<h2>Data Visualization & EDA</h2>

In [1]:
# Standard Libraries
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import textwrap
import tabulate

# Date & Time
import datetime as dt
import calendar
from calendar import monthrange

# Data Visualization
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots
from IPython.display import HTML
from IPython.display import Markdown

# Statistics & Maths
import math
import scipy.stats as stats
from scipy import stats
from scipy.stats import mannwhitneyu
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, root_mean_squared_error
import ruptures as rpt
from statsmodels.tsa.stattools import acf
from statsmodels.tsa.seasonal import STL
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.statespace.sarimax import SARIMAX

# Functions
import sys
import os

# Add parent directory + SCRIPTS to the import path
sys.path.append(os.path.abspath("../SCRIPTS"))

from DATA_ANALYSIS import DESCRIBE_VARIABLE, DAY_TYPE_LABELLING, TEMPORAL_AGGREGATION, RUN_STAT_TEST, MAP_STATION_COORDINATES
from REPORT_MANAGEMENT import REGISTER_REPORT_COMPONENT, SAVE_PLOT_AND_REGISTER, GENERATE_REPORT, FORMAT_SUMMARY_TABLE, FORMAT_VALUE, CLEAR_FIGURE_MANIFEST

In [2]:
# Report Contents Reinitisalisation
CLEAR_FIGURE_MANIFEST()

✅ Cleared existing figure manifest at C:\Folders\LightSouls888\CASH_FLOW_DATA_ANALYSIS\FIGURE_MANIFEST.json.

<h1>Data Overview</h1>
Number of records, missing values, date range, category distribution

In [3]:
# Cleaned Full Dataset (CASH_FLOW_CLEANED.csv)
CASH_FLOW = pd.read_csv('../DATA/PROCESSED/CASH_FLOW_CLEANED.csv', parse_dates=["Date"])
CASH_FLOW.head()

,Date,Year,ISO Year,Month,Month Label,Week,Week Label,Day,Category,Item,Vendor,Vendor Location,District,Income/Expenses,Amount,Formatted Date,Outlier
0,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Telephone,Top Up Singtel Card,7-Eleven,Blank,Clementi,Expenses,10.0,28/05/2019,False
1,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,15.3,28/05/2019,False
2,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Drinks,Bubble Tea,Koi,Takashimaya,Orchard,Expenses,1.8,28/05/2019,False
3,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,32.0,28/05/2019,False
4,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Food,Korean BBQ,I Am Kim,Blank,Rochor,Expenses,15.0,28/05/2019,False

In [4]:
# Dataset Description
CASH_FLOW.describe()

,Date,Year,ISO Year,Month,Week,Amount
count,3871,3871.000000,3871.000000,3871.000000,3871.000000,3871.000000
mean,2021-05-26 18:34:30.162748672,2020.894859,2020.893568,6.618962,26.928701,21.262116
min,2018-10-28 00:00:00,2018.000000,2018.000000,1.000000,1.000000,0.300000
25%,2020-01-02 00:00:00,2020.000000,2020.000000,3.000000,12.000000,4.500000
50%,2021-06-20 00:00:00,2021.000000,2021.000000,7.000000,27.000000,7.000000
75%,2022-09-28 00:00:00,2022.000000,2022.000000,10.000000,41.000000,10.600000
max,2023-12-31 00:00:00,2023.000000,2023.000000,12.000000,53.000000,432.100000
std,NaN,1.553042,1.551206,3.610599,15.734574,54.434321

In [5]:
# Dataset Information
CASH_FLOW.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3871 entries, 0 to 3870
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             3871 non-null   datetime64[ns]
 1   Year             3871 non-null   int64
 2   ISO Year         3871 non-null   int64
 3   Month            3871 non-null   int64
 4   Month Label      3871 non-null   object
 5   Week             3871 non-null   int64
 6   Week Label       3871 non-null   object
 7   Day              3871 non-null   object
 8   Category         3871 non-null   object
 9   Item             3871 non-null   object
 10  Vendor           3871 non-null   object
 11  Vendor Location  3871 non-null   object
 12  District         3871 non-null   object
 13  Income/Expenses  3871 non-null   object
 14  Amount           3871 non-null   float64
 15  Formatted Date   3871 non-null   object
 16  Outlier          3871 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(4), object(10)
memory usage: 487.8+ KB

In [6]:
# Cleaned Expenses Dataset (EXPENSES_CLEANED.csv)
EXPENSES = pd.read_csv('../DATA/PROCESSED/EXPENSES_CLEANED.csv', parse_dates=["Date"])
EXPENSES.head()

,Date,Year,ISO Year,Month,Month Label,Week,Week Label,Day,Category,Item,Vendor,Vendor Location,District,Income/Expenses,Amount,Formatted Date,Outlier
0,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Telephone,Top Up Singtel Card,7-Eleven,Blank,Clementi,Expenses,10.0,28/05/2019,False
1,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,15.3,28/05/2019,False
2,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Drinks,Bubble Tea,Koi,Takashimaya,Orchard,Expenses,1.8,28/05/2019,False
3,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,32.0,28/05/2019,False
4,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Food,Korean BBQ,I Am Kim,Blank,Rochor,Expenses,15.0,28/05/2019,False

In [7]:
# Expenses Dataset Description
EXPENSES.describe()

,Date,Year,ISO Year,Month,Week,Amount
count,3667,3667.000000,3667.000000,3667.000000,3667.000000,3667.000000
mean,2021-05-24 00:25:55.058630912,2020.887101,2020.886556,6.615490,26.902918,9.617671
min,2018-10-28 00:00:00,2018.000000,2018.000000,1.000000,1.000000,0.300000
25%,2020-01-01 00:00:00,2020.000000,2020.000000,3.000000,12.000000,4.500000
50%,2021-06-15 00:00:00,2021.000000,2021.000000,7.000000,27.000000,6.500000
75%,2022-09-23 12:00:00,2022.000000,2022.000000,10.000000,41.000000,10.000000
max,2023-12-13 00:00:00,2023.000000,2023.000000,12.000000,53.000000,188.000000
std,NaN,1.553489,1.551868,3.610082,15.739157,10.774103

In [8]:
# Expenses Dataset Information
EXPENSES.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3667 entries, 0 to 3666
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             3667 non-null   datetime64[ns]
 1   Year             3667 non-null   int64
 2   ISO Year         3667 non-null   int64
 3   Month            3667 non-null   int64
 4   Month Label      3667 non-null   object
 5   Week             3667 non-null   int64
 6   Week Label       3667 non-null   object
 7   Day              3667 non-null   object
 8   Category         3667 non-null   object
 9   Item             3667 non-null   object
 10  Vendor           3667 non-null   object
 11  Vendor Location  3667 non-null   object
 12  District         3667 non-null   object
 13  Income/Expenses  3667 non-null   object
 14  Amount           3667 non-null   float64
 15  Formatted Date   3667 non-null   object
 16  Outlier          3667 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(4), object(10)
memory usage: 462.1+ KB

In [9]:
# Cleaned Income Dataset (INCOME_CLEANED.csv)
INCOME = pd.read_csv('../DATA/PROCESSED/INCOME_CLEANED.csv', parse_dates=["Date"])
INCOME.head()

,Date,Year,ISO Year,Month,Month Label,Week,Week Label,Day,Category,Item,Vendor,Vendor Location,District,Income/Expenses,Amount,Formatted Date,Outlier
0,2019-05-27,2019,2019,5,May,22,W22,Monday,Cash Withdrawal,Cash Withdrawal,Blank,Blank,Blank,Income,100.0,27/05/2019,False
1,2019-05-15,2019,2019,5,May,20,W20,Wednesday,Cash Withdrawal,Cash Withdrawal,Blank,Blank,Blank,Income,200.0,15/05/2019,False
2,2019-05-04,2019,2019,5,May,18,W18,Saturday,Cash Withdrawal,Cash Withdrawal,Blank,Blank,Blank,Income,200.0,04/05/2019,False
3,2019-05-01,2019,2019,5,May,18,W18,Wednesday,Last Month's Balance,April's Balance,Blank,Blank,Blank,Income,215.8,01/05/2019,True
4,2019-04-21,2019,2019,4,April,16,W16,Sunday,Cash Withdrawal,Cash Withdrawal,Blank,Blank,Blank,Income,200.0,21/04/2019,False

In [10]:
# Expenses Dataset Description
INCOME.describe()

,Date,Year,ISO Year,Month,Week,Amount
count,204,204.000000,204.000000,204.000000,204.000000,204.000000
mean,2021-07-15 07:31:45.882352896,2021.034314,2021.019608,6.681373,27.392157,230.576716
min,2018-10-28 00:00:00,2018.000000,2018.000000,1.000000,1.000000,20.700000
25%,2020-02-29 06:00:00,2020.000000,2020.000000,3.000000,13.000000,170.325000
50%,2021-09-12 12:00:00,2021.000000,2021.000000,7.000000,27.500000,267.250000
75%,2022-11-15 06:00:00,2022.000000,2022.000000,10.000000,42.000000,300.000000
max,2023-12-31 00:00:00,2023.000000,2023.000000,12.000000,53.000000,432.100000
std,NaN,1.542118,1.537578,3.628221,15.683229,88.963215

In [11]:
# Expenses Dataset Information
INCOME.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             204 non-null    datetime64[ns]
 1   Year             204 non-null    int64
 2   ISO Year         204 non-null    int64
 3   Month            204 non-null    int64
 4   Month Label      204 non-null    object
 5   Week             204 non-null    int64
 6   Week Label       204 non-null    object
 7   Day              204 non-null    object
 8   Category         204 non-null    object
 9   Item             204 non-null    object
 10  Vendor           204 non-null    object
 11  Vendor Location  204 non-null    object
 12  District         204 non-null    object
 13  Income/Expenses  204 non-null    object
 14  Amount           204 non-null    float64
 15  Formatted Date   204 non-null    object
 16  Outlier          204 non-null    bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(4), object(10)
memory usage: 25.8+ KB

<hr>
<hr>

<h1>Descriptive Analysis</h1>
<p>Identification on what is in the data</p>

In [12]:
# Report Management
SECTION_TITLE = "Descriptive Analysis"
SECTION_CAPTION = "Identification on what is in the data"
REGISTER_REPORT_COMPONENT(
    REPORTING_TAG="DESCRIPTIVE_ANALYSIS",
    TITLE=SECTION_TITLE,
    CONTENT=SECTION_CAPTION,
    TYPE="text",
    HEADING="h2",
    BODY="normal",
    PATH=None
)

✅ Registered component: DESCRIPTIVE_ANALYSIS with Title Descriptive Analysis

<h2>Global View</h2>
<p>What is the total amount spent and how many transactions in total?</p>
<p> --> To show the Total Amount and Transaction on the Global View to get the insight of financial scale and activity level</p>

In [13]:
# Total Amount Spent + Total Number of Transactions
TOTAL_SPENT = EXPENSES["Amount"].sum()
TOTAL_TRANSACTIONS_EXPENSES = len(EXPENSES)

CAPTION = f"""
Total amount of Expenses: S${TOTAL_SPENT:,.2f} and total number of expense transactions: {TOTAL_TRANSACTIONS_EXPENSES}
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)

TOTAL_INCOME = INCOME["Amount"].sum()
TOTAL_TRANSACTIONS_INCOME = len(INCOME)

CAPTION_2 = f"""
Total amount of Income: S${TOTAL_INCOME:,.2f} and total number of income transactions: {TOTAL_TRANSACTIONS_INCOME}
"""

CAPTION_2_WRAPPED = textwrap.fill(CAPTION_2, width=130)
print(CAPTION_2_WRAPPED)

print("\n--------------------------------\n")

REGISTER_REPORT_COMPONENT(
    TITLE="Global View of Expenses & Income",
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="h3",
    BODY="point",
    PATH=None,
    REPORTING_TAG="DESCRIPTIVE_ANALYSIS_GLOBAL_VIEW"
)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_2_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="DESCRIPTIVE_ANALYSIS_GLOBAL_VIEW_BODY"
)

 Total amount of Expenses: S$35,268.00 and total number of expense transactions: 3667
 Total amount of Income: S$47,037.65 and total number of income transactions: 204

--------------------------------

✅ Registered component: DESCRIPTIVE_ANALYSIS_GLOBAL_VIEW with Title Global View of Expenses & Income

<hr>

<h2>Pie Chart</h2>
<p>What are the top spending categories?</p>
<p> --> To display the Top 7 Categories of Expenses with the rest of the Categories grouped as "Others" to show priority areas</p>

In [14]:
# Top 7 Expensive Categories
TOP_N = 7
CATEGORY_SUM = CASH_FLOW[CASH_FLOW['Income/Expenses'] == "Expenses"].groupby(["Category"])["Amount"].sum().reset_index().sort_values(by="Amount", ascending=False, ignore_index=True)
CATEGORY_SUM

          Category    Amount
0             Food  23377.65
1   Transportation   3426.30
2             Gift   1756.20
3         Clothing    771.80
4        Groceries    718.60
5          Dessert    647.80
6           Drinks    621.65
7             Home    455.30
8      Electronics    447.40
9    Entertainment    435.30
10       Telephone    414.00
11          Others    313.30
12          Snacks    297.50
13          Movies    256.70
14       Body Care    248.90
15        Shopping    236.60
16         Haircut    213.30
17           Sport    170.70
18          Fruits     99.35
19       Education     96.90
20         Package     64.20
21      Stationary     61.55
22          Health     47.50
23          Repair     47.00
24        Document     35.00
25         Laundry      7.50

In [15]:
# Separate Top N Categories
TOP_CATEGORIES = CATEGORY_SUM.head(TOP_N)
OTHERS_TOTAL = CATEGORY_SUM.iloc[TOP_N:]["Amount"].sum()

OTHERS_ROW = pd.DataFrame({"Category": ["Others"], "Amount": [OTHERS_TOTAL]})

PIE_DATA = pd.concat([TOP_CATEGORIES, OTHERS_ROW], ignore_index=True)
PIE_DATA.columns = ["Category", "Amount"]
PIE_DATA["Allocation"] = round((PIE_DATA["Amount"] / PIE_DATA["Amount"].sum()) * 100, 2)
PIE_DATA

         Category    Amount  Allocation
0            Food  23377.65       66.29
1  Transportation   3426.30        9.72
2            Gift   1756.20        4.98
3        Clothing    771.80        2.19
4       Groceries    718.60        2.04
5         Dessert    647.80        1.84
6          Drinks    621.65        1.76
7          Others   3948.00       11.19

In [16]:
# Pie Chart
fig = px.pie(
    PIE_DATA,
    names="Category",
    values="Amount",
    title=f"Spending by Category (Top {TOP_N} + Others)",
    template="plotly_dark",
    color_discrete_sequence=px.colors.qualitative.Pastel
)

fig.update_traces(textinfo="label+percent", textposition="outside")
fig.update_layout(legend_title_text="Category")

fig.show()

In [17]:
# Top N Categories Allocation Data Summary
TOP_N_ALLOCATION = PIE_DATA[PIE_DATA["Category"] != "Others"]["Allocation"].sum()
TOP_N_HIGHEST_ALLOCATION = PIE_DATA[PIE_DATA["Category"] != "Others"].sort_values("Allocation", ascending=False).iloc[0]

TOP_N_HIGHEST_CATEGORY = TOP_N_HIGHEST_ALLOCATION["Category"]
TOP_N_HIGHEST_ALLOCATION = TOP_N_HIGHEST_ALLOCATION["Allocation"]

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
Top {TOP_N} categories account for {TOP_N_ALLOCATION:.2f}% of the total spending with the highest category spending being {TOP_N_HIGHEST_CATEGORY} at {TOP_N_HIGHEST_ALLOCATION:.2f}%.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME=f"PIE_CHART_TOP_{TOP_N}_SPENDING_CATEGORIES.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Top 7 categories account for 88.82% of the total spending with the highest category spending being Food at 66.29%.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\PIE_CHART_TOP_7_SPENDING_CATEGORIES.png
✅ Registered component: PIE_CHART_TOP_7_SPENDING_CATEGORIES.png with Title Spending by Category (Top 7 + Others)

<hr>

<h2>Histogram</h2>
<p>What is the distribution of the purchase sizes?</p>
<p> --> To show the distribution of purchase frequency in histogram and boxplot to show clarity on the skewness and common amounts</p>

In [18]:
# Report Management
SUBSECTION_TITLE = "Distribution Visualisation & Analysis"
SUBSECTION_CAPTION = "To analyse the distribution of purchase frequency in histogram and boxplot to show clarity on the skewness and common amounts"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="DESCRIPTIVE_ANALYSIS_HISTOGRAM"
)

✅ Registered component: DESCRIPTIVE_ANALYSIS_HISTOGRAM with Title Distribution Visualisation & Analysis

In [19]:
# Histogram of Purchase Amount
fig = px.histogram(
    EXPENSES,
    x="Amount",
    nbins=50,
    title="Distribution of Purchase Sizes (Histogram)",
    marginal="box",  # Adds boxplot on top
    template="plotly_dark",
    opacity=0.75
)

fig.update_layout(xaxis_title="Amount", yaxis_title="Frequency")
fig.show()

fig_html = fig.to_html(full_html=False, include_plotlyjs='cdn')

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = """
The general spending amount distribution is heavily concentrated in the lower value range (left side), with a long right tail. This pattern reflects frequent low-cost purchases (such as, daily food or transport) and a few large-value expenses, possibly one-time or monthly essentials.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")
SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="HISTOGRAM_DISTRIBUTION_OF_PURCHASE_SIZES.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The general spending amount distribution is heavily concentrated in the lower value range (left side), with a long right tail.
This pattern reflects frequent low-cost purchases (such as, daily food or transport) and a few large-value expenses, possibly one-
time or monthly essentials.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\HISTOGRAM_DISTRIBUTION_OF_PURCHASE_SIZES.png
✅ Registered component: HISTOGRAM_DISTRIBUTION_OF_PURCHASE_SIZES.png with Title Distribution of Purchase Sizes (Histogram)

<hr>

<h2>General Descriptive Statistics</h2>
<p>What is generally the details of the spending amount from the statistics point of view?</p>
<p> --> To display the descriptive statistics in a form of a summary table to potentially draw insight on the bias from outliers</p>

In [20]:
# Variable Description Depending on Outlier Status
EXCLUDE_OUTLIERS = True

VARIABLE_DESCRIPTION_WITHOUT_OUTLIER = DESCRIBE_VARIABLE(EXPENSES, "Amount", EXCLUDE_OUTLIERS)
VARIABLE_DESCRIPTION_WITHOUT_OUTLIER

,Count,Mean,Median,Std Dev,Min,Lower Outlier Bound,Q1 (25%),Q3 (75%),Upper Outlier Bound,IQR,Max,Skewness,Kurtosis
Amount,3331,6.95,6.5,3.51,0.3,-3.75,4.5,10.0,18.25,5.5,18.2,0.85,0.52

In [21]:
# Report Management
REGISTER_REPORT_COMPONENT(
    TITLE="Descriptive Statistics Summary",
    CONTENT=FORMAT_SUMMARY_TABLE(VARIABLE_DESCRIPTION_WITHOUT_OUTLIER),
    TYPE="table",
    HEADING="h4",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="DESCRIPTIVE_ANALYSIS_DESC_STATS"
)

✅ Registered component: DESCRIPTIVE_ANALYSIS_DESC_STATS with Title Descriptive Statistics Summary

In [22]:
# Report Management
CAPTION = f"""
The overall spending distribution is moderately right-skewed ({VARIABLE_DESCRIPTION_WITHOUT_OUTLIER['Skewness'].iloc[0]:.2f}) indicating a higher concentration of small purchases along with a few large outliers. The kurtosis ({VARIABLE_DESCRIPTION_WITHOUT_OUTLIER["Kurtosis"].iloc[0]:.2f}) suggests extreme spending events are relatively rare and the distribution is more flattened than a normal bell curve.
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)

print("\n--------------------------------\n")

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="DESCRIPTIVE_ANALYSIS_DESC_STATS_BODY"
)

 The overall spending distribution is moderately right-skewed (0.85) indicating a higher concentration of small purchases along
with a few large outliers. The kurtosis (0.52) suggests extreme spending events are relatively rare and the distribution is more
flattened than a normal bell curve.

--------------------------------

In [23]:
# Plot of the Variable Description Showing the Outlier Boundaries
if EXCLUDE_OUTLIERS:
    EXPENSES_WITHOUT_OUTLIERS = EXPENSES[EXPENSES["Outlier"] == False]

fig = px.histogram(
    EXPENSES_WITHOUT_OUTLIERS,
    x="Amount",
    nbins=50,
    title="Distribution of Purchase Sizes Without Outliers (Histogram)",
    template="plotly_dark",
    opacity=0.75
)

STAT_VISUAL_LIST = [
    [VARIABLE_DESCRIPTION_WITHOUT_OUTLIER["Mean"].iloc[0], "#FF6961", "Mean"],
    [VARIABLE_DESCRIPTION_WITHOUT_OUTLIER["Median"].iloc[0], "#77DD77", "Median"],
    [VARIABLE_DESCRIPTION_WITHOUT_OUTLIER["Lower Outlier Bound"].iloc[0], "#C76E00", "Lower Outlier Bound"],
    [VARIABLE_DESCRIPTION_WITHOUT_OUTLIER["Upper Outlier Bound"].iloc[0], "#C76E00", "Upper Outlier Bound"]
]

for STAT in STAT_VISUAL_LIST:
    fig.add_vline(
        x=STAT[0], 
        line_width=2, 
        line_dash="dash", 
        line_color=STAT[1], 
        annotation_text=STAT[2], 
        annotation_position="top right", 
        annotation_textangle=90
    )

fig.update_layout(xaxis_title="Amount", yaxis_title="Frequency")
fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = """
Upon visualised, there are considerable number of outliers beyond Upper Outlier Bound.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="HISTOGRAM_DISTRIBUTION_OF_PURCHASE_SIZES_WITHOUT_OUTLIERS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Upon visualised, there are considerable number of outliers beyond Upper Outlier Bound.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\HISTOGRAM_DISTRIBUTION_OF_PURCHASE_SIZES_WITHOUT_OUTLIERS.png
✅ Registered component: HISTOGRAM_DISTRIBUTION_OF_PURCHASE_SIZES_WITHOUT_OUTLIERS.png with Title Distribution of Purchase Sizes Without Outliers (Histogram)

<hr>
<hr>

<h1>Behavioral Patterns</h1>
<p>Analysis to answer the question how I spend</p>

In [24]:
# Report Management
SECTION_TITLE = "Behavioral Patterns"
SECTION_CAPTION = "Analysis to answer the question how I spend"
REGISTER_REPORT_COMPONENT(
    TITLE=SECTION_TITLE,
    CONTENT=SECTION_CAPTION,
    TYPE="text",
    HEADING="h2",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS"
)

✅ Registered component: BEHAVIOURAL_PATTERNS with Title Behavioral Patterns

<h2>Boxplot per Category</h2>
<p>Which categories have the largest typical purchase?</p>
<p> --> To display boxplot for each category to draw general behavior</p>

In [25]:
# Report Management
SUBSECTION_TITLE = "General View of Purchase Size by Category"
SUBSECTION_CAPTION = "To showcase which categories have the largest typical purchase"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_BOXPLOT_CATEGORY"
)

✅ Registered component: BEHAVIOURAL_PATTERNS_BOXPLOT_CATEGORY with Title General View of Purchase Size by Category

In [26]:
# Boxplot of Purchase Amount (Zoomed-in)
fig2 = px.strip(
    EXPENSES,
    x="Amount",
    y="Category",
    color="Outlier",  # Highlight outlier status
    orientation="h",
    color_discrete_map={
        True: "red", 
        False: "white"
    }
)

fig = px.box(
    EXPENSES,
    x="Amount",
    y="Category",
    color="Category",
    title="Purchase Size by Category",
    custom_data=["Amount", "Category", "Outlier"],
    template="plotly_dark",
    points=False,
    orientation="h"
)

fig.add_traces(fig2.data)

fig.update_traces(
    hovertemplate="<br>".join([
        "Category: %{y}",
        "Total Amount: S$%{x:.2f}"
    ])
)

fig.update_layout(
    height=1500, 
    xaxis_title="Total Amount (S$)", 
    yaxis_title="Category"
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = """
Since each category has distinct data range and descriptive statistics, it is only reasonable the outliers are detected within each category separately.
Upon outlier detection, red and white dots signify outlier and non-outlier data points respectively.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="BOX_PLOT_PURCHASE_SIZE_BY_CATEGORY.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Since each category has distinct data range and descriptive statistics, it is only reasonable the outliers are detected within
each category separately. Upon outlier detection, red and white dots signify outlier and non-outlier data points respectively.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\BOX_PLOT_PURCHASE_SIZE_BY_CATEGORY.png
✅ Registered component: BOX_PLOT_PURCHASE_SIZE_BY_CATEGORY.png with Title Purchase Size by Category

In [27]:
# Boxplot of Purchase Amount (Zoomed-in) without Outliers
fig2 = px.strip(
    EXPENSES_WITHOUT_OUTLIERS,
    x="Amount",
    y="Category",
    color="Outlier",  # Highlight outlier status
    orientation="h",
    color_discrete_map={
        True: 'red', 
        False: 'white'
    }
)

fig = px.box(
    EXPENSES_WITHOUT_OUTLIERS,
    x="Amount",
    y="Category",
    color="Category",
    title="Purchase Size by Category Without Outliers",
    template="plotly_dark",
    points=False,
    orientation="h"
)

fig.add_traces(fig2.data)

fig.update_traces(
    hovertemplate="<br>".join([
        "Category: %{y}",
        "Total Amount: S$%{x:.2f}"
    ])
)

fig.update_layout(
    height=1500, 
    xaxis_title="Total Amount (S$)", 
    yaxis_title="Category"
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = """
In contrast, this boxplot contains no outlier.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="BOX_PLOT_PURCHASE_SIZE_BY_CATEGORY_WITHOUT_OUTLIERS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 In contrast, this boxplot contains no outlier.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\BOX_PLOT_PURCHASE_SIZE_BY_CATEGORY_WITHOUT_OUTLIERS.png
✅ Registered component: BOX_PLOT_PURCHASE_SIZE_BY_CATEGORY_WITHOUT_OUTLIERS.png with Title Purchase Size by Category Without Outliers

<hr>

<h2>Bar Chart by Weekday</h2>
<p>How would the spending behavior look like within the days of the week?</p>
<p> --> To show the spending pattern within the days of the week</p>

In [28]:
# Report Management
SUBSECTION_TITLE = "Spending Behaviour Based on the Days within the Week"
SUBSECTION_CAPTION = "To show the spending pattern within the days of the week"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_BAR_CHART_DAYS_WITHIN_WEEK"
)

✅ Registered component: BEHAVIOURAL_PATTERNS_BAR_CHART_DAYS_WITHIN_WEEK with Title Spending Behaviour Based on the Days within the Week

In [29]:
# Aggregating the Amount and Transaction Frequency Based on Days within the Week
DAY_IN_A_WEEK_AGG = TEMPORAL_AGGREGATION(EXPENSES, "Day", "Amount")
DAY_IN_A_WEEK_AGG

         Day  TOTAL_AMOUNT  TRANSACTION_FREQUENCY  AVERAGE_AMOUNT
0     Friday       5276.95                    543            9.72
1     Monday       4645.80                    523            8.88
2   Saturday       3606.10                    361            9.99
3     Sunday       6784.50                    610           11.12
4   Thursday       4998.95                    538            9.29
5    Tuesday       5179.20                    561            9.23
6  Wednesday       4776.50                    531            9.00

In [30]:
# Day with Highest Spending
DAY_WITH_HIGHEST_SPENDING = DAY_IN_A_WEEK_AGG.sort_values("AVERAGE_AMOUNT", ascending=False).iloc[0]
DAY_WITH_LOWEST_SPENDING = DAY_IN_A_WEEK_AGG.sort_values("AVERAGE_AMOUNT", ascending=True).iloc[0]
DAY_IN_A_WEEK_WITH_HIGHEST_SPENDING = DAY_WITH_HIGHEST_SPENDING["Day"]
DAY_IN_A_WEEK_WITH_LOWEST_SPENDING = DAY_WITH_LOWEST_SPENDING["Day"]

print(DAY_IN_A_WEEK_WITH_LOWEST_SPENDING, DAY_IN_A_WEEK_WITH_HIGHEST_SPENDING)

Monday Sunday

In [31]:
# Average Gap between Day with Highest Spending and Rest of the Week
REST_OF_THE_WEEK = DAY_IN_A_WEEK_AGG[DAY_IN_A_WEEK_AGG["Day"] != DAY_IN_A_WEEK_WITH_HIGHEST_SPENDING]
AVERAGE_TOTAL_AMOUNT_OF_REST_OF_THE_WEEK = REST_OF_THE_WEEK["AVERAGE_AMOUNT"].mean()
AVERAGE_TOTAL_AMOUNT_OF_REST_OF_THE_WEEK

AVERAGE_GAP = DAY_WITH_HIGHEST_SPENDING["AVERAGE_AMOUNT"] - AVERAGE_TOTAL_AMOUNT_OF_REST_OF_THE_WEEK
AVERAGE_GAP_PERCENT = round((AVERAGE_GAP / AVERAGE_TOTAL_AMOUNT_OF_REST_OF_THE_WEEK) * 100, 1)
AVERAGE_GAP_PERCENT

np.float64(18.9)

In [32]:
# Interactive Bar Plot
fig = px.bar(
    DAY_IN_A_WEEK_AGG, 
    x="Day", 
    y="TOTAL_AMOUNT", 
    color="Day", 
    title="Spending Behaviour by Day of the Week", 
    color_discrete_sequence=px.colors.qualitative.Pastel1,
    custom_data=["TOTAL_AMOUNT", "TRANSACTION_FREQUENCY", "AVERAGE_AMOUNT"],
    text="TOTAL_AMOUNT",
    template="plotly_dark",
    category_orders={"Day": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]}
)

fig.update_traces(
    hovertemplate="<br>".join([
        "Day: %{x}",
        "Total Amount: S$%{text}",
        "Transaction Frequency: %{customdata[1]}",
        "Average Amount: S$%{customdata[2]}"
    ]),
    textposition="outside",
    texttemplate="S$%{text}"
)

fig.update_layout(
    xaxis_title="Total Amount (S$)", 
    yaxis_title="Day of the Week"
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
Spending is highest on {DAY_IN_A_WEEK_WITH_HIGHEST_SPENDING}, with average transaction values approximately {AVERAGE_GAP_PERCENT}% above the average levels of the other days in a week.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="BAR_PLOT_SPENDING_BEHAVIOUR_BY_DAY.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

CAPTION2 = f"""
Weekdays reflect routine low-value spending (e.g., transport, food).
"""
CAPTION2_WRAPPED = textwrap.fill(CAPTION2, width=130)
print(CAPTION2_WRAPPED)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION2_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="BAR_PLOT_SPENDING_BEHAVIOUR_BY_DAY_BODY_1"
)

print("\n--------------------------------\n")

CAPTION3 = f"""
 {DAY_IN_A_WEEK_WITH_LOWEST_SPENDING}s reflect the lowest spending level across the days which are aligned as there is typically no outside activities (e.g. going out, eating out) on {DAY_IN_A_WEEK_WITH_LOWEST_SPENDING}s.
"""
CAPTION3_WRAPPED = textwrap.fill(CAPTION3, width=130)
print(CAPTION3_WRAPPED)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION3_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="BAR_PLOT_SPENDING_BEHAVIOUR_BY_DAY_BODY_2"
)

 Spending is highest on Sunday, with average transaction values approximately 18.9% above the average levels of the other days in
a week.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\BAR_PLOT_SPENDING_BEHAVIOUR_BY_DAY.png
✅ Registered component: BAR_PLOT_SPENDING_BEHAVIOUR_BY_DAY.png with Title Spending Behaviour by Day of the Week
 Weekdays reflect routine low-value spending (e.g., transport, food).

--------------------------------

  Mondays reflect the lowest spending level across the days which are aligned as there is typically no outside activities (e.g.
going out, eating out) on Mondays.

<hr>

<h2>Weekends vs Weekdays</h2>
<p>How would the spending behavior differ between weekends and weekdays?</p>
<p> --> To show the comparison of spending between weekends and weekdays</p>

In [33]:
# Report Management
SUBSECTION_TITLE = "Weekends vs Weekdays Analysis"
SUBSECTION_CAPTION = "To show the comparison of spending between weekends and weekdays"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_WEEKENDS_VS_WEEKDAYS"
)

✅ Registered component: BEHAVIOURAL_PATTERNS_WEEKENDS_VS_WEEKDAYS with Title Weekends vs Weekdays Analysis

In [34]:
# Apply Day Type Labeling to EXPENSES Dataset
WEEKEND_LIST = ["Saturday", "Sunday"]
EXPENSES_WEEKEND_LABELLED_1 = DAY_TYPE_LABELLING(EXPENSES, "Day", WEEKEND_LIST)
EXPENSES_WEEKEND_LABELLED_1.head()

,Date,Year,ISO Year,Month,Month Label,Week,Week Label,Day,Category,Item,Vendor,Vendor Location,District,Income/Expenses,Amount,Formatted Date,Outlier,Day Type
0,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Telephone,Top Up Singtel Card,7-Eleven,Blank,Clementi,Expenses,10.0,28/05/2019,False,Weekday
1,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,15.3,28/05/2019,False,Weekday
2,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Drinks,Bubble Tea,Koi,Takashimaya,Orchard,Expenses,1.8,28/05/2019,False,Weekday
3,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,32.0,28/05/2019,False,Weekday
4,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Food,Korean BBQ,I Am Kim,Blank,Rochor,Expenses,15.0,28/05/2019,False,Weekday

In [35]:
# Boxplot for Expenses Based on Day Type (Weekday vs Weekend)
fig = px.box(
    EXPENSES_WEEKEND_LABELLED_1,
    x="Amount",
    y="Day Type",
    color="Day Type",
    title="Spending Behaviour by Day Type (Weekday vs Weekend)",
    template="plotly_dark",
    orientation="h"
)

fig.update_layout(
    xaxis_title="Amount (S$)",
    yaxis_title="Day Type", 
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
Upon looking at the presented boxplot, the Spending is greater on Weekends than it is on Weekdays. In this case the significance of the difference needs to be assessed to obtain better understanding on the Spending Behaviours throughout the week.

From the histogram previously, the data is extremely right-skewed. 
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="SPENDING_BEHAVIOUR_WEEKEND_VS_WEEKDAY.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Upon looking at the presented boxplot, the Spending is greater on Weekends than it is on Weekdays. In this case the significance
of the difference needs to be assessed to obtain better understanding on the Spending Behaviours throughout the week.  From the
histogram previously, the data is extremely right-skewed.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\SPENDING_BEHAVIOUR_WEEKEND_VS_WEEKDAY.png
✅ Registered component: SPENDING_BEHAVIOUR_WEEKEND_VS_WEEKDAY.png with Title Spending Behaviour by Day Type (Weekday vs Weekend)

In [36]:
HTML(f"""
<div id="my_histogram_plot" style="border: 1px solid #ddd; padding: 10px;">
    {fig_html}
</div>
""")

In [37]:
# Report Management
CONFIDENCE_LEVEL = 0.99
CAPTION = f"""
Therefore, it is more sensible to utilise right-tailed test using Mann-Whitney U method on the data starting with {CONFIDENCE_LEVEL*100}% Confidence Level as a benchmark.
"""

CAPTION2 = """
Hypotheses for One-Tailed Test:
- Null Hypothesis: average amount spent on weekend less than or equal to average amount spent on weekday \n
    i.e. $H_0: \mu_{weekend} \leq \mu_{weekday}$
- Alternative Hypothesis: average amount spent on weekend greater than average amount spent on weekday \n
    i.e. $H_1: \mu_{weekend} > \mu_{weekday}$
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)
print(CAPTION2)

print("\n--------------------------------\n")

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_STAT_TEST_BODY_1"
)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION2,
    TYPE="text",
    HEADING="normal",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_STAT_TEST_BODY_2"
)

 Therefore, it is more sensible to utilise right-tailed test using Mann-Whitney U method on the data starting with 99.0%
Confidence Level as a benchmark.

Hypotheses for One-Tailed Test:
- Null Hypothesis: average amount spent on weekend less than or equal to average amount spent on weekday

    i.e. $H_0: \mu_{weekend} \leq \mu_{weekday}$
- Alternative Hypothesis: average amount spent on weekend greater than average amount spent on weekday

    i.e. $H_1: \mu_{weekend} > \mu_{weekday}$


--------------------------------

<>:7: SyntaxWarning:

invalid escape sequence '\m'

<>:7: SyntaxWarning:

invalid escape sequence '\m'

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\368444719.py:7: SyntaxWarning:

invalid escape sequence '\m'

In [38]:
# Mann-Whitney U Test
TEST_RESULT_1 = RUN_STAT_TEST(
    GROUP1 = EXPENSES_WEEKEND_LABELLED_1["Amount"][EXPENSES_WEEKEND_LABELLED_1["Day Type"] == "Weekend"],
    GROUP2 = EXPENSES_WEEKEND_LABELLED_1["Amount"][EXPENSES_WEEKEND_LABELLED_1["Day Type"] == "Weekday"],
    METHOD = "mannwhitney",
    DIRECTION = "greater",  # one-tailed: Weekend > Weekday
    CONFIDENCE = CONFIDENCE_LEVEL
)

print("Statistical Test Result")
print("-----------------------")
for k, v in TEST_RESULT_1.items():
    print(f"- {k}: {v}")

Statistical Test Result
-----------------------
- Test: Mann-Whitney U Test
- p-value: 0.0
- Group1_Mean: 10.7
- Group1_CI: (np.float64(9.71), np.float64(11.69))
- Group2_Mean: 9.23
- Group2_CI: (np.float64(8.72), np.float64(9.74))
- Conclusion: Reject H₀ (Significant)

In [39]:
# Transform the Statistical Test Result Table 1 into Pandas DataFrame
TEST_RESULT_1_DF = pd.DataFrame(list(TEST_RESULT_1.items()), columns=["Metric", "Value"])
TEST_RESULT_1_DF.loc[TEST_RESULT_1_DF["Metric"] == "Conclusion", "Value"] = TEST_RESULT_1_DF.loc[
    TEST_RESULT_1_DF["Metric"] == "Conclusion", "Value"
].str.replace("H₀", "$H_0$", regex=False)
TEST_RESULT_1_DF["Value"] = TEST_RESULT_1_DF["Value"].apply(FORMAT_VALUE)
TEST_RESULT_1_DF

        Metric                       Value
0         Test         Mann-Whitney U Test
1      p-value                        0.00
2  Group1_Mean                       10.70
3    Group1_CI               (9.71, 11.69)
4  Group2_Mean                        9.23
5    Group2_CI                (8.72, 9.74)
6   Conclusion  Reject $H_0$ (Significant)

In [40]:
# Significance Status
if float(TEST_RESULT_1_DF.loc[TEST_RESULT_1_DF["Metric"] == "p-value"]["Value"].values[0]) < (1 - CONFIDENCE_LEVEL):
    SIGNIFICANCE = "significant"
else:
    SIGNIFICANCE = "insignificant"

In [41]:
# Report Management
CAPTION = f"""
The result of the first statistical test is as follows:
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)
REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_STAT_TEST_RESULT_INTRO_1"
)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=TEST_RESULT_1_DF.to_markdown(index=False),
    TYPE="table",
    HEADING="normal",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_STAT_TEST_RESULT_1"
)

CAPTION2 = f"""
With the p-value {TEST_RESULT_1_DF.loc[TEST_RESULT_1_DF["Metric"] == "p-value"]["Value"].values[0]} < {round(1 - CONFIDENCE_LEVEL,2)}, it is discovered that there is a statistically {SIGNIFICANCE} difference on average spending between weekends and weekdays. Hence, {TEST_RESULT_1_DF.loc[TEST_RESULT_1_DF["Metric"] == "Conclusion"]["Value"].values[0]} at {CONFIDENCE_LEVEL * 100}% confidence level.
"""

CAPTION2_WRAPPED = textwrap.fill(CAPTION2, width=130)
print(CAPTION2_WRAPPED)
REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION2_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_STAT_TEST_RESULT_CAPTION_1"
)

 The result of the first statistical test is as follows:
 With the p-value 0.00 < 0.01, it is discovered that there is a statistically significant difference on average spending between
weekends and weekdays. Hence, Reject $H_0$ (Significant) at 99.0% confidence level.

In [42]:
# Report Management
CAPTION = f"""
Depending on culture and life stage, Friday is sometimes considered as "weekend-like" periods according to many businesses because Friday night spending is often social or leisure. Another set of analysis is redone with the inclusion of Friday considered as weekend 
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)
REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_STAT_TEST_BODY_1"
)

 Depending on culture and life stage, Friday is sometimes considered as "weekend-like" periods according to many businesses
because Friday night spending is often social or leisure. Another set of analysis is redone with the inclusion of Friday
considered as weekend

In [43]:
# Apply Day Type Labeling to EXPENSES Dataset
WEEKEND_LIST = ["Friday", "Saturday", "Sunday"]
EXPENSES_WEEKEND_LABELLED_2 = DAY_TYPE_LABELLING(EXPENSES, "Day", WEEKEND_LIST)
EXPENSES_WEEKEND_LABELLED_2.head()

,Date,Year,ISO Year,Month,Month Label,Week,Week Label,Day,Category,Item,Vendor,Vendor Location,District,Income/Expenses,Amount,Formatted Date,Outlier,Day Type
0,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Telephone,Top Up Singtel Card,7-Eleven,Blank,Clementi,Expenses,10.0,28/05/2019,False,Weekday
1,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,15.3,28/05/2019,False,Weekday
2,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Drinks,Bubble Tea,Koi,Takashimaya,Orchard,Expenses,1.8,28/05/2019,False,Weekday
3,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,32.0,28/05/2019,False,Weekday
4,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Food,Korean BBQ,I Am Kim,Blank,Rochor,Expenses,15.0,28/05/2019,False,Weekday

In [44]:
# Boxplot for Expenses Based on Day Type (Weekday vs Weekend)
fig = px.box(
    EXPENSES_WEEKEND_LABELLED_2,
    x="Amount",
    y="Day Type",
    color="Day Type",
    title="Spending Behaviour by Day Type (Weekday vs Weekend + Friday)",
    template="plotly_dark",
    orientation="h"
)

fig.update_layout(
    xaxis_title="Amount (S$)",
    yaxis_title="Day Type", 
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
Upon looking at the presented boxplot, the Spending is still greater on Weekends than it is on Weekdays. The signficance test is going to be recalculated to confirm the findings.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="SPENDING_BEHAVIOUR_WEEKEND_VS_WEEKDAY_RECALCULATED.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Upon looking at the presented boxplot, the Spending is still greater on Weekends than it is on Weekdays. The signficance test is
going to be recalculated to confirm the findings.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\SPENDING_BEHAVIOUR_WEEKEND_VS_WEEKDAY_RECALCULATED.png
✅ Registered component: SPENDING_BEHAVIOUR_WEEKEND_VS_WEEKDAY_RECALCULATED.png with Title Spending Behaviour by Day Type (Weekday vs Weekend + Friday)

In [45]:
# Mann-Whitney U Statistical Test
TEST_RESULT_2 = RUN_STAT_TEST(
    GROUP1 = EXPENSES_WEEKEND_LABELLED_2["Amount"][EXPENSES_WEEKEND_LABELLED_2["Day Type"] == "Weekend"],
    GROUP2 = EXPENSES_WEEKEND_LABELLED_2["Amount"][EXPENSES_WEEKEND_LABELLED_2["Day Type"] == "Weekday"],
    METHOD = "mannwhitney",
    DIRECTION = "greater",  # one-tailed: Weekend > Weekday
    CONFIDENCE = 0.99
)

print("Statistical Test Result")
print("-----------------------")
for k, v in TEST_RESULT_2.items():
    print(f"- {k}: {v}")

Statistical Test Result
-----------------------
- Test: Mann-Whitney U Test
- p-value: 0.0
- Group1_Mean: 10.35
- Group1_CI: (np.float64(9.53), np.float64(11.17))
- Group2_Mean: 9.1
- Group2_CI: (np.float64(8.58), np.float64(9.63))
- Conclusion: Reject H₀ (Significant)

In [46]:
# Transform the Statistical Test Result Table 2 into Pandas DataFrame
TEST_RESULT_2_DF = pd.DataFrame(list(TEST_RESULT_2.items()), columns=["Metric", "Value"])
TEST_RESULT_2_DF.loc[TEST_RESULT_2_DF["Metric"] == "Conclusion", "Value"] = TEST_RESULT_2_DF.loc[
    TEST_RESULT_2_DF["Metric"] == "Conclusion", "Value"
].str.replace("H₀", "$H_0$", regex=False)
TEST_RESULT_2_DF["Value"] = TEST_RESULT_2_DF["Value"].apply(FORMAT_VALUE)
TEST_RESULT_2_DF

        Metric                       Value
0         Test         Mann-Whitney U Test
1      p-value                        0.00
2  Group1_Mean                       10.35
3    Group1_CI               (9.53, 11.17)
4  Group2_Mean                        9.10
5    Group2_CI                (8.58, 9.63)
6   Conclusion  Reject $H_0$ (Significant)

In [47]:
# Significance Status
if float(TEST_RESULT_1_DF.loc[TEST_RESULT_2_DF["Metric"] == "p-value"]["Value"].values[0]) < (1 - CONFIDENCE_LEVEL):
    SIGNIFICANCE = "significant"
else:
    SIGNIFICANCE = "insignificant"

In [48]:
# Report Management
CAPTION = f"""
The result of the second statistical test is as follows:
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)
REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_STAT_TEST_RESULT_INTRO_2"
)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=TEST_RESULT_2_DF.to_markdown(index=False),
    TYPE="table",
    HEADING="normal",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_STAT_TEST_RESULT_2"
)

CAPTION2 = f"""
With the p-value {TEST_RESULT_2_DF.loc[TEST_RESULT_2_DF["Metric"] == "p-value"]["Value"].values[0]} < {round(1 - CONFIDENCE_LEVEL,2)}, it is discovered that there is a statistically {SIGNIFICANCE} difference on average spending between weekends and weekdays. Hence, {TEST_RESULT_2_DF.loc[TEST_RESULT_2_DF["Metric"] == "Conclusion"]["Value"].values[0]} at {CONFIDENCE_LEVEL * 100}% confidence level.
"""

CAPTION2_WRAPPED = textwrap.fill(CAPTION2, width=130)
print(CAPTION2_WRAPPED)
REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION2_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_STAT_TEST_RESULT_CAPTION_2"
)

 The result of the second statistical test is as follows:
 With the p-value 0.00 < 0.01, it is discovered that there is a statistically significant difference on average spending between
weekends and weekdays. Hence, Reject $H_0$ (Significant) at 99.0% confidence level.

<hr>

<h2>Geospatial Visualisation</h2>
<p>Where do most transactions happen?</p>
<p> --> To visualise where most transactions take place through Scatter Map </p>

In [49]:
# Report Management
SUBSECTION_TITLE = "Geospatial Visualisation"
SUBSECTION_CAPTION = "To visualise the geographical distribution of the data"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_GEOSPATIAL"
)

✅ Registered component: BEHAVIOURAL_PATTERNS_GEOSPATIAL with Title Geospatial Visualisation

In [50]:
# Map District to Coordinates
EXPENSES_WITH_COORDINATES = MAP_STATION_COORDINATES(
    EXPENSES, 
    DISTRICT_COL="District", 
    COORDS_PATH="../DATA/LOOKUP/MRT_STATION_COORDINATES_SG.csv"
)
EXPENSES_WITH_COORDINATES.head()

✅ Matched 3406 out of 3667 records (92.9%)

,Date,Year,ISO Year,Month,Month Label,Week,Week Label,Day,Category,Item,...,District,Income/Expenses,Amount,Formatted Date,Outlier,Day Type,Station,Latitude,Longitude,Coordinates Available
0,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Telephone,Top Up Singtel Card,...,Clementi,Expenses,10.0,28/05/2019,False,Weekday,Clementi,1.3151,103.7654,True
1,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,...,Blank,Expenses,15.3,28/05/2019,False,Weekday,NaN,NaN,NaN,False
2,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Drinks,Bubble Tea,...,Orchard,Expenses,1.8,28/05/2019,False,Weekday,Orchard,1.3048,103.8318,True
3,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,...,Blank,Expenses,32.0,28/05/2019,False,Weekday,NaN,NaN,NaN,False
4,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Food,Korean BBQ,...,Rochor,Expenses,15.0,28/05/2019,False,Weekday,Rochor,1.3036,103.8527,True

In [51]:
# Location Aggregation
LOCATION_AGG = EXPENSES_WITH_COORDINATES.groupby("District").agg({
    "Amount": ["sum", "mean", "count"]
}).reset_index().round(2)

LOCATION_AGG.columns = ["District", "Total Amount", "Average Amount", "Transaction Count"]
LOCATION_AGG.to_csv("../DATA/TEMP/LOCATION_AGG.csv")
LOCATION_AGG.head()

       District  Total Amount  Average Amount  Transaction Count
0      Bayfront         218.4           12.85                 17
1  Beauty World         173.5           12.39                 14
2         Bedok         212.1           14.14                 15
3        Bishan           8.0            8.00                  1
4         Blank        6510.4           25.04                260

In [52]:
# District Mapping to Coordinates (Latitude & Longitude)
LOCATION_AGG_MAPPED = MAP_STATION_COORDINATES(
    LOCATION_AGG, 
    DISTRICT_COL="District", 
    COORDS_PATH="../DATA/LOOKUP/MRT_STATION_COORDINATES_SG.csv"
)
LOCATION_AGG_MAPPED.head()

✅ Matched 57 out of 59 records (96.6%)

,District,Total Amount,Average Amount,Transaction Count,Station,Latitude,Longitude,Coordinates Available
0,Bayfront,218.4,12.85,17,Bayfront,1.2813,103.8590,True
1,Beauty World,173.5,12.39,14,Beauty World,1.3417,103.7760,True
2,Bedok,212.1,14.14,15,Bedok,1.3242,103.9303,True
3,Bishan,8.0,8.00,1,Bishan,1.3508,103.8485,True
4,Blank,6510.4,25.04,260,NaN,NaN,NaN,False

<p>
Due to high numbers of transaction on several districts, it is better to apply Log Transformation towards the Transaction Count column to ensure good visibility on the Geospatial Visualisation.

The Log Transformation to be applied is the following: log(1 + x) in order to avoid log(0)

</p>

In [53]:
# Log Transformation on the Transaction Count Column
LOCATION_AGG_MAPPED["Log Transaction Count"] = round(np.log1p(LOCATION_AGG_MAPPED["Transaction Count"]), 3)
LOCATION_AGG_MAPPED.head()

,District,Total Amount,Average Amount,Transaction Count,Station,Latitude,Longitude,Coordinates Available,Log Transaction Count
0,Bayfront,218.4,12.85,17,Bayfront,1.2813,103.8590,True,2.890
1,Beauty World,173.5,12.39,14,Beauty World,1.3417,103.7760,True,2.708
2,Bedok,212.1,14.14,15,Bedok,1.3242,103.9303,True,2.773
3,Bishan,8.0,8.00,1,Bishan,1.3508,103.8485,True,0.693
4,Blank,6510.4,25.04,260,NaN,NaN,NaN,False,5.565

In [54]:
# Geospatial Heatmap
fig = px.scatter_map(
    LOCATION_AGG_MAPPED, 
    lat="Latitude", 
    lon="Longitude", 
    size="Log Transaction Count",
    color="Average Amount",
    hover_name="District",
    color_continuous_scale="Picnic",
    custom_data=["District", "Total Amount", "Average Amount", "Transaction Count"],
    template="plotly_dark",
    size_max=50,
    zoom=10,
    map_style="carto-darkmatter",
    center={"lat": 1.3521, "lon": 103.8198}
)

fig.update_traces(
    hovertemplate="<br>".join([
        "District: %{customdata[0]}",
        "Total Amount: S$%{customdata[1]}",
        "Transaction Frequency: %{customdata[3]}",
        "Average Amount: S$%{customdata[2]}"
    ]),
    # textposition="outside",
    texttemplate="S$%{text}"
)

fig.update_layout(
    height=600,
    # width=800,
    title="Spending Heatmap by Region"
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
Each point represents a region of transaction activity. Size corresponds to the number of transactions (log scale), where larger points correspond to areas with more frequent transactions. Meanwhile, the average spending per transaction is represented by the blue-red colour scale with blue being the lowest average spending and red being the highest.
"""
PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="SPENDING_HEATMAP_BY_REGION.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Each point represents a region of transaction activity. Size corresponds to the number of transactions (log scale), where larger
points correspond to areas with more frequent transactions. Meanwhile, the average spending per transaction is represented by the
blue-red colour scale with blue being the lowest average spending and red being the highest.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\SPENDING_HEATMAP_BY_REGION.png
✅ Registered component: SPENDING_HEATMAP_BY_REGION.png with Title Spending Heatmap by Region

In [55]:
# Top N Transaction Locations
TOP_N = 2
TOP_N_TRANSACTION_LOCATION = LOCATION_AGG_MAPPED[LOCATION_AGG_MAPPED["District"] != "Blank"].sort_values("Log Transaction Count", ascending=False).head(TOP_N)["District"].tolist()
TOP_N_TRANSACTION_LOCATION

['Clementi', 'Tanjong Pagar']

In [56]:
# Top N Average Amount Locations but Bottom N Transaction Locations
TOP_N_AVG_AMOUNT_LOCATION = LOCATION_AGG_MAPPED[LOCATION_AGG_MAPPED["District"] != "Blank"].sort_values(["Average Amount", "Transaction Count"], ascending=[False, True]).head(TOP_N)["District"].tolist()
TOP_N_AVG_AMOUNT_LOCATION

['Jalan Besar', 'Boon Keng']

In [57]:
# Report Management
CAPTION = f"""
The Geospatial Heatmap displays various distinct zones of highly-frequent low-cost transactions (e.g. {TOP_N_TRANSACTION_LOCATION[0]} and {TOP_N_TRANSACTION_LOCATION[1]}), likely reflecting habitual daily spending patterns around home, school, and/or work.
"""
CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_GEOSPATIAL_BODY_1"
)

print("\n--------------------------------\n")

CAPTION2 = f"""
On the contrary, areas such as {TOP_N_AVG_AMOUNT_LOCATION[0]} and {TOP_N_AVG_AMOUNT_LOCATION[1]} show much higher average spending per visit despite of minimum visits, representing discretionary purchases.
"""
CAPTION2_WRAPPED = textwrap.fill(CAPTION2, width=130)
print(CAPTION2_WRAPPED)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION2_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_GEOSPATIAL_BODY_2"
)

print("\n--------------------------------\n")

CAPTION3 = f"""
Such contrast underlines a duality of spending behaviours where on the functional zones, there is a habitual spending concentration with occasional higher consumption on other districts.
"""
CAPTION3_WRAPPED = textwrap.fill(CAPTION3, width=130)
print(CAPTION3_WRAPPED)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION3_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_GEOSPATIAL_BODY_3"
)

 The Geospatial Heatmap displays various distinct zones of highly-frequent low-cost transactions (e.g. Clementi and Tanjong
Pagar), likely reflecting habitual daily spending patterns around home, school, and/or work.

--------------------------------

 On the contrary, areas such as Jalan Besar and Boon Keng show much higher average spending per visit despite of minimum visits,
representing discretionary purchases.

--------------------------------

 Such contrast underlines a duality of spending behaviours where on the functional zones, there is a habitual spending
concentration with occasional higher consumption on other districts.

<p>
The Top 5 Districts with Highest Consumption:
</p>

In [58]:
LOCATION_AGG_MAPPED.sort_values("Average Amount", ascending=False).head()

,District,Total Amount,Average Amount,Transaction Count,Station,Latitude,Longitude,Coordinates Available,Log Transaction Count
28,Jalan Besar,51.0,51.00,1,Jalan Besar,1.3057,103.8553,True,0.693
5,Boon Keng,40.0,40.00,1,Boon Keng,1.3156,103.8732,True,0.693
39,Outram Park,158.1,39.52,4,Outram Park,1.2800,103.8390,True,1.609
52,Tiong Bahru,39.3,39.30,1,Tiong Bahru,1.2857,103.8269,True,0.693
26,Hillview,60.5,30.25,2,Hillview,1.3622,103.7671,True,1.099

<hr>

<h2>Volume vs Value Analysis</h2>
<p>What is the comparison between how much is spent (i.e. value) and how often is the spending (volume)?</p>
<p> --> To compare districts where spending is frequent vs expensive to support behavioural insights</p>

In [59]:
# Report Management
SUBSECTION_TITLE = "Volume vs Value Analysis"
SUBSECTION_CAPTION = "To compare districts where spending is frequent vs expensive to support behavioural insights"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_VOLUME_VALUE"
)

✅ Registered component: BEHAVIOURAL_PATTERNS_VOLUME_VALUE with Title Volume vs Value Analysis

In [60]:
# Filter Out Districts with Less Than 3 Transactions
LOCATION_AGG = LOCATION_AGG[LOCATION_AGG["Transaction Count"] >= 4]

In [61]:
# Min-Max Scaling to Normalize Total Amount & Transaction Count
scaler = MinMaxScaler()
LOCATION_AGG[["Total Amount Scaled", "Average Amount Scaled", "Transaction Count Scaled"]] = scaler.fit_transform(
    LOCATION_AGG[["Total Amount", "Average Amount", "Transaction Count"]]
)
LOCATION_AGG.head()

,District,Total Amount,Average Amount,Transaction Count,Total Amount Scaled,Average Amount Scaled,Transaction Count Scaled
0,Bayfront,218.4,12.85,17,0.014040,0.254195,0.006616
1,Beauty World,173.5,12.39,14,0.010902,0.241331,0.005089
2,Bedok,212.1,14.14,15,0.013600,0.290268,0.005598
4,Blank,6510.4,25.04,260,0.453754,0.595078,0.130280
6,Boon Lay,102.2,11.36,9,0.005919,0.212528,0.002545

In [62]:
# Set Minimum Bar Height to Avoid Empty Bar
MIN_BAR_HEIGHT = 0.0001
LOCATION_AGG[["Total Amount Scaled", "Average Amount Scaled", "Transaction Count Scaled"]] = LOCATION_AGG[["Total Amount Scaled", "Average Amount Scaled", "Transaction Count Scaled"]].replace(0, MIN_BAR_HEIGHT)
LOCATION_AGG.head()

,District,Total Amount,Average Amount,Transaction Count,Total Amount Scaled,Average Amount Scaled,Transaction Count Scaled
0,Bayfront,218.4,12.85,17,0.014040,0.254195,0.006616
1,Beauty World,173.5,12.39,14,0.010902,0.241331,0.005089
2,Bedok,212.1,14.14,15,0.013600,0.290268,0.005598
4,Blank,6510.4,25.04,260,0.453754,0.595078,0.130280
6,Boon Lay,102.2,11.36,9,0.005919,0.212528,0.002545

In [63]:
fig_layout = go.Layout(
    autosize=True,
    width=1000,
    height=700,
)

fig = go.Figure(layout=fig_layout)

# Deactivate Normalised Data on Hover and Show Raw Data Instead
hover_data = {
    "Transaction Count Scaled": False,
    "Total Amount Scaled": False,
    "Average Amount Scaled": False,
    "Transaction Count": True,
    "Total Amount": True,
    "Average Amount": True
}

# Bar Chart
BAR_CHART_LIST = [
    ["Total Amount", "Total Amount Scaled", "#8FD9FB"], 
    ["Transaction Count", "Transaction Count Scaled", "#FF6F61"], 
    ["Average Amount", "Average Amount Scaled", "#A8DCAB"]
]

for BAR_CHART in BAR_CHART_LIST:
    fig.add_trace(go.Bar(
        x=LOCATION_AGG["District"],
        y=LOCATION_AGG[BAR_CHART[1]],
        name=BAR_CHART[0],
        text=LOCATION_AGG[BAR_CHART[0]],
        hovertemplate=f"{BAR_CHART[0]}: S$%{{text}}<br>District: %{{x}}",
        textposition="none",
        marker_color=BAR_CHART[2]
    ))

fig.update_layout(
    barmode='group',
    height=800,
    xaxis_title="District",
    yaxis_title="Amount",
    title="Volume vs. Value by District",
    template="plotly_dark",
    legend_title_text='Metric Type',
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    ),
    updatemenus=[
        dict(
            type="buttons",
            direction="right",
            showactive=False,
            active=-1,
            buttons=[
                dict(
                    label="Hide District Labels",
                    method="relayout",
                    args=[{"xaxis.showticklabels": False}]
                ),
                dict(
                    label="Show District Labels",
                    method="relayout",
                    args=[{"xaxis.showticklabels": True}]
                )
            ],
            x=0.5,
            xanchor="center",
            y=1.15,
            yanchor="top"
        )
    ]
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
The chart above compares all districts by Transaction Count (volume), Total Spending (value), and Average Amount per Transaction (intensity), each normalised between 0 and 1 where 0 represents values close to the Minimum within the column and 1 the Maximum within the column.
"""
PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="VOLUME_VALUE_BY_DISTRICT.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The chart above compares all districts by Transaction Count (volume), Total Spending (value), and Average Amount per Transaction
(intensity), each normalised between 0 and 1 where 0 represents values close to the Minimum within the column and 1 the Maximum
within the column.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\VOLUME_VALUE_BY_DISTRICT.png
✅ Registered component: VOLUME_VALUE_BY_DISTRICT.png with Title Volume vs. Value by District

In [64]:
# Topmost Total Amount and Transaction Location
TOP_N = 1
TOP_N_TRANSACTION_LOCATION = LOCATION_AGG[LOCATION_AGG["District"] != "Blank"].sort_values(["Total Amount Scaled", "Transaction Count Scaled"], ascending=False).head(TOP_N)
TOP_N_TRANSACTION_LOCATION["District"].to_list()[0]

'Clementi'

In [65]:
# Topmost Average Amount but Bottommost Transaction Location
TOP_N_AVG_AMOUNT_LOCATION = LOCATION_AGG[LOCATION_AGG["District"] != "Blank"].sort_values(["Average Amount Scaled", "Transaction Count Scaled"], ascending=[False, True]).head(TOP_N)
TOP_N_AVG_AMOUNT_LOCATION

,District,Total Amount,Average Amount,Transaction Count,Total Amount Scaled,Average Amount Scaled,Transaction Count Scaled
39,Outram Park,158.1,39.52,4,0.009826,1.0,0.0001

In [66]:
# Moderate Locations
TARGET = 0.5
LOCATION_AGG = LOCATION_AGG[LOCATION_AGG["District"] != "Blank"]
LOCATION_AGG["Distance To Moderate"] = np.sqrt(
    (LOCATION_AGG["Total Amount Scaled"] - TARGET) ** 2 +
    (LOCATION_AGG["Average Amount Scaled"] - TARGET) ** 2 +
    (LOCATION_AGG["Transaction Count Scaled"] - TARGET) ** 2
)
MODERATE_LOCATION_LIST = LOCATION_AGG.sort_values("Distance To Moderate", ascending=True).head(2)["District"].to_list()
MODERATE_LOCATION_LIST

['Tanjong Pagar', 'Jurong East']

In [67]:
# Report Management
CAPTION = f"""
{TOP_N_TRANSACTION_LOCATION["District"].to_list()[0]} shows the highest normalized Transaction Volume and Total Spending, indicating it is by far the most frequently visited location, likely reflecting a habitual area such as a school or home base. On the other hand, its Average Amount per Transaction is low, suggesting small, routine purchases.
"""
CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_VOLUME_VALUE_BODY_1"
)

print("\n--------------------------------\n")

CAPTION2 = f"""
On the contrary, {TOP_N_AVG_AMOUNT_LOCATION["District"].to_list()[0]} has a low number of transactions, but the highest average spending per visit, suggesting it is used for rare but expensive purchases - possibly special dining, shopping, or events.
"""
CAPTION2_WRAPPED = textwrap.fill(CAPTION2, width=130)
print(CAPTION2_WRAPPED)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION2_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_VOLUME_VALUE_BODY_2"
)

print("\n--------------------------------\n")

CAPTION3 = f"""
Mid-tier districts like {MODERATE_LOCATION_LIST[0]} and {MODERATE_LOCATION_LIST[1]} show moderate activity across all metrics, suggesting balanced use cases - both frequent and moderately costly.
"""
CAPTION3_WRAPPED = textwrap.fill(CAPTION3, width=130)
print(CAPTION3_WRAPPED)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION3_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_VOLUME_VALUE_BODY_3"
)

print("\n--------------------------------\n")

CAPTION4 = f"""
Normalization provides better comparison for visualisation, however, it is worth noting that it masks absolute differences - {TOP_N_TRANSACTION_LOCATION["District"].to_list()[0]}'s transaction count could be 10x higher than others, even if shown as only slightly above in the chart.
"""
CAPTION4_WRAPPED = textwrap.fill(CAPTION4, width=130)
print(CAPTION4_WRAPPED)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION4_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="BEHAVIOURAL_PATTERNS_VOLUME_VALUE_BODY_4"
)

 Clementi shows the highest normalized Transaction Volume and Total Spending, indicating it is by far the most frequently visited
location, likely reflecting a habitual area such as a school or home base. On the other hand, its Average Amount per Transaction
is low, suggesting small, routine purchases.

--------------------------------

 On the contrary, Outram Park has a low number of transactions, but the highest average spending per visit, suggesting it is used
for rare but expensive purchases - possibly special dining, shopping, or events.

--------------------------------

 Mid-tier districts like Tanjong Pagar and Jurong East show moderate activity across all metrics, suggesting balanced use cases -
both frequent and moderately costly.

--------------------------------

 Normalization provides better comparison for visualisation, however, it is worth noting that it masks absolute differences -
Clementi's transaction count could be 10x higher than others, even if shown as only slightly above in the chart.

<hr>
<hr>

<h1>Temporal Trends</h1>
<p>How the behaviour changes over time</p>

In [68]:
# Report Management
SECTION_TITLE = "Temporal Trends"
SECTION_CAPTION = "How the behaviour changes over time"
REGISTER_REPORT_COMPONENT(
    TITLE=SECTION_TITLE,
    CONTENT=SECTION_CAPTION,
    TYPE="text",
    HEADING="h2",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="TEMPORAL_TRENDS"
)

✅ Registered component: TEMPORAL_TRENDS with Title Temporal Trends

<h2>Bar Chart for Monthly Spend</h2>
<p>What is the monthly spending trend?</p>
<p> --> To show the seasonality of the spending on the monthly bucket</p>

In [69]:
# Report Management
SUBSECTION_TITLE = "Monthly Spend"
SUBSECTION_CAPTION = "To show the seasonality of the spending on the monthly bucket"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="TEMPORAL_TRENDS_MONTHLY_SPEND"
)

✅ Registered component: TEMPORAL_TRENDS_MONTHLY_SPEND with Title Monthly Spend

In [70]:
# Year-Month Grouping
EXPENSES["Year Month"] = EXPENSES["Date"].dt.strftime('%Y-%m')
EXPENSES.head()

,Date,Year,ISO Year,Month,Month Label,Week,Week Label,Day,Category,Item,Vendor,Vendor Location,District,Income/Expenses,Amount,Formatted Date,Outlier,Day Type,Year Month
0,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Telephone,Top Up Singtel Card,7-Eleven,Blank,Clementi,Expenses,10.0,28/05/2019,False,Weekday,2019-05
1,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,15.3,28/05/2019,False,Weekday,2019-05
2,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Drinks,Bubble Tea,Koi,Takashimaya,Orchard,Expenses,1.8,28/05/2019,False,Weekday,2019-05
3,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,32.0,28/05/2019,False,Weekday,2019-05
4,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Food,Korean BBQ,I Am Kim,Blank,Rochor,Expenses,15.0,28/05/2019,False,Weekday,2019-05

In [71]:
# Temporal Aggregation on Year-Month
EXPENSES_MONTHLY = TEMPORAL_AGGREGATION(EXPENSES, "Year Month", "Amount")
EXPENSES_MONTHLY.head()

  Year Month  TOTAL_AMOUNT  TRANSACTION_FREQUENCY  AVERAGE_AMOUNT
0    2018-10         87.35                     11            7.94
1    2018-11        371.45                     81            4.59
2    2018-12        538.80                     84            6.41
3    2019-01        488.40                     80            6.10
4    2019-02        439.20                     68            6.46

In [72]:
# Year & Month Labelling
EXPENSES_MONTHLY[["Year", "Month"]] = EXPENSES_MONTHLY["Year Month"].str.split("-", expand=True)
EXPENSES_MONTHLY['Month Label'] = EXPENSES_MONTHLY['Month'].astype(int).replace(dict(enumerate(calendar.month_name)))
EXPENSES_MONTHLY.head()

,Year Month,TOTAL_AMOUNT,TRANSACTION_FREQUENCY,AVERAGE_AMOUNT,Year,Month,Month Label
0,2018-10,87.35,11,7.94,2018,10,October
1,2018-11,371.45,81,4.59,2018,11,November
2,2018-12,538.80,84,6.41,2018,12,December
3,2019-01,488.40,80,6.10,2019,01,January
4,2019-02,439.20,68,6.46,2019,02,February

In [73]:
# Month Grouping with Year Being Sorted
EXPENSES_MONTHLY_BY_YEAR = EXPENSES_MONTHLY.groupby(["Year", "Month", "Month Label"]).agg({
    "TOTAL_AMOUNT": "sum",
    "TRANSACTION_FREQUENCY": "sum",
    "AVERAGE_AMOUNT": "mean"
}).reset_index()
EXPENSES_MONTHLY_BY_YEAR.head()

   Year Month Month Label  TOTAL_AMOUNT  TRANSACTION_FREQUENCY  AVERAGE_AMOUNT
0  2018    10     October         87.35                     11            7.94
1  2018    11    November        371.45                     81            4.59
2  2018    12    December        538.80                     84            6.41
3  2019    01     January        488.40                     80            6.10
4  2019    02    February        439.20                     68            6.46

In [74]:
# Stacked Monthly Spending Pattern
fig = px.bar(
    EXPENSES_MONTHLY_BY_YEAR,
    x="Month Label",
    y="TOTAL_AMOUNT",
    color="Year",
    title="Monthly Spending Pattern (Stacked by Year)",
    labels={
        "TOTAL_AMOUNT": "Total Spend",
        "Month Label": "Month"
    },
    category_orders={"Month Label": [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"
    ]},
    template="plotly_dark",
    color_discrete_sequence=px.colors.qualitative.Set3,
    custom_data=["Year", "Month"]
)

fig.update_traces(
    hovertemplate="<br>".join([
        "Year: %{customdata[0]}",
        "Month: %{x}",
        "Total Amount: S$%{y:.2f}"
    ])
)


fig.update_layout(
    barmode="stack",
    xaxis_title="Month",
    yaxis_title="Total Spending",
    legend_title_text="Year"
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
The graph shows the monthly spending trend for each year. The stacked bars indicate the total spending amount per month for each year.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="MONTHLY_SPENDING_PATTERN_STACKED.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The graph shows the monthly spending trend for each year. The stacked bars indicate the total spending amount per month for each
year.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\MONTHLY_SPENDING_PATTERN_STACKED.png
✅ Registered component: MONTHLY_SPENDING_PATTERN_STACKED.png with Title Monthly Spending Pattern (Stacked by Year)

In [75]:
fig = px.line(
    EXPENSES_MONTHLY,
    x="Year Month",
    y="TOTAL_AMOUNT",
    title="Monthly Spending Trend",
    markers=True,
    labels={"TOTAL_AMOUNT": "Total Spend", "Year Month": "Time Period"},
    template="plotly_dark",
    line_shape="linear"
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
A line chart displays the monthly spending trend throughout the data horizon to identify the overall spending trend. 
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="MONTHLY_SPENDING_PATTERN_LINE.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 A line chart displays the monthly spending trend throughout the data horizon to identify the overall spending trend.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\MONTHLY_SPENDING_PATTERN_LINE.png
✅ Registered component: MONTHLY_SPENDING_PATTERN_LINE.png with Title Monthly Spending Trend

In [76]:
# Report Management
CAPTION = f"""
Note: There is a visible drop in spending between June and August 2019. This reflects a period during which data was not recorded, not a behavioral change. Interpret trends around this period with caution.

The following periods are when the data was not recorded completely and hence, no data point: June 2019 & July 2019. Due to this, these periods need to be marked in the subsequent steps.
"""
CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="TEMPORAL_TRENDS_MONTHLY_SPEND_TREND_BODY_1"
)

 Note: There is a visible drop in spending between June and August 2019. This reflects a period during which data was not
recorded, not a behavioral change. Interpret trends around this period with caution.  The following periods are when the data was
not recorded completely and hence, no data point: June 2019 & July 2019. Due to this, these periods need to be marked in the
subsequent steps.

In [77]:
# Mark Months with Less Than 30 Transactions Invalid
EXPENSES_MONTHLY_BY_YEAR["Valid"] = True 
EXPENSES_MONTHLY_BY_YEAR.loc[
    ((EXPENSES_MONTHLY_BY_YEAR["TRANSACTION_FREQUENCY"] <= 30)),
    "Valid"
] = False
EXPENSES_MONTHLY_BY_YEAR.head()

,Year,Month,Month Label,TOTAL_AMOUNT,TRANSACTION_FREQUENCY,AVERAGE_AMOUNT,Valid
0,2018,10,October,87.35,11,7.94,False
1,2018,11,November,371.45,81,4.59,True
2,2018,12,December,538.80,84,6.41,True
3,2019,01,January,488.40,80,6.10,True
4,2019,02,February,439.20,68,6.46,True

In [78]:
# Spending Behaviour Annotated for No Record
fig = px.line(
    EXPENSES_MONTHLY,
    x="Year Month",
    y="TOTAL_AMOUNT",
    title="Monthly Spending Trend",
    markers=True,
    labels={"TOTAL_AMOUNT": "Total Spend", "Year Month": "Time Period"},
    template="plotly_dark",
    line_shape="linear"
)

fig.add_vrect(
    x0="2019-06-01", 
    x1="2019-07-31",
    fillcolor="white", 
    opacity=0.3,
    layer="below", 
    line_width=0,
    annotation_text="No Record",
    annotation_position="top left", 
    annotation_textangle = 90
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
The specified periods where the data is missing are highlighted in the graph using gray shading and annotated as "No Record". 
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="MONTHLY_SPENDING_PATTERN_LINE_ANNOTATED.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The specified periods where the data is missing are highlighted in the graph using gray shading and annotated as "No Record".

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\MONTHLY_SPENDING_PATTERN_LINE_ANNOTATED.png
✅ Registered component: MONTHLY_SPENDING_PATTERN_LINE_ANNOTATED.png with Title Monthly Spending Trend

In [79]:
# MA 3 -> Regular Smoothing (Covers 1 Quarter)
EXPENSES_MONTHLY["MA_3_FILLED"] = EXPENSES_MONTHLY["TOTAL_AMOUNT"].interpolate()
EXPENSES_MONTHLY["MA_3"] = EXPENSES_MONTHLY["MA_3_FILLED"].rolling(3, center=True).mean().round(2)

# MA 6 -> Stronger Smoothing (Covers Half Year)
EXPENSES_MONTHLY["MA_6_FILLED"] = EXPENSES_MONTHLY["TOTAL_AMOUNT"].interpolate()
EXPENSES_MONTHLY["MA_6"] = EXPENSES_MONTHLY["MA_6_FILLED"].rolling(6, center=True).mean().round(2)

# MA 12 -> Annual Trend (Covers 1 Year)
EXPENSES_MONTHLY["MA_12_FILLED"] = EXPENSES_MONTHLY["TOTAL_AMOUNT"].interpolate()
EXPENSES_MONTHLY["MA_12"] = EXPENSES_MONTHLY["MA_12_FILLED"].rolling(12, center=True).mean().round(2)

EXPENSES_MONTHLY.head()

,Year Month,TOTAL_AMOUNT,TRANSACTION_FREQUENCY,AVERAGE_AMOUNT,Year,Month,Month Label,MA_3_FILLED,MA_3,MA_6_FILLED,MA_6,MA_12_FILLED,MA_12
0,2018-10,87.35,11,7.94,2018,10,October,87.35,NaN,87.35,NaN,87.35,NaN
1,2018-11,371.45,81,4.59,2018,11,November,371.45,332.53,371.45,NaN,371.45,NaN
2,2018-12,538.80,84,6.41,2018,12,December,538.80,466.22,538.80,NaN,538.80,NaN
3,2019-01,488.40,80,6.10,2019,01,January,488.40,488.80,488.40,410.78,488.40,NaN
4,2019-02,439.20,68,6.46,2019,02,February,439.20,489.03,439.20,473.48,439.20,NaN

In [80]:
# Moving Average Visualisation
fig_layout = go.Layout(
    autosize=True,
    width=1000,
    height=700,
)

fig = go.Figure(layout=fig_layout)

# Original Line
fig.add_trace(go.Scatter(
    x=EXPENSES_MONTHLY["Year Month"],
    y=EXPENSES_MONTHLY["TOTAL_AMOUNT"],
    name="Monthly Spend",
    mode="lines+markers",
    line_color="#B8A9A9"
))

# Bar Chart
fig.add_trace(go.Bar(
    x=EXPENSES_MONTHLY["Year Month"],
    y=EXPENSES_MONTHLY["TOTAL_AMOUNT"],
    name="Monthly Spend",
    marker_color="#96717D"
))

# Moving Average
MA_LIST = [
    ["MA_3", "3-Month Moving Average", "#8FB8D3"], 
    ["MA_6", "6-Month Moving Average", "#388E89"], 
    ["MA_12", "12-Month Moving Average", "#8b80d0"]
]

for MA in MA_LIST:
    fig.add_trace(go.Scatter(
        x=EXPENSES_MONTHLY["Year Month"],
        y=EXPENSES_MONTHLY[MA[0]],
        name=MA[1],
        mode="lines",
        line=dict(dash="dash", width=3, color=MA[2])
    ))

fig.add_vrect(
    x0="2019-06-01", 
    x1="2019-07-15",
    fillcolor="white", 
    opacity=0.3,
    layer="below", 
    line_width=0,
    annotation_text="No Record",
    annotation_position="top left", 
    annotation_textangle = 90
)

fig.update_layout(
    title="Monthly Spending Trend with Moving Average",
    xaxis_title="Time Period",
    yaxis_title="Total Spending",
    template="plotly_dark",
    height=800,
    legend_title_text='Metric Type',
    legend=dict(
        orientation="h",
        yanchor="top",
        xanchor="right",
        x=1
    )
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
The holistic monthly spending trend is shown in the graph, with the original data points and a 3-month, 6-month and 12-month moving average. 
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="MONTHLY_SPENDING_PATTERN_MOVING_AVERAGE.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The holistic monthly spending trend is shown in the graph, with the original data points and a 3-month, 6-month and 12-month
moving average.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\MONTHLY_SPENDING_PATTERN_MOVING_AVERAGE.png
✅ Registered component: MONTHLY_SPENDING_PATTERN_MOVING_AVERAGE.png with Title Monthly Spending Trend with Moving Average

In [81]:
# Obtaining Seasonality Index
SEASONALITY_INDEX = EXPENSES_MONTHLY.groupby(["Month", "Month Label"]).agg({
    "TOTAL_AMOUNT": "mean",
}).reset_index()
SEASONALITY_INDEX["Seasonality Index"] = (SEASONALITY_INDEX["TOTAL_AMOUNT"] / SEASONALITY_INDEX["TOTAL_AMOUNT"].mean()) - 1
SEASONALITY_INDEX["Seasonality Status"] = SEASONALITY_INDEX["Seasonality Index"].apply(lambda x: "Below Average" if x < 0 else "Above Average")
SEASONALITY_INDEX

   Month Month Label  TOTAL_AMOUNT  Seasonality Index Seasonality Status
0     01     January    588.080000           0.015103      Above Average
1     02    February    609.840000           0.052664      Above Average
2     03       March    638.760000           0.102583      Above Average
3     04       April    578.500000          -0.001433      Below Average
4     05         May    533.220000          -0.079593      Below Average
5     06        June    566.225000          -0.022622      Below Average
6     07        July    598.800000           0.033607      Above Average
7     08      August    565.500000          -0.023873      Below Average
8     09   September    599.840000           0.035402      Above Average
9     10     October    549.058333          -0.052254      Below Average
10    11    November    555.575000          -0.041005      Below Average
11    12    December    568.566667          -0.018580      Below Average

In [82]:
# Visualisation on Seasonality Index

fig = px.bar(
    SEASONALITY_INDEX,
    x="Month Label",
    y="Seasonality Index",
    color="Seasonality Status",
    title="Seasonality Index (Scaled from -1 to 1)",
    labels={
        "Seasonality Index": "Seasonality Index",
        "Month Label": "Month"
    },
    category_orders={"Month Label": [
        "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"
    ]},
    template="plotly_dark",
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig.update_layout(
    legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1
        )
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
To better visualise the Seasonality Index, a Bar Chart scaled from -1 to 1 is used. From the graph, it is discovered that the range of Seasonality Index is not beyond the scale between -0.1 to 0.1. Therefore, spending is not strongly seasonal; variability is likely driven by events, not months.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="SEASONALITY_INDEX.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 To better visualise the Seasonality Index, a Bar Chart scaled from -1 to 1 is used. From the graph, it is discovered that the
range of Seasonality Index is not beyond the scale between -0.1 to 0.1. Therefore, spending is not strongly seasonal; variability
is likely driven by events, not months.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\SEASONALITY_INDEX.png
✅ Registered component: SEASONALITY_INDEX.png with Title Seasonality Index (Scaled from -1 to 1)

<hr>

<h2>Surplus/Deficit Analysis</h2>
<p>What is the net financial health overtime?</p>
<p> --> To analyse the impact of the spending behaviour towards the financial health relative to the income.</p>

<p>
Details regarding the Income Data:

- Income data consists of 2 main source of income: 
    - Real Income (comes from Disposable Income from Budget Planning) 
    - Carry-Over (Category is named as "Last Month's Balance").
- The inclusion of Carry-Over dilutes the actual effect of real income, therefore needs to be annotated/visualised differently.
</p>

In [83]:
# Report Management
SUBSECTION_TITLE = "Surplus/Deficit Analysis"
SUBSECTION_CAPTION = "To analyse the surplus/deficit in the spending pattern"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="TEMPORAL_TRENDS_SURPLUS_DEFICIT"
)

✅ Registered component: TEMPORAL_TRENDS_SURPLUS_DEFICIT with Title Surplus/Deficit Analysis

In [84]:
CASH_FLOW.head()

,Date,Year,ISO Year,Month,Month Label,Week,Week Label,Day,Category,Item,Vendor,Vendor Location,District,Income/Expenses,Amount,Formatted Date,Outlier
0,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Telephone,Top Up Singtel Card,7-Eleven,Blank,Clementi,Expenses,10.0,28/05/2019,False
1,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,15.3,28/05/2019,False
2,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Drinks,Bubble Tea,Koi,Takashimaya,Orchard,Expenses,1.8,28/05/2019,False
3,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,32.0,28/05/2019,False
4,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Food,Korean BBQ,I Am Kim,Blank,Rochor,Expenses,15.0,28/05/2019,False

In [85]:
# Classify Real Income as True, False, or "Expenses"
CASH_FLOW["Real Income"] = CASH_FLOW[CASH_FLOW["Income/Expenses"] == "Income"]["Category"].apply(lambda x: False if (x == "Last Month's Balance") | (x == "Balance from Previous Month") else True)
CASH_FLOW["Real Income"] = CASH_FLOW["Real Income"].fillna("Expenses")

# Retain the Date Format + Generate the Label
CASH_FLOW["Year Month"] = CASH_FLOW["Date"].dt.strftime("%Y-%B")
CASH_FLOW["Year Month"] = pd.to_datetime(CASH_FLOW["Year Month"], format="%Y-%B")
CASH_FLOW["Year Month Label"] = CASH_FLOW["Year Month"].dt.strftime("%B %Y")
CASH_FLOW = CASH_FLOW.sort_values("Date").reset_index(drop=True)

CASH_FLOW.head()

,Date,Year,ISO Year,Month,Month Label,Week,Week Label,Day,Category,Item,Vendor,Vendor Location,District,Income/Expenses,Amount,Formatted Date,Outlier,Real Income,Year Month,Year Month Label
0,2018-10-28,2018,2018,10,October,43,W43,Sunday,Cash Withdrawal,Cash Withdrawal + Current Balance,Blank,Blank,Blank,Income,180.0,28/10/2018,False,True,2018-10-01,October 2018
1,2018-10-28,2018,2018,10,October,43,W43,Sunday,Food,Mixed Rice,Kopitiam,Northpoint Shopping Centre,Yishun,Expenses,4.7,28/10/2018,False,Expenses,2018-10-01,October 2018
2,2018-10-28,2018,2018,10,October,43,W43,Sunday,Fruits,Juice,Boost Juice Bars,Northpoint Shopping Centre,Yishun,Expenses,2.5,28/10/2018,False,Expenses,2018-10-01,October 2018
3,2018-10-29,2018,2018,10,October,44,W44,Monday,Food,Mixed Rice,Food Clique,SIM,Clementi,Expenses,3.6,29/10/2018,False,Expenses,2018-10-01,October 2018
4,2018-10-29,2018,2018,10,October,44,W44,Monday,Food,Spaghetti,Ngee Ann Polytechnic,Blank,Clementi,Expenses,5.0,29/10/2018,False,Expenses,2018-10-01,October 2018

In [86]:
# Monthly Cash Flow
MONTHLY_CASH_FLOW = CASH_FLOW.groupby(["Income/Expenses", "Year Month", "Year Month Label", "Month Label", "Real Income"]).agg({
    "Amount": "sum"
}).reset_index()
MONTHLY_CASH_FLOW.head()

  Income/Expenses Year Month Year Month Label Month Label Real Income  Amount
0        Expenses 2018-10-01     October 2018     October    Expenses   87.35
1        Expenses 2018-11-01    November 2018    November    Expenses  371.45
2        Expenses 2018-12-01    December 2018    December    Expenses  538.80
3        Expenses 2019-01-01     January 2019     January    Expenses  488.40
4        Expenses 2019-02-01    February 2019    February    Expenses  439.20

In [87]:
# Stacked Bar + Group Bar for Surplus/Deficit Analysis
fig_layout = go.Layout(
    autosize=True,
    width=1000,
    height=700,
)

fig = go.Figure(layout=fig_layout)

# List of Bar Components, if base = "base" -> unstacked bar, otherwise, stacked bar
BAR_COMPONENT_LIST = [
    [
        (MONTHLY_CASH_FLOW["Income/Expenses"] == "Income") & (MONTHLY_CASH_FLOW["Real Income"] == False), 
        "Excess Income Carry-over", 
        "base",
        0, 
        "#7FB3D5"
    ],
    [
        (MONTHLY_CASH_FLOW["Income/Expenses"] == "Income") & (MONTHLY_CASH_FLOW["Real Income"] == True), 
        "Real Income", 
        MONTHLY_CASH_FLOW[(MONTHLY_CASH_FLOW["Income/Expenses"] == "Income") & (MONTHLY_CASH_FLOW["Real Income"] == False)]["Amount"],
        0,
        "#ACE1AF"
    ],
    [
        (MONTHLY_CASH_FLOW["Income/Expenses"] == "Expenses"), 
        "Expenses",
        "base",
        1,
        "#FFB7BC"
    ]
]

for BAR in BAR_COMPONENT_LIST:
    fig.add_trace(go.Bar(
        x=MONTHLY_CASH_FLOW["Year Month"],
        y=MONTHLY_CASH_FLOW[BAR[0]]["Amount"],
        name=BAR[1],
        text=MONTHLY_CASH_FLOW["Year Month Label"],
        hovertemplate="%{text}<br>Amount: %{y}",
        textposition="none",
        offsetgroup=BAR[3],
        base=BAR[2],
        marker_color=BAR[4]
    ))

fig.add_vrect(
    x0="2019-05-25", 
    x1="2019-07-15",
    fillcolor="white", 
    opacity=0.3,
    layer="below", 
    line_width=0,
    annotation_text="No Record",
    annotation_position="top left", 
    annotation_textangle = 90
)

fig.update_layout(
    barmode="group",
    title="Monthly Cash Flow: Resources (Income + Carry-over) vs Expenses",
    xaxis_title="Time Period",
    yaxis_title="Amount (S$)",
    template="plotly_dark",
    legend_title_text="Component",
    bargap=0.2,
    height=600,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    )
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
Throughout the horizon of the analysis, the monthly cash flow reflects a consistent surplus each month triggering a growing cumulative excess income indicating a sustainable savings habits.Occasional months reflect extremely low spending are due to the Circuit Breaker imposed during Covid-19 pandemic and therefore, the income along with carry-over can exceed twice as much expenses during those months. Overtime, the spending has been escalating as the cost of living and lifestyle in general have been climbing altogether.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="MONTHLY_CASH_FLOW.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Throughout the horizon of the analysis, the monthly cash flow reflects a consistent surplus each month triggering a growing
cumulative excess income indicating a sustainable savings habits.Occasional months reflect extremely low spending are due to the
Circuit Breaker imposed during Covid-19 pandemic and therefore, the income along with carry-over can exceed twice as much expenses
during those months. Overtime, the spending has been escalating as the cost of living and lifestyle in general have been climbing
altogether.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\MONTHLY_CASH_FLOW.png
✅ Registered component: MONTHLY_CASH_FLOW.png with Title Monthly Cash Flow: Resources (Income + Carry-over) vs Expenses

In [88]:
# Pivot Table for Surplus/Deficit Analysis 

MONTHLY_CASH_FLOW_PIVOT = MONTHLY_CASH_FLOW.pivot_table(
    index=["Year Month", "Year Month Label"],
    columns=["Income/Expenses", "Real Income"],
    values="Amount",
    aggfunc="sum"
).fillna(0).reset_index()
MONTHLY_CASH_FLOW_PIVOT

MONTHLY_CASH_FLOW_PIVOT.columns = ["Year Month", "Year Month Label", "Expenses", "Carry-over", "Real Income"]
MONTHLY_CASH_FLOW_PIVOT = MONTHLY_CASH_FLOW_PIVOT.rename(columns={
    ("Income", True): "Carry-over",
    ("Income", False): "Real Income",
    ("Expenses", "Expenses"): "Expenses"
})
MONTHLY_CASH_FLOW_PIVOT.head()

  Year Month Year Month Label  Expenses  Carry-over  Real Income
0 2018-10-01     October 2018     87.35        0.00        180.0
1 2018-11-01    November 2018    371.45       92.65        400.0
2 2018-12-01    December 2018    538.80      121.20        500.0
3 2019-01-01     January 2019    488.40       82.40        500.0
4 2019-02-01    February 2019    439.20       94.00        500.0

In [89]:
# Cumulative Surplus
MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE = MONTHLY_CASH_FLOW_PIVOT.sort_values("Year Month").copy()
MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE["Carryover"] = 0.0
MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE["Surplus"] = 0.0
MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE["Cumulative Surplus"] = 0.0

for i in range(len(MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE)):
    CARRYOVER = MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE.iloc[i - 1]["Surplus"] if i > 0 else 0.0
    MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE.at[i, "Carryover"] = CARRYOVER
    PREV_CUMULATIVE_SURPLUS = MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE.iloc[i - 1]["Cumulative Surplus"] if i > 0 else 0.0
    
    REAL_INCOME = MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE.at[i, "Real Income"]
    EXPENSES_TOTAL_MONTHLY = MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE.at[i, "Expenses"]
    
    # Ensure these are not NaN
    REAL_INCOME = 0.0 if pd.isna(REAL_INCOME) else REAL_INCOME
    EXPENSES_TOTAL_MONTHLY = 0.0 if pd.isna(EXPENSES_TOTAL_MONTHLY) else EXPENSES_TOTAL_MONTHLY
    
    SURPLUS = REAL_INCOME + CARRYOVER - EXPENSES_TOTAL_MONTHLY
    MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE.at[i, "Surplus"] = SURPLUS
    MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE.at[i, "Cumulative Surplus"] = SURPLUS + PREV_CUMULATIVE_SURPLUS

MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE.head()

,Year Month,Year Month Label,Expenses,Carry-over,Real Income,Carryover,Surplus,Cumulative Surplus
0,2018-10-01,October 2018,87.35,0.00,180.0,0.00,92.65,92.65
1,2018-11-01,November 2018,371.45,92.65,400.0,92.65,121.20,213.85
2,2018-12-01,December 2018,538.80,121.20,500.0,121.20,82.40,296.25
3,2019-01-01,January 2019,488.40,82.40,500.0,82.40,94.00,390.25
4,2019-02-01,February 2019,439.20,94.00,500.0,94.00,154.80,545.05

In [90]:
# Cumulative Surplus Visualisation
fig = px.bar(
    MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE,
    x="Year Month",
    y="Cumulative Surplus",
    template="plotly_dark"
)

fig.add_vrect(
    x0="2019-06-01", 
    x1="2019-07-15",
    fillcolor="white", 
    opacity=0.3,
    layer="below", 
    line_width=0,
    annotation_text="No Record",
    annotation_position="top left", 
    annotation_textangle = 90
)

fig.update_traces(
    hovertemplate="<br>".join([
        "Period: %{x}",
        "Cumulative Amount: S$%{y:.2f}"
    ])
)

fig.update_layout(
    barmode="group",
    title="Cumulative Surplus Analysis",
    xaxis_title="Time Period",
    yaxis_title="Cumulative Surplus (S$)",
    template="plotly_dark",
    legend_title_text="Component",
    yaxis_tickformat=",", 
    bargap=0.2,
    height=600,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    )
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
The graph shows the cumulative surplus analysis for each month. The bars indicate the cumulative surplus amount per month.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="CUMULATIVE_SURPLUS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The graph shows the cumulative surplus analysis for each month. The bars indicate the cumulative surplus amount per month.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\CUMULATIVE_SURPLUS.png
✅ Registered component: CUMULATIVE_SURPLUS.png with Title Cumulative Surplus Analysis

In [91]:
# Generate Complete Data Range and Reindex the Table with Complete Date Range
MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX = MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE.set_index("Year Month").sort_index()

ALL_MONTHS = pd.date_range(
    start=MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX.index.min(), 
    end=MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX.index.max(), 
    freq="MS"
)

MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX = MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX.reindex(ALL_MONTHS)
MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX.head()

,Year Month Label,Expenses,Carry-over,Real Income,Carryover,Surplus,Cumulative Surplus
2018-10-01,October 2018,87.35,0.00,180.0,0.00,92.65,92.65
2018-11-01,November 2018,371.45,92.65,400.0,92.65,121.20,213.85
2018-12-01,December 2018,538.80,121.20,500.0,121.20,82.40,296.25
2019-01-01,January 2019,488.40,82.40,500.0,82.40,94.00,390.25
2019-02-01,February 2019,439.20,94.00,500.0,94.00,154.80,545.05

In [92]:
# Forward-fill only the cumulative surplus and carryover
MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX["Cumulative Surplus"] = MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX["Cumulative Surplus"].ffill()
MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX["Carryover"] = MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX["Carryover"].ffill()

# Fill the rest with 0 or NaN
MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX[["Real Income", "Expenses", "Surplus"]] = MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX[["Real Income", "Expenses", "Surplus"]].fillna(0)

# Restore the Index
MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX = MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX.reset_index().rename(columns={"index": "Year Month"})

# Fill in the Missing Year Month Label
MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX["Year Month"] = pd.to_datetime(MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX["Year Month"])
MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX["Year Month Label"] = MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX["Year Month"].dt.strftime("%B %Y")

# MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX.to_csv("..\DATA\TEMP\MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX.csv", index=False)
MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX.head()

,Year Month,Year Month Label,Expenses,Carry-over,Real Income,Carryover,Surplus,Cumulative Surplus
0,2018-10-01,October 2018,87.35,0.00,180.0,0.00,92.65,92.65
1,2018-11-01,November 2018,371.45,92.65,400.0,92.65,121.20,213.85
2,2018-12-01,December 2018,538.80,121.20,500.0,121.20,82.40,296.25
3,2019-01-01,January 2019,488.40,82.40,500.0,82.40,94.00,390.25
4,2019-02-01,February 2019,439.20,94.00,500.0,94.00,154.80,545.05

In [93]:
# Cumulative Surplus Visualisation
fig = px.bar(
    MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX,
    x="Year Month",
    y="Cumulative Surplus",
    template="plotly_dark"
)

fig.update_traces(
    hovertemplate="<br>".join([
        "Period: %{x}",
        "Cumulative Amount: S$%{y:.2f}"
    ])
)

fig.update_layout(
    barmode="group",
    title="Cumulative Surplus Analysis",
    xaxis_title="Time Period",
    yaxis_title="Cumulative Surplus (S$)",
    template="plotly_dark",
    legend_title_text="Component",
    yaxis_tickformat=",", 
    bargap=0.2,
    height=600,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    )
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
Since both June and July 2019 do not have any data points, these periods are skipped in the table. Logically, these periods should remain flat and consistent with the balance of the previous month since the timeline is continuous and these two months are periods of inactivity with no financial change. According to the Cumulative Surplus Analysis, the final cumulative surplus is S${MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX.iloc[len(MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX) - 1]["Cumulative Surplus"]:.2f} on {MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX.iloc[len(MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX) - 1]["Year Month Label"]}.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="CUMULATIVE_SURPLUS_FULL.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Since both June and July 2019 do not have any data points, these periods are skipped in the table. Logically, these periods
should remain flat and consistent with the balance of the previous month since the timeline is continuous and these two months are
periods of inactivity with no financial change. According to the Cumulative Surplus Analysis, the final cumulative surplus is
S$13560.95 on December 2023.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\CUMULATIVE_SURPLUS_FULL.png
✅ Registered component: CUMULATIVE_SURPLUS_FULL.png with Title Cumulative Surplus Analysis

<hr>
<hr>

<h1>Diagnostic & Comparative Analysis</h1>
<p>Why a certain financial event happens and how it compares</p>

In [94]:
# Report Management
SECTION_TITLE = "Diagnostic & Comparative Analysis"
SECTION_CAPTION = "Analysis to diagnose and compare data according to the financial events"
REGISTER_REPORT_COMPONENT(
    TITLE=SECTION_TITLE,
    CONTENT=SECTION_CAPTION,
    TYPE="text",
    HEADING="h2",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="DIAGNOSTIC_COMPARATIVE_ANALYSIS"
)

✅ Registered component: DIAGNOSTIC_COMPARATIVE_ANALYSIS with Title Diagnostic & Comparative Analysis

<h2>Year-over-Year (YoY) Comparisons</h2>
<p>How does the spending of one year compare against the previous?</p>
<p> --> To analyse the evolution of spending over the years.</p>

In [95]:
# Report Management
SUBSECTION_TITLE = "Year-on-Year (YoY) Comparison"
SUBSECTION_CAPTION = "To analyse the evolution of spending over the years"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="DIAGNOSTIC_COMPARATIVE_ANALYSIS_YOY"
)

✅ Registered component: DIAGNOSTIC_COMPARATIVE_ANALYSIS_YOY with Title Year-on-Year (YoY) Comparison

In [96]:
# YoY Dataframe
YOY_CASH_FLOW = MONTHLY_CASH_FLOW_PIVOT_CUMULATIVE_DATE_INDEX.copy()
YOY_CASH_FLOW["Month"] = YOY_CASH_FLOW["Year Month"].dt.month
YOY_CASH_FLOW["Year"] = YOY_CASH_FLOW["Year Month"].dt.year
YOY_CASH_FLOW.head()

,Year Month,Year Month Label,Expenses,Carry-over,Real Income,Carryover,Surplus,Cumulative Surplus,Month,Year
0,2018-10-01,October 2018,87.35,0.00,180.0,0.00,92.65,92.65,10,2018
1,2018-11-01,November 2018,371.45,92.65,400.0,92.65,121.20,213.85,11,2018
2,2018-12-01,December 2018,538.80,121.20,500.0,121.20,82.40,296.25,12,2018
3,2019-01-01,January 2019,488.40,82.40,500.0,82.40,94.00,390.25,1,2019
4,2019-02-01,February 2019,439.20,94.00,500.0,94.00,154.80,545.05,2,2019

In [97]:
# YoY Pivot Table
YOY_CASH_FLOW_PIVOT = YOY_CASH_FLOW.pivot_table(
    index="Month",
    columns="Year",
    values="Surplus",
    aggfunc="sum"
).sort_index()

YOY_CASH_FLOW_PIVOT = YOY_CASH_FLOW_PIVOT.reset_index()
YOY_CASH_FLOW_PIVOT["Month Label"] = YOY_CASH_FLOW_PIVOT["Month"].apply(lambda MONTH: calendar.month_name[MONTH])

YOY_CASH_FLOW_PIVOT

Year  Month    2018   2019   2020   2021   2022   2023 Month Label
0         1     NaN   94.0  466.0  348.6  282.0  152.0     January
1         2     NaN  154.8  307.4  480.0  256.0  175.2    February
2         3     NaN  115.3  377.4  429.4  255.6  201.9       March
3         4     NaN  251.8  299.1  209.0  377.1  150.1       April
4         5     NaN  154.3  276.1  151.5  346.0  193.1         May
5         6     NaN    0.0  147.0   93.9  256.5  204.4        June
6         7     NaN    0.0  266.1  115.2  201.4  123.9        July
7         8     NaN  123.9  368.6   77.2  163.3  100.4      August
8         9     NaN  256.0  169.7  186.9   88.2  133.4   September
9        10   92.65  294.0  176.6  364.1   77.0   15.5     October
10       11  121.20  324.2  288.5  468.4  137.2   46.9    November
11       12   82.40  343.9  271.8  339.5  245.4  292.0    December

In [98]:
MONTH_WITH_HIGHEST_SURPLUS = YOY_CASH_FLOW.groupby(["Month"]).agg({
    "Surplus": "mean",
}).reset_index().sort_values("Surplus", ascending=False).head(3)
MONTH_WITH_HIGHEST_SURPLUS_TOP_3 = MONTH_WITH_HIGHEST_SURPLUS["Month"].tolist()
MONTH_WITH_HIGHEST_SURPLUS_TOP_3 = [calendar.month_name[i] for i in sorted(MONTH_WITH_HIGHEST_SURPLUS_TOP_3)]
MONTH_WITH_HIGHEST_SURPLUS_TOP_3

['January', 'February', 'March']

In [99]:
MONTH_WITH_LOWEST_SURPLUS = YOY_CASH_FLOW.groupby(["Month"]).agg({
    "Surplus": "mean",
}).reset_index().sort_values("Surplus", ascending=True).head(3)
MONTH_WITH_LOWEST_SURPLUS_TOP_3 = MONTH_WITH_LOWEST_SURPLUS["Month"].tolist()
MONTH_WITH_LOWEST_SURPLUS_TOP_3 = [calendar.month_name[i] for i in sorted(MONTH_WITH_LOWEST_SURPLUS_TOP_3)]
MONTH_WITH_LOWEST_SURPLUS_TOP_3

['June', 'July', 'August']

In [100]:
# YoY Visualisation
fig = px.bar(
    YOY_CASH_FLOW_PIVOT.melt(id_vars=["Month", "Month Label"], var_name="Year", value_name="Surplus"),
    x="Month Label",
    y="Surplus",
    color="Year",
    barmode="group",
    title="Year-over-Year (YoY) Monthly Surplus Comparison",
    color_discrete_sequence=px.colors.qualitative.Set3,
    custom_data=["Year", "Month"]
)

fig.update_traces(
    hovertemplate="<br>".join([
        "Year: %{customdata[0]}",
        "Month: %{x}",
        "Surplus: S$%{y:.2f}"
    ])
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Surplus (S$)",
    template="plotly_dark"
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
Strong surpluses generally happen in {", ".join(MONTH_WITH_HIGHEST_SURPLUS_TOP_3)} of each year linked of the low-season holiday activities since these periods are more intensive due to exams and work. Some weaker surpluses of {", ".join(MONTH_WITH_LOWEST_SURPLUS_TOP_3)} are linked to the mid-of-the-year big purchases. The absence of strong month-to-month seasonality suggests that financial behavior is primarily driven by life circumstances or irregular events rather than fixed cycles
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="YOY_SURPLUS_COMPARISON.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Strong surpluses generally happen in January, February, March of each year linked of the low-season holiday activities since
these periods are more intensive due to exams and work. Some weaker surpluses of June, July, August are linked to the mid-of-the-
year big purchases. The absence of strong month-to-month seasonality suggests that financial behavior is primarily driven by life
circumstances or irregular events rather than fixed cycles

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\YOY_SURPLUS_COMPARISON.png
✅ Registered component: YOY_SURPLUS_COMPARISON.png with Title Year-over-Year (YoY) Monthly Surplus Comparison

<hr>

<h2>Trend Break Detection</h2>
<p>When did my spending behavior change?</p>
<p> --> To identify if there is a change of pattern in spending.</p>

In [101]:
# Report Management
SUBSECTION_TITLE = "Trend Break Detection"
SUBSECTION_CAPTION = "To identify if there is a change of pattern in spending"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="DIAGNOSTIC_COMPARATIVE_ANALYSIS_TREND_BREAK_DETECTION"
)

✅ Registered component: DIAGNOSTIC_COMPARATIVE_ANALYSIS_TREND_BREAK_DETECTION with Title Trend Break Detection

In [102]:
EXPENSES_MONTHLY.head()

,Year Month,TOTAL_AMOUNT,TRANSACTION_FREQUENCY,AVERAGE_AMOUNT,Year,Month,Month Label,MA_3_FILLED,MA_3,MA_6_FILLED,MA_6,MA_12_FILLED,MA_12
0,2018-10,87.35,11,7.94,2018,10,October,87.35,NaN,87.35,NaN,87.35,NaN
1,2018-11,371.45,81,4.59,2018,11,November,371.45,332.53,371.45,NaN,371.45,NaN
2,2018-12,538.80,84,6.41,2018,12,December,538.80,466.22,538.80,NaN,538.80,NaN
3,2019-01,488.40,80,6.10,2019,01,January,488.40,488.80,488.40,410.78,488.40,NaN
4,2019-02,439.20,68,6.46,2019,02,February,439.20,489.03,439.20,473.48,439.20,NaN

In [103]:
# Trend Break Detection
SIGNAL = EXPENSES_MONTHLY["TOTAL_AMOUNT"].values
ALGO = rpt.Pelt(model="rbf").fit(SIGNAL)
BREAKS = ALGO.predict(pen=5)  # Tune the penalty value

<p>
Note: PELT (rbf) is the best model to detect the trend break since it captures both level & volatility shifts
</p>

In [104]:
# Trend Break Detection Visualisation
EXPENSES_MONTHLY["Year Month"] = pd.to_datetime(EXPENSES_MONTHLY["Year Month"])

fig_layout = go.Layout(
    autosize=True,
    width=1000,
    height=700,
)

fig = go.Figure(layout=fig_layout)

fig.add_trace(go.Scatter(
    x=EXPENSES_MONTHLY["Year Month"],
    y=EXPENSES_MONTHLY["TOTAL_AMOUNT"],
    name="Monthly Spend",
    hovertemplate=f"Time Period: %{{x}}<br>Total Amount: S$%{{y}}",
    mode="lines+markers",
    line_color="#B8A9A9"
))

for i in BREAKS[:-1]:
    BREAK_DATE = EXPENSES_MONTHLY["Year Month"].iloc[i]
    fig.add_vline(
        x=BREAK_DATE,
        line_width=3,
        line_color="#8b80d0"
    )

    fig.add_annotation(
        x=BREAK_DATE,
        y=EXPENSES_MONTHLY["TOTAL_AMOUNT"].max(),
        text=f"Trend Break on {BREAK_DATE.strftime('%b %Y')}",
        showarrow=False,
        font=dict(color="#FFFFFF"),
        align="center",
        bgcolor="#1e1e1e",
        opacity=0.8,
        yanchor="top"
    )

fig.update_layout(
    title="Trend Break Detection",
    xaxis_title="Time Period",
    yaxis_title="Total Spending (S$)",
    template="plotly_dark",
    height=800
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
A Trend Break is detected on November 2021 which is linked with the increased spending due to the beginning of employment upon graduation. Pelt/Binary Segmentation from the RPT package is used to detect the trend breaks. The approach is prioritise for efficient search for the optimal breakpoints using dynamic programming and actively recursively splits the signal to detect multiple changes.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="TREND_BREAK_DETECTION.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 A Trend Break is detected on November 2021 which is linked with the increased spending due to the beginning of employment upon
graduation. Pelt/Binary Segmentation from the RPT package is used to detect the trend breaks. The approach is prioritise for
efficient search for the optimal breakpoints using dynamic programming and actively recursively splits the signal to detect
multiple changes.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\TREND_BREAK_DETECTION.png
✅ Registered component: TREND_BREAK_DETECTION.png with Title Trend Break Detection

<hr>
<hr>

<h1>Predictive & Prescriptive</h1>
<p>What the next steps would be</p>

In [105]:
# Report Management
SECTION_TITLE = "Predictive & Prescriptive"
SECTION_CAPTION = "Leveraging on the analysis and data to optimise the financial planning for the future horizon"
REGISTER_REPORT_COMPONENT(
    TITLE=SECTION_TITLE,
    CONTENT=SECTION_CAPTION,
    TYPE="text",
    HEADING="h2",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="PREDICTIVE_AND_PRESCRIPTIVE"
)

✅ Registered component: PREDICTIVE_AND_PRESCRIPTIVE with Title Predictive & Prescriptive

<h2>Time Series Decomposition & Forecast Foundations</h2>
<p>What is likely to happen if nothing changes?</p>
<p> --> To determine the forecast baseline for future horizons given the historical data.</p>

In [106]:
# Report Management
SUBSECTION_TITLE = "Time Series Decomposition & Forecast Foundations"
SUBSECTION_CAPTION = "To determine the forecast baseline for future horizons given the historical data"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="PREDICTIVE_AND_PRESCRIPTIVE_FORECAST_FOUNDATIONS"
)

✅ Registered component: PREDICTIVE_AND_PRESCRIPTIVE_FORECAST_FOUNDATIONS with Title Time Series Decomposition & Forecast Foundations

In [107]:
EXPENSES

,Date,Year,ISO Year,Month,Month Label,Week,Week Label,Day,Category,Item,Vendor,Vendor Location,District,Income/Expenses,Amount,Formatted Date,Outlier,Day Type,Year Month
0,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Telephone,Top Up Singtel Card,7-Eleven,Blank,Clementi,Expenses,10.0,28/05/2019,False,Weekday,2019-05
1,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,15.3,28/05/2019,False,Weekday,2019-05
2,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Drinks,Bubble Tea,Koi,Takashimaya,Orchard,Expenses,1.8,28/05/2019,False,Weekday,2019-05
3,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Gift,Gift,Blank,Blank,Blank,Expenses,32.0,28/05/2019,False,Weekday,2019-05
4,2019-05-28,2019,2019,5,May,22,W22,Tuesday,Food,Korean BBQ,I Am Kim,Blank,Rochor,Expenses,15.0,28/05/2019,False,Weekday,2019-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3662,2023-08-02,2023,2023,8,August,31,W31,Wednesday,Food,Fried Rice,Blank,Blank,Clementi,Expenses,7.7,02/08/2023,False,Weekday,2023-08
3663,2023-08-02,2023,2023,8,August,31,W31,Wednesday,Food,Mixed Rice,Blank,Blank,Tanjong Pagar,Expenses,6.5,02/08/2023,False,Weekday,2023-08
3664,2023-08-02,2023,2023,8,August,31,W31,Wednesday,Transportation,Top Up Ezlink Card,Blank,Blank,Blank,Expenses,50.0,02/08/2023,False,Weekday,2023-08
3665,2023-08-01,2023,2023,8,August,31,W31,Tuesday,Food,Burrito,Guzman Y Gomez,Guoco Tower,Tanjong Pagar,Expenses,12.4,01/08/2023,False,Weekday,2023-08
3666,2023-08-01,2023,2023,8,August,31,W31,Tuesday,Food,Mixed Rice,Blank,Blank,Tanjong Pagar,Expenses,6.5,01/08/2023,False,Weekday,2023-08

In [108]:
MONTHLY_EXPENSES_TIME_SERIES = EXPENSES.groupby("Year Month")["Amount"].sum()
MONTHLY_EXPENSES_TIME_SERIES.index = pd.to_datetime(MONTHLY_EXPENSES_TIME_SERIES.index)
MONTHLY_EXPENSES_TIME_SERIES

Year Month
2018-10-01     87.35
2018-11-01    371.45
2018-12-01    538.80
2019-01-01    488.40
2019-02-01    439.20
               ...
2023-08-01    823.50
2023-09-01    567.00
2023-10-01    817.90
2023-11-01    668.60
2023-12-01    454.90
Name: Amount, Length: 61, dtype: float64

In [109]:
# Report Management
CAPTION = f"""In order to break down complex time series data into three core components: a long-term Trend, repeating Seasonal patterns, and random Residuals (noise), the Seasonal-Trend decomposition using LOESS (STL) method is employed. This technique is particularly effective for handling time series data with strong seasonal effects and can accommodate any type of seasonality. By decomposing the data, we can better understand the underlying patterns and make more informed decisions regarding budget recommendations.
"""

CAPTION2 = """The following formula is used to explain the STL Decomposition: 
"""

CAPTION3 = """Observed = Trend + Seasonality + Residual
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)
print(CAPTION2)
print(CAPTION3)

print("\n--------------------------------\n")

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="FORECAST_FOUNDATIONS_STL_DECOMPOSITION_BODY_1"
)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION2,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="FORECAST_FOUNDATIONS_STL_DECOMPOSITION_BODY_2"
)

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION3,
    TYPE="text",
    HEADING="normal",
    BODY="equation",
    PATH=None,
    REPORTING_TAG="FORECAST_FOUNDATIONS_STL_DECOMPOSITION_BODY_3"
)

In order to break down complex time series data into three core components: a long-term Trend, repeating Seasonal patterns, and
random Residuals (noise), the Seasonal-Trend decomposition using LOESS (STL) method is employed. This technique is particularly
effective for handling time series data with strong seasonal effects and can accommodate any type of seasonality. By decomposing
the data, we can better understand the underlying patterns and make more informed decisions regarding budget recommendations.
The following formula is used to explain the STL Decomposition:

Observed = Trend + Seasonality + Residual


--------------------------------

In [110]:
# STL Decomposition
STL_MODEL = STL(MONTHLY_EXPENSES_TIME_SERIES, period=12, robust=True)
STL_RESULT = STL_MODEL.fit()

STL_TREND = STL_RESULT.trend
STL_SEASONALITY = STL_RESULT.seasonal
STL_RESIDUAL = STL_RESULT.resid

In [111]:
# STL Decomposition Visualisation
fig = make_subplots(
    rows=4, cols=1,
    shared_xaxes=True,
    vertical_spacing=0.04,
    subplot_titles=[
        "Observed Monthly Expenses",
        "Trend (Long-Term Spending Direction)",
        "Seasonality (Recurring Yearly Pattern)",
        "Residuals (Irregular / One-off Spending)"
    ]
)

fig.add_trace(
    go.Scatter(
        x=MONTHLY_EXPENSES_TIME_SERIES.index,
        y=MONTHLY_EXPENSES_TIME_SERIES,
        name="Observed",
        line=dict(color="#E74C3C")
    ), 
    row=1, 
    col=1
)

fig.add_trace(
    go.Scatter(
        x=STL_TREND.index,
        y=STL_TREND,
        name="Trend",
        line=dict(color="#3498DB")
    ),
    row=2, 
    col=1
)

fig.add_trace(
    go.Scatter(
        x=STL_SEASONALITY.index,
        y=STL_SEASONALITY,
        name="Seasonality",
        line=dict(color="#2ECC71")
    ), 
    row=3, 
    col=1
)

fig.add_trace(
    go.Scatter(
        x=STL_RESIDUAL.index,
        y=STL_RESIDUAL,
        name="Residuals",
        line=dict(color="#95A5A6")
    ), 
    row=4, 
    col=1
)

fig.update_layout(
    height=900,
    width=1000,
    title="STL Decomposition of Monthly Expenses",
    template="plotly_dark",
    showlegend=False
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
Observed Monthly Expenses are volatile based on the monthly spending pattern. The Trend component shows a gradual increase in spending over time, indicating a rising cost of living or lifestyle changes. The Seasonality component reveals recurring patterns, with peaks and troughs corresponding to specific months, likely influenced by holidays or annual events. The Residuals capture irregular spending that does not follow the trend or seasonal patterns, representing one-off expenses or anomalies.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="STL_DECOMPOSITION_FORECAST_FOUNDATIONS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Observed Monthly Expenses are volatile based on the monthly spending pattern. The Trend component shows a gradual increase in
spending over time, indicating a rising cost of living or lifestyle changes. The Seasonality component reveals recurring patterns,
with peaks and troughs corresponding to specific months, likely influenced by holidays or annual events. The Residuals capture
irregular spending that does not follow the trend or seasonal patterns, representing one-off expenses or anomalies.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\STL_DECOMPOSITION_FORECAST_FOUNDATIONS.png
✅ Registered component: STL_DECOMPOSITION_FORECAST_FOUNDATIONS.png with Title STL Decomposition of Monthly Expenses

In [112]:
# ETS Forecasting for Budget Recommendation (24 Months)
MONTHLY_EXPENSES_TIME_SERIES = MONTHLY_EXPENSES_TIME_SERIES.asfreq("MS")
MONTHLY_EXPENSES_TIME_SERIES = MONTHLY_EXPENSES_TIME_SERIES.fillna(0)

ETS_MODEL = ExponentialSmoothing(
    MONTHLY_EXPENSES_TIME_SERIES,
    trend="add",
    seasonal="add",
    seasonal_periods=12
)

ETS_HORIZON = 24
ETS_FIT = ETS_MODEL.fit()
ETS_FORECAST = ETS_FIT.forecast(ETS_HORIZON)
ETS_FORECAST

2024-01-01    791.668938
2024-02-01    814.017723
2024-03-01    841.855339
2024-04-01    783.283920
2024-05-01    738.922260
2024-06-01    657.553024
2024-07-01    685.053339
2024-08-01    771.459618
2024-09-01    811.560745
2024-10-01    791.284830
2024-11-01    801.616282
2024-12-01    813.653903
2025-01-01    866.812149
2025-02-01    889.160934
2025-03-01    916.998549
2025-04-01    858.427131
2025-05-01    814.065471
2025-06-01    732.696235
2025-07-01    760.196550
2025-08-01    846.602829
2025-09-01    886.703956
2025-10-01    866.428041
2025-11-01    876.759493
2025-12-01    888.797114
Freq: MS, dtype: float64

In [113]:
print(ETS_FORECAST.describe())

count     24.000000
mean     812.732432
std       66.122717
min      657.553024
25%      780.327845
50%      813.835813
75%      866.524068
max      916.998549
dtype: float64

In [114]:
# ETS Forecast Visualisation
fig_layout = go.Layout(
    autosize=True,
    width=1000,
    height=700,
)

fig = go.Figure(layout=fig_layout)

fig.add_trace(
    go.Scatter(
        x=ETS_FORECAST.index,
        y=ETS_FORECAST,
        mode="lines+markers",
        name="Forecast",
        line=dict(color="#F39C12")
    )
)

fig.update_layout(
    title=f"ETS Forecast of Monthly Expenses (Next {ETS_HORIZON} Months)",
    xaxis_title="Month",
    yaxis_title="Expected Spending (S$)",
    template="plotly_dark",
    height=500
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
The ETS forecast predicts the monthly expenses for the next {ETS_HORIZON} months, showing a continued upward trend in spending. This suggests that without changes in spending habits or external factors, expenses are expected to rise steadily. The forecast can help in budgeting and financial planning by providing an estimate of future costs based on historical patterns.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="ETS_FORECAST_FORECAST_FOUNDATIONS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The ETS forecast predicts the monthly expenses for the next 24 months, showing a continued upward trend in spending. This
suggests that without changes in spending habits or external factors, expenses are expected to rise steadily. The forecast can
help in budgeting and financial planning by providing an estimate of future costs based on historical patterns.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\ETS_FORECAST_FORECAST_FOUNDATIONS.png
✅ Registered component: ETS_FORECAST_FORECAST_FOUNDATIONS.png with Title ETS Forecast of Monthly Expenses (Next 24 Months)

In [115]:
# Combined Historical and Forecast Visualisation
fig_layout = go.Layout(
    autosize=True,
    width=1000,
    height=700,
)

fig = go.Figure(layout=fig_layout)

# Historical
fig.add_trace(
    go.Scatter(
        x=MONTHLY_EXPENSES_TIME_SERIES.index,
        y=MONTHLY_EXPENSES_TIME_SERIES,
        name="Historical Spending",
        mode="lines+markers",
        line=dict(color="#5DADE2")
    )
)

# Forecast
fig.add_trace(
    go.Scatter(
        x=ETS_FORECAST.index,
        y=ETS_FORECAST,
        name="Forecasted Spending",
        mode="lines+markers",
        line=dict(color="#E67E22", dash="dash")
    )
)

fig.update_layout(
    title="Historical and Forecasted Monthly Expenses (ETS)",
    xaxis_title="Month",
    yaxis_title="Spending Amount (S$)",
    template="plotly_dark",
    height=600
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
Combining historical spending data with ETS forecast provides a comprehensive view of past trends and future expectations. The historical data shows actual spending patterns, while the forecasted data indicates where expenses are likely headed. This combined view aids in understanding how past behaviors influence future financial planning and budgeting.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="STL_ETS_FORECAST_FOUNDATIONS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Combining historical spending data with ETS forecast provides a comprehensive view of past trends and future expectations. The
historical data shows actual spending patterns, while the forecasted data indicates where expenses are likely headed. This
combined view aids in understanding how past behaviors influence future financial planning and budgeting.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\STL_ETS_FORECAST_FOUNDATIONS.png
✅ Registered component: STL_ETS_FORECAST_FOUNDATIONS.png with Title Historical and Forecasted Monthly Expenses (ETS)

In [116]:
# Report Management
CAPTION = f"""Based on the time series decomposition and forecasting results, monthly expenses are projected to remain on an upward trajectory, with an estimated average monthly expenditure of approximately ${ETS_FORECAST.mean():,.2f} over the forecast horizon. This projection reflects the continuation of long-term spending trends and recurring seasonal patterns observed in the historical data.

While short-term fluctuations are expected, the forecast provides a stable baseline for forward-looking financial planning rather than precise month-level predictions.
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)

print("\n--------------------------------\n")

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="FORECAST_FOUNDATIONS_SUMMARY_BODY_1"
)

Based on the time series decomposition and forecasting results, monthly expenses are projected to remain on an upward trajectory,
with an estimated average monthly expenditure of approximately $812.73 over the forecast horizon. This projection reflects the
continuation of long-term spending trends and recurring seasonal patterns observed in the historical data.  While short-term
fluctuations are expected, the forecast provides a stable baseline for forward-looking financial planning rather than precise
month-level predictions.

--------------------------------

In [117]:
# SARIMA Model
SARIMA_MODEL = SARIMAX(
    MONTHLY_EXPENSES_TIME_SERIES,
    order=(1, 1, 1),
    seasonal_order=(1, 1, 1, 12),
    enforce_stationarity=False,
    enforce_invertibility=False
)

SARIMA_MODEL = SARIMA_MODEL.fit(disp=False)
SARIMA_RESIDUALS = SARIMA_MODEL.resid
SARIMA_RESIDUALS = SARIMA_RESIDUALS.dropna()

In [118]:
# SARIMA Forecasting for Early Warning (24 Months)
FORECAST_HORIZON = 24
SARIMA_CI_ALPHA = 0.05
SARIMA_FORECAST = SARIMA_MODEL.get_forecast(steps=FORECAST_HORIZON)

SARIMA_FORECAST_MEAN = SARIMA_FORECAST.predicted_mean
SARIMA_FORECAST_CI = SARIMA_FORECAST.conf_int(alpha=SARIMA_CI_ALPHA) 

SARIMA_FORECAST_LOWER_CI = SARIMA_FORECAST_CI.iloc[:, 0]
SARIMA_FORECAST_UPPER_CI = SARIMA_FORECAST_CI.iloc[:, 1]

In [119]:
# SARIMA Forecast Visualisation
fig_layout = go.Layout(
    autosize=True,
    width=1000,
    height=700
)

fig = go.Figure(layout=fig_layout)

# Historical
fig.add_trace(go.Scatter(
    x=MONTHLY_EXPENSES_TIME_SERIES.index,
    y=MONTHLY_EXPENSES_TIME_SERIES,
    mode="lines",
    name="Historical Expenses",
    line=dict(color="#5DADE2")
))

# Forecast mean
fig.add_trace(go.Scatter(
    x=SARIMA_FORECAST_MEAN.index,
    y=SARIMA_FORECAST_MEAN,
    mode="lines",
    name="Forecast",
    line=dict(dash="dash", color="#F39C12")
))

# Confidence interval
fig.add_trace(go.Scatter(
    x=SARIMA_FORECAST_CI.index.tolist() + SARIMA_FORECAST_CI.index[::-1].tolist(),
    y=SARIMA_FORECAST_CI.iloc[:, 0].tolist() + SARIMA_FORECAST_CI.iloc[:, 1][::-1].tolist(),
    fill="toself",
    fillcolor="rgba(255,255,255,0.15)",
    line=dict(color="rgba(255,255,255,0)"),
    name="Confidence Interval"
))

fig.update_layout(
    title="SARIMA Forecast of Monthly Expenses",
    xaxis_title="Date",
    yaxis_title="Expenses",
    template="plotly_dark",
    height=600
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
Given historical data and model assumptions, there is a {(1 - SARIMA_CI_ALPHA) * 100}% probability that actual expenses will fall within this range. If an actual monthly expense exceeds the upper bound, it signals potential overspending requiring attention, while staying below the lower bound indicates underspending. The widening confidence interval reflects increasing uncertainty over longer forecast horizons, underscoring the need for regular forecast updates as new data becomes available.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="SARIMA_FORECAST_FOUNDATIONS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Given historical data and model assumptions, there is a 95.0% probability that actual expenses will fall within this range. If an
actual monthly expense exceeds the upper bound, it signals potential overspending requiring attention, while staying below the
lower bound indicates underspending. The widening confidence interval reflects increasing uncertainty over longer forecast
horizons, underscoring the need for regular forecast updates as new data becomes available.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\SARIMA_FORECAST_FOUNDATIONS.png
✅ Registered component: SARIMA_FORECAST_FOUNDATIONS.png with Title SARIMA Forecast of Monthly Expenses

In [120]:
# Report Management
CAPTION = f"""With a statistically validated SARIMA model and clearly defined confidence bounds, deviations beyond expected expenditure ranges can be systematically identified. This establishes a robust early warning mechanism that flags abnormal spending behavior before it compounds, enabling proactive financial intervention.
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)

print("\n--------------------------------\n")

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="FORECAST_FOUNDATIONS_SARIMA_BODY_1"
)

With a statistically validated SARIMA model and clearly defined confidence bounds, deviations beyond expected expenditure ranges
can be systematically identified. This establishes a robust early warning mechanism that flags abnormal spending behavior before
it compounds, enabling proactive financial intervention.

--------------------------------

In [121]:
# Create 2x2 subplot
fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        'Residuals Over Time',
        'Distribution of Residuals',
        'Q-Q Plot',
        'Autocorrelation Function (ACF)'
    ),
    vertical_spacing=0.12,
    horizontal_spacing=0.10,
    specs=[
        [{"type": "scatter"}, {"type": "histogram"}],
        [{"type": "scatter"}, {"type": "bar"}]
    ]
)

# Residuals Over Time (Top Left)
fig.add_trace(
    go.Scatter(
        x=SARIMA_RESIDUALS.index,
        y=SARIMA_RESIDUALS,
        mode="lines",
        name="Residuals",
        line=dict(color="#7FADDC"),
        showlegend=False
    ),
    row=1, col=1
)
fig.add_hline(y=0, line_dash="dash", line_color="gray", row=1, col=1)

# Histogram (Top Right)
fig.add_trace(
    go.Histogram(
        x=SARIMA_RESIDUALS,
        nbinsx=20,
        name="Residual Distribution",
        marker=dict(color="#7FADDC"),
        showlegend=False
    ),
    row=1, col=2
)

# QQ Plot (Bottom Left)
QQ_X = np.sort(SARIMA_RESIDUALS)
QQ_Y = stats.norm.ppf(np.linspace(0.01, 0.99, len(QQ_X)))

fig.add_trace(
    go.Scatter(
        x=QQ_Y,
        y=QQ_X,
        mode="markers",
        name="Sample Quantiles",
        marker=dict(color="#7FADDC", size=6),
        showlegend=False
    ),
    row=2, col=1
)
fig.add_trace(
    go.Scatter(
        x=QQ_Y,
        y=QQ_Y,
        mode="lines",
        name="45° Reference",
        line=dict(color="red", dash="dash"),
        showlegend=False
    ),
    row=2, col=1
)

# ACF Plot (Bottom Right)
SARIMA_ACF_VALUES = acf(SARIMA_RESIDUALS, nlags=24)
CONFIDENCE_INTERVAL = 1.96 / np.sqrt(len(SARIMA_RESIDUALS))

fig.add_trace(
    go.Bar(
        x=list(range(len(SARIMA_ACF_VALUES))),
        y=SARIMA_ACF_VALUES,
        name="ACF",
        marker=dict(color="#7FADDC"),
        showlegend=False
    ),
    row=2, col=2
)
fig.add_hline(
    y=CONFIDENCE_INTERVAL,
    line_dash="dash",
    line_color="red",
    row=2, col=2
)
fig.add_hline(
    y=-CONFIDENCE_INTERVAL,
    line_dash="dash",
    line_color="red",
    row=2, col=2
)

# Update axes labels
fig.update_xaxes(title_text="Date", row=1, col=1)
fig.update_yaxes(title_text="Residual", row=1, col=1)

fig.update_xaxes(title_text="Residual Value", row=1, col=2)
fig.update_yaxes(title_text="Frequency", row=1, col=2)

fig.update_xaxes(title_text="Theoretical Quantiles", row=2, col=1)
fig.update_yaxes(title_text="Sample Quantiles", row=2, col=1)

fig.update_xaxes(title_text="Lag", row=2, col=2)
fig.update_yaxes(title_text="ACF", row=2, col=2)

# Overall layout
fig.update_layout(
    title=dict(
        text="SARIMA Model Residual Diagnostics",
        x=0.5,
        xanchor='center',
        font=dict(size=20)
    ),
    height=900,
    width=1200,
    template="plotly_dark",
    showlegend=False
)

fig.show()

# Combined interpretation
FIG_TITLE = "SARIMA Model Residual Diagnostics"
PLOT_CAPTION = """
The residual diagnostics validate the SARIMA model's adequacy: (1) Residuals oscillate randomly around zero with no systematic patterns, indicating proper trend and seasonal capture; (2) The distribution is approximately normal and centered at zero, with most errors within -200 to +200, though heavier tails suggest occasional extreme spending events; (3) The Q-Q plot shows good alignment in the central region with deviation at extremes, typical for financial data with outliers; (4) ACF values decay rapidly and stay within confidence bounds (except lag-0), confirming no remaining autocorrelation. Overall, the model effectively captures the time series structure, with residual deviations attributable to genuine anomalies rather than model inadequacy.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="SARIMA_RESIDUALS_DIAGNOSTICS_FORECAST_FOUNDATIONS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The residual diagnostics validate the SARIMA model's adequacy: (1) Residuals oscillate randomly around zero with no systematic
patterns, indicating proper trend and seasonal capture; (2) The distribution is approximately normal and centered at zero, with
most errors within -200 to +200, though heavier tails suggest occasional extreme spending events; (3) The Q-Q plot shows good
alignment in the central region with deviation at extremes, typical for financial data with outliers; (4) ACF values decay rapidly
and stay within confidence bounds (except lag-0), confirming no remaining autocorrelation. Overall, the model effectively captures
the time series structure, with residual deviations attributable to genuine anomalies rather than model inadequacy.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\SARIMA_RESIDUALS_DIAGNOSTICS_FORECAST_FOUNDATIONS.png
✅ Registered component: SARIMA_RESIDUALS_DIAGNOSTICS_FORECAST_FOUNDATIONS.png with Title SARIMA Model Residual Diagnostics

In [122]:
# Model Comparison
MODEL_COMPARISON_DF = pd.DataFrame({
    "Model": ["ETS", "SARIMA"],
    "AIC": [ETS_FIT.aic, SARIMA_MODEL.aic],
    "BIC": [ETS_FIT.bic, SARIMA_MODEL.bic],
    "RMSE": [
        root_mean_squared_error(
            MONTHLY_EXPENSES_TIME_SERIES,
            ETS_FIT.fittedvalues
        ),
        root_mean_squared_error(
            MONTHLY_EXPENSES_TIME_SERIES,
            SARIMA_MODEL.fittedvalues
        )
    ]
})

MODEL_COMPARISON_DF = MODEL_COMPARISON_DF.set_index("Model")
MODEL_COMPARISON_DF = MODEL_COMPARISON_DF.style.format({
    "AIC": "{:.2f}",
    "BIC": "{:.2f}",
    "RMSE": "{:.2f}"
})
MODEL_COMPARISON_DF

In [123]:
# Visual comparison
fig_layout = go.Layout(
    autosize=True,
    width=1000,
    height=700,
)

fig = go.Figure()

# Add actual
fig.add_trace(
    go.Scatter(
        x=MONTHLY_EXPENSES_TIME_SERIES.index,
        y=MONTHLY_EXPENSES_TIME_SERIES,
        name='Actual', 
        line=dict(color='#7FADDC', width=2)
    )
)

# Add ETS forecast
fig.add_trace(
    go.Scatter(
        x=ETS_FORECAST.index,
        y=ETS_FORECAST,
        name='ETS Forecast',
        line=dict(color='#E8B4B8', width=2, dash='dash')
    )
)

# Add SARIMA forecast
fig.add_trace(
    go.Scatter(
        x=SARIMA_FORECAST_MEAN.index,
        y=SARIMA_FORECAST_MEAN,
        name='SARIMA Forecast',
        line=dict(color='#4ECDC4', width=2, dash='dot')
    )
)

fig.update_layout(
    title="Model Comparison: ETS vs SARIMA",
    xaxis_title="Date",
    yaxis_title="Expenses",
    template="plotly_dark"
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
The comparison reveals distinct behavioral differences between ETS and SARIMA models. ETS produces smoother, more stable forecasts by gradually weighting historical data, making it less reactive to recent changes. In contrast, SARIMA demonstrates higher sensitivity to recent spending patterns, particularly visible in the post-2023 period where it captures the downward trend more aggressively. This adaptive characteristic makes SARIMA more suitable for anomaly detection, as it adjusts its baseline expectations faster, allowing genuine deviations to be detected rather than being masked by outdated historical averages. The trade-off is increased forecast variance, but for early warning systems, responsiveness to recent patterns outweighs smoothness.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="MODEL_COMPARISON_FORECAST_FOUNDATIONS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The comparison reveals distinct behavioral differences between ETS and SARIMA models. ETS produces smoother, more stable
forecasts by gradually weighting historical data, making it less reactive to recent changes. In contrast, SARIMA demonstrates
higher sensitivity to recent spending patterns, particularly visible in the post-2023 period where it captures the downward trend
more aggressively. This adaptive characteristic makes SARIMA more suitable for anomaly detection, as it adjusts its baseline
expectations faster, allowing genuine deviations to be detected rather than being masked by outdated historical averages. The
trade-off is increased forecast variance, but for early warning systems, responsiveness to recent patterns outweighs smoothness.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\MODEL_COMPARISON_FORECAST_FOUNDATIONS.png
✅ Registered component: MODEL_COMPARISON_FORECAST_FOUNDATIONS.png with Title Model Comparison: ETS vs SARIMA

<h2>Anomaly Detection & Early Warning</h2>
<p>Relative to historical patterns, is my current or upcoming spending abnormal?</p>
<p> --> To predict overspending in the future based on the trends.</p>

In [124]:
# Report Management
SUBSECTION_TITLE = "Early Warning & Anomaly Detection"
SUBSECTION_CAPTION = "To predict overspending in the future based on the trends"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="PREDICTIVE_AND_PRESCRIPTIVE_ANOMALY_DETECTION"
)

✅ Registered component: PREDICTIVE_AND_PRESCRIPTIVE_ANOMALY_DETECTION with Title Early Warning & Anomaly Detection

In [125]:
# Report Management
CAPTION = f"""Back-testing serves as our primary anomaly detection method. By performing 
rolling-window forecasts and comparing predictions to actual values, we can:
1. Identify months where actual spending falls outside predicted confidence intervals
2. Ensure anomalies are detected based on historical patterns, not one-time model fit
3. Validate detection robustness across different time periods

Anomalies are flagged when actual expenses fall outside the 95% confidence interval
of the SARIMA forecast.
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)

print("\n--------------------------------\n")

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="ANOMALY_DETECTION_PREFACE_1"
)

Back-testing serves as our primary anomaly detection method. By performing  rolling-window forecasts and comparing predictions to
actual values, we can: 1. Identify months where actual spending falls outside predicted confidence intervals 2. Ensure anomalies
are detected based on historical patterns, not one-time model fit 3. Validate detection robustness across different time periods
Anomalies are flagged when actual expenses fall outside the 95% confidence interval of the SARIMA forecast.

--------------------------------

In [126]:
# Back-testing Early Warning System
BACKTEST_MONTHS = 12
BACKTEST_START_DATE = len(MONTHLY_EXPENSES_TIME_SERIES) - BACKTEST_MONTHS

MONTHLY_EXPENSES_TIME_SERIES_COPY = MONTHLY_EXPENSES_TIME_SERIES.copy()

In [127]:
RESULTS = []
SARIMA_ORDER = (1,1,1)
SEASONAL_ORDER = (1,0,1,12)

for i in range(BACKTEST_START_DATE, len(MONTHLY_EXPENSES_TIME_SERIES_COPY)):
    TRAIN_DATA = MONTHLY_EXPENSES_TIME_SERIES_COPY.iloc[:i]

    MODEL = SARIMAX(
        TRAIN_DATA,
        order=SARIMA_ORDER,
        seasonal_order=SEASONAL_ORDER,
        enforce_stationarity=False,
        enforce_invertibility=False
    )

    FITTED_MODEL = MODEL.fit(
        disp=False
    )

    FORECAST = FITTED_MODEL.get_forecast(steps=1)

    MEAN = FORECAST.predicted_mean.iloc[0]
    CI = FORECAST.conf_int().iloc[0]

    LOWER_CI = CI[0]
    UPPER_CI = CI[1]

    ACTUAL_VALUE = MONTHLY_EXPENSES_TIME_SERIES_COPY.iloc[i]

    ANOMALY_CI = (ACTUAL_VALUE < LOWER_CI) or (ACTUAL_VALUE > UPPER_CI)

    RESULTS.append({
        "Date": MONTHLY_EXPENSES_TIME_SERIES_COPY.index[i],
        "Actual": ACTUAL_VALUE,
        "Forecast": MEAN,
        "Lower CI": LOWER_CI,
        "Upper CI": UPPER_CI,
        "Anomaly CI": ANOMALY_CI,
        "Error": ACTUAL_VALUE - MEAN
    })

BACKTEST_RESULTS = pd.DataFrame(RESULTS)
BACKTEST_RESULTS.set_index("Date", inplace=True)
BACKTEST_RESULTS

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:25: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:26: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:25: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:26: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:25: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:26: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:25: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:26: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:25: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:26: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:25: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:26: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:25: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:26: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:25: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:26: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:25: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:26: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:25: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:26: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:25: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:26: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:25: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1999587202.py:26: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

            Actual    Forecast    Lower CI    Upper CI  Anomaly CI       Error
Date
2023-01-01   793.4  570.422461  370.264168  770.580753        True  222.977539
2023-02-01   776.8  734.616595  525.843324  943.389866       False   42.183405
2023-03-01   773.3  745.396845  538.902096  951.891595       False   27.903155
2023-04-01   751.8  744.097518  540.058238  948.136798       False    7.702482
2023-05-01   657.0  746.697945  545.205558  948.190332       False  -89.697945
2023-06-01   688.7  687.016441  486.173555  887.859328       False    1.683559
2023-07-01   680.5  710.332455  511.897992  908.766917       False  -29.832455
2023-08-01   823.5  690.187530  493.874577  886.500483       False  133.312470
2023-09-01   567.0  763.856349  565.854412  961.858286       False -196.856349
2023-10-01   817.9  647.806507  444.533566  851.079448       False  170.093493
2023-11-01   668.6  753.561752  546.787360  960.336145       False  -84.961752
2023-12-01   454.9  721.940146  515.926585  927.953707        True -267.040146

In [128]:
# Back-testing Anomaly CI Result
ANOMALIES_CI = BACKTEST_RESULTS[BACKTEST_RESULTS["Anomaly CI"] == True]
ANOMALIES_CI["Month Year Label"] = ANOMALIES_CI.index.strftime("%b %Y")

ANOMALIES_CI_MONTH_LIST = []
for i in ANOMALIES_CI["Month Year Label"]:
    ANOMALIES_CI_MONTH_LIST.append(i)

ANOMALIES_CI_MONTH_STRING = ", ".join(ANOMALIES_CI_MONTH_LIST)
if ANOMALIES_CI_MONTH_STRING == "":
    ANOMALIES_CI_MONTH_STRING = "None"
ANOMALIES_CI_MONTH_STRING

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1670284649.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

'Jan 2023, Dec 2023'

In [129]:
# Back-testing Dataframe Test
print("Data shape:", MONTHLY_EXPENSES_TIME_SERIES_COPY.shape)
print("Data range:", MONTHLY_EXPENSES_TIME_SERIES_COPY.min(), "to", MONTHLY_EXPENSES_TIME_SERIES_COPY.max())
print("Training size at start:", BACKTEST_START_DATE)

# Actual vs Forecast Comparison
print("\nFirst few results:")
for result in RESULTS[:3]:
    print(f"Date: {result['Date']}, Actual: {result['Actual']:.2f}, Forecast: {result['Forecast']:.2f}")

Data shape: (63,)
Data range: 0.0 to 875.1
Training size at start: 51

First few results:
Date: 2023-01-01 00:00:00, Actual: 793.40, Forecast: 570.42
Date: 2023-02-01 00:00:00, Actual: 776.80, Forecast: 734.62
Date: 2023-03-01 00:00:00, Actual: 773.30, Forecast: 745.40

In [130]:
# Backtesting Visualisation
fig_layout = go.Layout(
    autosize=True
)

fig = make_subplots(
    rows=2, cols=1,
    row_heights=[0.7, 0.3],
    subplot_titles=("Expense Forecast vs Actual with Confidence Intervals", "Forecast Error"),
    vertical_spacing=0.12
)

# Add actual values
fig.add_trace(
    go.Scatter(
        x=BACKTEST_RESULTS.index,
        y=BACKTEST_RESULTS["Actual"],
        mode="lines+markers",
        name="Actual",
        line=dict(color="#2E86AB", width=2),
        marker=dict(size=6)
    ),
    row=1, 
    col=1
)

# Add forecast
fig.add_trace(
    go.Scatter(
        x=BACKTEST_RESULTS.index,
        y=BACKTEST_RESULTS["Forecast"],
        mode="lines",
        name="Forecast",
        line=dict(color="#A23B72", width=2, dash="dash")
    ),
    row=1, 
    col=1
)

# Add confidence interval
fig.add_trace(
    go.Scatter(
        x=BACKTEST_RESULTS.index,
        y=BACKTEST_RESULTS["Upper CI"],
        mode="lines",
        name="Upper CI",
        line=dict(width=0),
        showlegend=False,
        hoverinfo="skip"
    ),
    row=1, 
    col=1
)

fig.add_trace(
    go.Scatter(
        x=BACKTEST_RESULTS.index,
        y=BACKTEST_RESULTS["Lower CI"],
        mode="lines",
        name="Confidence Interval",
        fill="tonexty",
        fillcolor="rgba(162, 59, 114, 0.2)",
        line=dict(width=0),
        showlegend=True
    ),
    row=1, 
    col=1
)

# Highlight anomalies
if len(ANOMALIES_CI) > 0:
    fig.add_trace(
        go.Scatter(
            x=ANOMALIES_CI.index,
            y=ANOMALIES_CI["Actual"],
            mode="markers",
            name="Anomalies",
            marker=dict(
                size=12,
                color="#C73E1D",
                symbol="x",
            )
        ),
        row=1, 
        col=1
    )

# Add error bars
fig.add_trace(
    go.Bar(
        x=BACKTEST_RESULTS.index,
        y=BACKTEST_RESULTS["Error"],
        name="Forecast Error",
        marker=dict(
            color=BACKTEST_RESULTS["Error"],
            colorscale="RdYlGn_r",
            showscale=True,
            colorbar=dict(title="Error", y=0.15, len=0.3)
        )
    ),
    row=2, 
    col=1
)

# Update layout
fig.update_xaxes(title_text="Date", row=2, col=1)
fig.update_yaxes(title_text="Expenses", row=1, col=1)
fig.update_yaxes(title_text="Error", row=2, col=1)

fig.update_layout(
    title=dict(
        text="Anomaly Detection via Confidence Intervals Backtesting",
        x=0.5,
        xanchor="center",
        font=dict(size=20)
    ),
    height=800,
    width=1000,
    hovermode="x unified",
    template="plotly_dark",
    showlegend=True
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
The back-testing results demonstrate the SARIMA model's effectiveness in forecasting monthly expenses, with most actual values falling within the predicted confidence intervals. Detected anomalies highlight months where spending deviated significantly from expectations, validating the early warning system's capability to identify potential overspending events.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="CI_ANOMALY_DETECTION.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The back-testing results demonstrate the SARIMA model's effectiveness in forecasting monthly expenses, with most actual values
falling within the predicted confidence intervals. Detected anomalies highlight months where spending deviated significantly from
expectations, validating the early warning system's capability to identify potential overspending events.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\CI_ANOMALY_DETECTION.png
✅ Registered component: CI_ANOMALY_DETECTION.png with Title Anomaly Detection via Confidence Intervals Backtesting

In [131]:
# Report Management
CAPTION = f"""By systematically back-testing the SARIMA model over the past {BACKTEST_MONTHS} months, we have validated its predictive accuracy and reliability in identifying spending anomalies. The model's ability to flag deviations beyond established confidence intervals provides a robust early warning mechanism, empowering proactive financial management and timely interventions to mitigate overspending risks. The following months are flagged as anomalies: {ANOMALIES_CI_MONTH_STRING}. The months identified can be further investigated to understand the underlying causes and implement corrective actions as needed since they represent significant deviations from expected spending patterns.
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)

print("\n--------------------------------\n")

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="ANOMALY_DETECTION_CI_SUMMARY_BODY_1"
)

By systematically back-testing the SARIMA model over the past 12 months, we have validated its predictive accuracy and reliability
in identifying spending anomalies. The model's ability to flag deviations beyond established confidence intervals provides a
robust early warning mechanism, empowering proactive financial management and timely interventions to mitigate overspending risks.
The following months are flagged as anomalies: Jan 2023, Dec 2023. The months identified can be further investigated to understand
the underlying causes and implement corrective actions as needed since they represent significant deviations from expected
spending patterns.

--------------------------------

In [132]:
# Residuals Z-Score Anomaly Detection
RESIDUALS = BACKTEST_RESULTS["Error"]
Z_SCORES = np.abs(stats.zscore(RESIDUALS))
BACKTEST_RESULTS["Z-Score"] = Z_SCORES

In [133]:
# Diagnostic: Check z-score distribution
print("Z-Score Distribution Analysis:")
print(f"  Max Z-Score: {Z_SCORES.max():.2f}")
print(f"  95th Percentile: {np.percentile(Z_SCORES, 95):.2f}")
print(f"  90th Percentile: {np.percentile(Z_SCORES, 90):.2f}")
print(f"  Mean: {Z_SCORES.mean():.2f}")
print(f"  Std Dev: {Z_SCORES.std():.2f}")

Z-Score Distribution Analysis:
  Max Z-Score: 1.91
  95th Percentile: 1.78
  90th Percentile: 1.64
  Mean: 0.78
  Std Dev: 0.62

In [134]:
# 95% Confidence Level Threshold
Z_SCORES_THRESHOLD = 1.5
BACKTEST_RESULTS['Anomaly Z-Score'] = Z_SCORES > Z_SCORES_THRESHOLD
BACKTEST_RESULTS

,Actual,Forecast,Lower CI,Upper CI,Anomaly CI,Error,Z-Score,Anomaly Z-Score
Date,,,,,,,,
2023-01-01,793.4,570.422461,370.264168,770.580753,True,222.977539,1.666697,True
2023-02-01,776.8,734.616595,525.843324,943.389866,False,42.183405,0.346171,False
2023-03-01,773.3,745.396845,538.902096,951.891595,False,27.903155,0.241867,False
2023-04-01,751.8,744.097518,540.058238,948.136798,False,7.702482,0.094321,False
2023-05-01,657.0,746.697945,545.205558,948.190332,False,-89.697945,0.617095,False
2023-06-01,688.7,687.016441,486.173555,887.859328,False,1.683559,0.050358,False
2023-07-01,680.5,710.332455,511.897992,908.766917,False,-29.832455,0.179836,False
2023-08-01,823.5,690.187530,493.874577,886.500483,False,133.312470,1.011780,False
2023-09-01,567.0,763.856349,565.854412,961.858286,False,-196.856349,1.399784,False
2023-10-01,817.9,647.806507,444.533566,851.079448,False,170.093493,1.280430,False
2023-11-01,668.6,753.561752,546.787360,960.336145,False,-84.961752,0.582502,False
2023-12-01,454.9,721.940146,515.926585,927.953707,True,-267.040146,1.912408,True

In [135]:
# Anomaly Z-score
ANOMALIES_ZSCORE = BACKTEST_RESULTS[BACKTEST_RESULTS["Anomaly Z-Score"] == True]
ANOMALIES_ZSCORE["Month Year Label"] = ANOMALIES_ZSCORE.index.strftime("%b %Y")

ANOMALIES_ZSCORE_MONTH_LIST = []
for i in ANOMALIES_ZSCORE["Month Year Label"]:
    ANOMALIES_ZSCORE_MONTH_LIST.append(i)

ANOMALIES_ZSCORE_MONTH_STRING = ", ".join(ANOMALIES_ZSCORE_MONTH_LIST)
if ANOMALIES_ZSCORE_MONTH_STRING == "":
    ANOMALIES_ZSCORE_MONTH_STRING = "None"
ANOMALIES_ZSCORE_MONTH_STRING

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\1243806539.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

'Jan 2023, Dec 2023'

In [136]:
# Z-Score Distribution & Error vs Spending Level
fig = make_subplots(
    rows=1, 
    cols=2,
    subplot_titles=(
        "Distribution of Forecast Errors",
        "Error by Spending Level"
    ),
    horizontal_spacing=0.12
)

# Error Distribution Histogram with Normal Overlay
fig.add_trace(
    go.Histogram(
        x=BACKTEST_RESULTS["Error"],
        nbinsx=25,
        name="Forecast Error",
        marker=dict(color="#7FADDC"),
        showlegend=False
    ),
    row=1, 
    col=1
)

# Add Normal Distribution Overlay
mu = BACKTEST_RESULTS["Error"].mean()
sigma = BACKTEST_RESULTS["Error"].std()
x_range = np.linspace(BACKTEST_RESULTS["Error"].min(), BACKTEST_RESULTS["Error"].max(), 100)
y_normal = stats.norm.pdf(x_range, mu, sigma) * len(BACKTEST_RESULTS) * (BACKTEST_RESULTS["Error"].max() - BACKTEST_RESULTS["Error"].min()) / 25

fig.add_trace(
    go.Scatter(
        x=x_range,
        y=y_normal,
        mode="lines",
        name="Normal Distribution",
        line=dict(color="#FF6B6B", width=3, dash="dash")
    ),
    row=1,
    col=1
)

# Error vs Actual Spending (Scatter)
fig.add_trace(
    go.Scatter(
        x=BACKTEST_RESULTS["Actual"],
        y=BACKTEST_RESULTS["Error"],
        mode="markers",
        name="Forecast Error",
        marker=dict(
            size=8,
            color=BACKTEST_RESULTS["Error"],
            colorscale="RdYlGn_r",
            showscale=True,
            colorbar=dict(title="Error ($)", x=1.01, y=0.35)
        ),
        showlegend=False
    ),
    row=1,
    col=2
)

# Add Zero Line
fig.add_hline(y=0, line_dash="dash", line_color="white", row=1, col=2)

# Add Trend Line (if there's heteroscedasticity)
z = np.polyfit(BACKTEST_RESULTS["Actual"], BACKTEST_RESULTS["Error"], 1)
p = np.poly1d(z)
fig.add_trace(
    go.Scatter(
        x=BACKTEST_RESULTS["Actual"],
        y=p(BACKTEST_RESULTS["Actual"]),
        mode="lines",
        name="Trend",
        line=dict(color="#4ECDC4", width=2, dash="dot")
    ),
    row=1,
    col=2
)

# Update Axes
fig.update_xaxes(title_text="Forecast Error ($)", row=1, col=1)
fig.update_yaxes(title_text="Frequency", row=1, col=1)

fig.update_xaxes(title_text="Actual Spending ($)", row=1, col=2)
fig.update_yaxes(title_text="Forecast Error ($)", row=1, col=2)

fig.update_layout(
    title=dict(
        text="Forecast Error Distribution & Patterns",
        x=0.5,
        xanchor="center",
        font=dict(size=20)
    ),
    height=500,
    width=1000,
    template="plotly_dark",
    showlegend=True
)

fig.show()

FIG_TITLE = "Forecast Error Distribution & Patterns"
PLOT_CAPTION = """
Analysis of forecast error distribution reveals the nature of prediction uncertainty. The left panel shows error distribution against a normal curve, testing the assumption that forecast errors follow a symmetric, bell-shaped pattern. Deviations from normality, particularly in the tails, indicate the presence of outliers or skewed prediction errors. The right panel examines whether forecast accuracy varies with spending level (heteroscedasticity). A flat trend line around zero suggests consistent accuracy across all spending magnitudes, while a sloped trend indicates systematic over or under-prediction at different expense levels. This diagnostic helps identify whether model adjustments or stratified forecasting approaches are needed.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="ZSCORE_ANOMALY_DETECTION.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Analysis of forecast error distribution reveals the nature of prediction uncertainty. The left panel shows error distribution
against a normal curve, testing the assumption that forecast errors follow a symmetric, bell-shaped pattern. Deviations from
normality, particularly in the tails, indicate the presence of outliers or skewed prediction errors. The right panel examines
whether forecast accuracy varies with spending level (heteroscedasticity). A flat trend line around zero suggests consistent
accuracy across all spending magnitudes, while a sloped trend indicates systematic over or under-prediction at different expense
levels. This diagnostic helps identify whether model adjustments or stratified forecasting approaches are needed.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\ZSCORE_ANOMALY_DETECTION.png
✅ Registered component: ZSCORE_ANOMALY_DETECTION.png with Title Forecast Error Distribution & Patterns

In [137]:
# Report Management
CAPTION = f"""Using Z-score threshold of {Z_SCORES_THRESHOLD} since the maximum observed Z-score is {Z_SCORES.max():.2f}, which indicates that there are significant deviations in the residuals. A threshold of {Z_SCORES_THRESHOLD} standard deviations effectively captures these anomalies while minimizing false positives. This threshold balances sensitivity and specificity, ensuring that genuine anomalies are detected without overwhelming the system with false alarms. In this case, the months identified as anomalies based on Z-score analysis are: {ANOMALIES_ZSCORE_MONTH_STRING}.
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)

print("\n--------------------------------\n")

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="ANOMALY_DETECTION_ZSCORE_SUMMARY_BODY_1"
)

Using Z-score threshold of 1.5 since the maximum observed Z-score is 1.91, which indicates that there are significant deviations
in the residuals. A threshold of 1.5 standard deviations effectively captures these anomalies while minimizing false positives.
This threshold balances sensitivity and specificity, ensuring that genuine anomalies are detected without overwhelming the system
with false alarms. In this case, the months identified as anomalies based on Z-score analysis are: Jan 2023, Dec 2023.

--------------------------------

In [138]:
# IQR Anomaly Detection
ACTUAL_Q1 = BACKTEST_RESULTS["Actual"].quantile(0.25)
ACTUAL_Q3 = BACKTEST_RESULTS["Actual"].quantile(0.75)
ACTUAL_IQR = ACTUAL_Q3 - ACTUAL_Q1
ACTUAL_IQR_LOWER_BOUND = ACTUAL_Q1 - 1.5 * ACTUAL_IQR
ACTUAL_IQR_UPPER_BOUND = ACTUAL_Q3 + 1.5 * ACTUAL_IQR
BACKTEST_RESULTS["Anomaly IQR"] = (
    (BACKTEST_RESULTS["Actual"] < ACTUAL_IQR_LOWER_BOUND) | 
    (BACKTEST_RESULTS["Actual"] > ACTUAL_IQR_UPPER_BOUND)
)
BACKTEST_RESULTS

,Actual,Forecast,Lower CI,Upper CI,Anomaly CI,Error,Z-Score,Anomaly Z-Score,Anomaly IQR
Date,,,,,,,,,
2023-01-01,793.4,570.422461,370.264168,770.580753,True,222.977539,1.666697,True,False
2023-02-01,776.8,734.616595,525.843324,943.389866,False,42.183405,0.346171,False,False
2023-03-01,773.3,745.396845,538.902096,951.891595,False,27.903155,0.241867,False,False
2023-04-01,751.8,744.097518,540.058238,948.136798,False,7.702482,0.094321,False,False
2023-05-01,657.0,746.697945,545.205558,948.190332,False,-89.697945,0.617095,False,False
2023-06-01,688.7,687.016441,486.173555,887.859328,False,1.683559,0.050358,False,False
2023-07-01,680.5,710.332455,511.897992,908.766917,False,-29.832455,0.179836,False,False
2023-08-01,823.5,690.187530,493.874577,886.500483,False,133.312470,1.011780,False,False
2023-09-01,567.0,763.856349,565.854412,961.858286,False,-196.856349,1.399784,False,False
2023-10-01,817.9,647.806507,444.533566,851.079448,False,170.093493,1.280430,False,False
2023-11-01,668.6,753.561752,546.787360,960.336145,False,-84.961752,0.582502,False,False
2023-12-01,454.9,721.940146,515.926585,927.953707,True,-267.040146,1.912408,True,True

In [139]:
# Anomaly IQR
ANOMALIES_IQR = BACKTEST_RESULTS[BACKTEST_RESULTS["Anomaly IQR"] == True]
ANOMALIES_IQR["Month Year Label"] = ANOMALIES_IQR.index.strftime("%b %Y")

ANOMALIES_IQR_MONTH_LIST = []
for i in ANOMALIES_IQR["Month Year Label"]:
    ANOMALIES_IQR_MONTH_LIST.append(i)

ANOMALIES_IQR_MONTH_STRING = ", ".join(ANOMALIES_IQR_MONTH_LIST)
if ANOMALIES_IQR_MONTH_STRING == "":
    ANOMALIES_IQR_MONTH_STRING = "None"
ANOMALIES_IQR_MONTH_STRING

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\2389511453.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

'Dec 2023'

In [140]:
# Calculate IQR statistics
Q1 = BACKTEST_RESULTS["Actual"].quantile(0.25)
Q3 = BACKTEST_RESULTS["Actual"].quantile(0.75)
IQR = Q3 - Q1
LOWER_BOUND = Q1 - 1.5 * IQR
UPPER_BOUND = Q3 + 1.5 * IQR
MEDIAN = BACKTEST_RESULTS["Actual"].median()

fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        "IQR Anomaly Detection Over Time",
        "Box Plot Distribution",
        "Spending Distribution with IQR Bounds",
        "IQR Statistics Summary"
    ),
    specs=[
        [{"type": "scatter", "colspan": 2}, None],
        [{"type": "box"}, {"type": "histogram"}]
    ],
    vertical_spacing=0.15,
    horizontal_spacing=0.12,
    row_heights=[0.6, 0.4]
)

# Main Time Series with IQR Zones (TOP - spans both columns)
# Normal zone shading
fig.add_hrect(
    y0=LOWER_BOUND, y1=UPPER_BOUND,
    fillcolor="rgba(76, 205, 196, 0.1)",
    line_width=0,
    row=1, col=1
)

# Caution zones (beyond IQR but not extreme)
fig.add_hrect(
    y0=UPPER_BOUND, y1=UPPER_BOUND * 1.2,
    fillcolor="rgba(255, 193, 7, 0.1)",
    line_width=0,
    row=1, col=1
)
fig.add_hrect(
    y0=LOWER_BOUND * 0.8, y1=LOWER_BOUND,
    fillcolor="rgba(255, 193, 7, 0.1)",
    line_width=0,
    row=1, col=1
)

# Actual spending line
fig.add_trace(
    go.Scatter(
        x=BACKTEST_RESULTS.index,
        y=BACKTEST_RESULTS["Actual"],
        mode="lines+markers",
        name="Actual Spending",
        line=dict(color="#7FADDC", width=2),
        marker=dict(size=5)
    ),
    row=1, col=1
)

# Upper and lower IQR bounds
fig.add_hline(
    y=UPPER_BOUND,
    line_dash="dash",
    line_color="#FF6B6B",
    annotation_text=f"Upper: ${UPPER_BOUND:.2f}",
    annotation_font_color="#FF6B6B",
    row=1, col=1
)
fig.add_hline(
    y=LOWER_BOUND,
    line_dash="dash",
    line_color="#FF6B6B",
    annotation_text=f"Lower: ${LOWER_BOUND:.2f}",
    annotation_font_color="#FF6B6B",
    row=1, col=1
)
fig.add_hline(
    y=Q1,
    line_dash="dot",
    line_color="#4ECDC4",
    annotation_text=f"Q1: ${Q1:.2f}",
    annotation_font_color="#4ECDC4",
    row=1, col=1
)
fig.add_hline(
    y=Q3,
    line_dash="dot",
    line_color="#4ECDC4",
    annotation_text=f"Q3: ${Q3:.2f}",
    annotation_font_color="#4ECDC4",
    row=1, col=1
)
fig.add_hline(
    y=MEDIAN,
    line_dash="solid",
    line_color="#FFA500",
    annotation_text=f"Median: ${MEDIAN:.2f}",
    annotation_font_color="#FFA500",
    row=1, col=1
)

# IQR anomalies
IQR_ANOMALIES = BACKTEST_RESULTS[BACKTEST_RESULTS["Anomaly IQR"]]
if len(IQR_ANOMALIES) > 0:
    fig.add_trace(
        go.Scatter(
            x=IQR_ANOMALIES.index,
            y=IQR_ANOMALIES["Actual"],
            mode="markers",
            name="IQR Anomalies",
            marker=dict(
                size=14,
                color="#FF6B6B",
                symbol="x",
                line=dict(width=2, color="white")
            )
        ),
        row=1, col=1
    )

# Box Plot (BOTTOM LEFT)
fig.add_trace(
    go.Box(
        y=BACKTEST_RESULTS["Actual"],
        name="Monthly Expenses",
        marker_color="#7FADDC",
        boxmean=True,
        showlegend=False
    ),
    row=2, col=1
)

# Histogram with bounds (BOTTOM RIGHT)
fig.add_trace(
    go.Histogram(
        x=BACKTEST_RESULTS["Actual"],
        nbinsx=20,
        name="Spending Distribution",
        marker=dict(color="#7FADDC"),
        showlegend=False
    ),
    row=2, col=2
)

# Add vertical lines for bounds on histogram
fig.add_vline(
    x=UPPER_BOUND, line_dash="dash",
    line_color="#FF6B6B",
    annotation_text="Upper",
    row=2, col=2
)
fig.add_vline(
    x=LOWER_BOUND, line_dash="dash",
    line_color="#FF6B6B",
    annotation_text="Lower",
    row=2, col=2
)
fig.add_vline(
    x=MEDIAN, line_dash="solid",
    line_color="#FFA500",
    annotation_text="Median",
    row=2, col=2
)

# Update axes
fig.update_xaxes(title_text="Date", row=1, col=1)
fig.update_yaxes(title_text="Expenses ($)", row=1, col=1)

fig.update_yaxes(title_text="Expenses ($)", row=2, col=1)

fig.update_xaxes(title_text="Expenses ($)", row=2, col=2)
fig.update_yaxes(title_text="Frequency", row=2, col=2)

fig.update_layout(
    title=dict(
        text="IQR-Based Anomaly Detection",
        x=0.5,
        xanchor="center",
        font=dict(size=20)
    ),
    height=900,
    width=1000,
    template="plotly_dark",
    showlegend=True,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    ),
    hovermode="x unified"
)

fig.show()

FIG_TITLE = "IQR-Based Anomaly Detection"
PLOT_CAPTION = f"""
IQR-based anomaly detection uses the interquartile range (Q1=${Q1:.2f}, Q3=${Q3:.2f}, IQR=${IQR:.2f}) to define normal spending boundaries. The upper fence (${UPPER_BOUND:.2f}) and lower fence (${LOWER_BOUND:.2f}) are set at 1.5× IQR beyond Q1 and Q3 respectively, following standard statistical outlier detection conventions. The time series panel shows spending against these thresholds, with shaded regions indicating normal (teal) and caution (yellow) zones. The box plot confirms the spending distribution's central tendency and spread, while the histogram reveals the frequency distribution relative to IQR boundaries. This method is robust to non-normal distributions and complements the CI-based detection by focusing on the actual spending distribution rather than model predictions.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="IQR_ANOMALY_DETECTION.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 IQR-based anomaly detection uses the interquartile range (Q1=$665.70, Q3=$780.95, IQR=$115.25) to define normal spending
boundaries. The upper fence ($953.82) and lower fence ($492.83) are set at 1.5× IQR beyond Q1 and Q3 respectively, following
standard statistical outlier detection conventions. The time series panel shows spending against these thresholds, with shaded
regions indicating normal (teal) and caution (yellow) zones. The box plot confirms the spending distribution's central tendency
and spread, while the histogram reveals the frequency distribution relative to IQR boundaries. This method is robust to non-normal
distributions and complements the CI-based detection by focusing on the actual spending distribution rather than model
predictions.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\IQR_ANOMALY_DETECTION.png
✅ Registered component: IQR_ANOMALY_DETECTION.png with Title IQR-Based Anomaly Detection

In [141]:
# Report Management
CAPTION = f"""By applying the IQR method, we have established robust bounds for normal spending behavior based on historical data distribution. The calculated lower bound is {ACTUAL_IQR_LOWER_BOUND:.2f} and the upper bound is {ACTUAL_IQR_UPPER_BOUND:.2f}. Any actual monthly expense falling outside these bounds is flagged as an anomaly, indicating significant deviations from typical spending patterns. The months identified as anomalies based on IQR analysis are: {ANOMALIES_IQR_MONTH_STRING}.
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)

print("\n--------------------------------\n")

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="ANOMALY_DETECTION_IQR_SUMMARY_BODY_1"
)

By applying the IQR method, we have established robust bounds for normal spending behavior based on historical data distribution.
The calculated lower bound is 492.83 and the upper bound is 953.82. Any actual monthly expense falling outside these bounds is
flagged as an anomaly, indicating significant deviations from typical spending patterns. The months identified as anomalies based
on IQR analysis are: Dec 2023.

--------------------------------

In [142]:
# Moving Average Deviation
MA_WINDOW = 3
MA_THRESHOLD = 0.25
BACKTEST_RESULTS["MA 3 Months"] = BACKTEST_RESULTS["Actual"].rolling(window=MA_WINDOW, center=True).mean()

BACKTEST_RESULTS["MA Upper"] = BACKTEST_RESULTS["MA 3 Months"] * (1 + MA_THRESHOLD)
BACKTEST_RESULTS["MA Lower"] = BACKTEST_RESULTS["MA 3 Months"] * (1 - MA_THRESHOLD)

BACKTEST_RESULTS["MA Deviation"] = (np.abs(BACKTEST_RESULTS["Actual"] - BACKTEST_RESULTS["MA 3 Months"]) / BACKTEST_RESULTS["MA 3 Months"]) * 100

# Use 25% deviation as threshold (adjust based on your data)
MA_THRESHOLD = 0.25
BACKTEST_RESULTS["Anomaly MA"] = BACKTEST_RESULTS["MA Deviation"].abs() > MA_THRESHOLD

print(f"MA Deviation Method detected: {BACKTEST_RESULTS["Anomaly MA"].sum()} anomalies")
BACKTEST_RESULTS

MA Deviation Method detected: 10 anomalies

,Actual,Forecast,Lower CI,Upper CI,Anomaly CI,Error,Z-Score,Anomaly Z-Score,Anomaly IQR,MA 3 Months,MA Upper,MA Lower,MA Deviation,Anomaly MA
Date,,,,,,,,,,,,,,
2023-01-01,793.4,570.422461,370.264168,770.580753,True,222.977539,1.666697,True,False,NaN,NaN,NaN,NaN,False
2023-02-01,776.8,734.616595,525.843324,943.389866,False,42.183405,0.346171,False,False,781.166667,976.458333,585.875,0.558993,True
2023-03-01,773.3,745.396845,538.902096,951.891595,False,27.903155,0.241867,False,False,767.300000,959.125000,575.475,0.781963,True
2023-04-01,751.8,744.097518,540.058238,948.136798,False,7.702482,0.094321,False,False,727.366667,909.208333,545.525,3.359149,True
2023-05-01,657.0,746.697945,545.205558,948.190332,False,-89.697945,0.617095,False,False,699.166667,873.958333,524.375,6.030989,True
2023-06-01,688.7,687.016441,486.173555,887.859328,False,1.683559,0.050358,False,False,675.400000,844.250000,506.550,1.969203,True
2023-07-01,680.5,710.332455,511.897992,908.766917,False,-29.832455,0.179836,False,False,730.900000,913.625000,548.175,6.895608,True
2023-08-01,823.5,690.187530,493.874577,886.500483,False,133.312470,1.011780,False,False,690.333333,862.916667,517.750,19.290198,True
2023-09-01,567.0,763.856349,565.854412,961.858286,False,-196.856349,1.399784,False,False,736.133333,920.166667,552.100,22.975910,True
2023-10-01,817.9,647.806507,444.533566,851.079448,False,170.093493,1.280430,False,False,684.500000,855.625000,513.375,19.488678,True
2023-11-01,668.6,753.561752,546.787360,960.336145,False,-84.961752,0.582502,False,False,647.133333,808.916667,485.350,3.317194,True
2023-12-01,454.9,721.940146,515.926585,927.953707,True,-267.040146,1.912408,True,True,NaN,NaN,NaN,NaN,False

In [143]:
# Anomaly MA
ANOMALIES_MA = BACKTEST_RESULTS[BACKTEST_RESULTS["Anomaly MA"] == True]
ANOMALIES_MA["Month Year Label"] = ANOMALIES_MA.index.strftime("%b %Y")

ANOMALIES_MA_MONTH_LIST = []
for i in ANOMALIES_MA["Month Year Label"]:
    ANOMALIES_MA_MONTH_LIST.append(i)

ANOMALIES_MA_MONTH_STRING = ", ".join(ANOMALIES_MA_MONTH_LIST)
if ANOMALIES_MA_MONTH_STRING == "":
    ANOMALIES_MA_MONTH_STRING = "None"

ANOMALIES_MA_MONTH_STRING

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\887939041.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

'Feb 2023, Mar 2023, Apr 2023, May 2023, Jun 2023, Jul 2023, Aug 2023, Sep 2023, Oct 2023, Nov 2023'

In [144]:
fig = make_subplots(
    rows=2, 
    cols=1,
    subplot_titles=(
        f"Moving Average ({MA_WINDOW}-Month) with Deviation Bands",
        f"Percentage Deviation from {MA_WINDOW}-Month Moving Average"
    ),
    vertical_spacing=0.12,
    row_heights=[0.6, 0.4]
)

# Main Chart with MA and bands (TOP)
# Add MA envelope bands
fig.add_trace(
    go.Scatter(
        x=BACKTEST_RESULTS.index,
        y=BACKTEST_RESULTS["MA Upper"],
        mode="lines",
        name=f"Upper Band (+{MA_THRESHOLD*100:.0f}%)",
        line=dict(color="rgba(255, 107, 107, 0.5)", width=1, dash="dash"),
        showlegend=True
    ),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(
        x=BACKTEST_RESULTS.index,
        y=BACKTEST_RESULTS["MA Lower"],
        mode="lines",
        name=f"Lower Band (-{MA_THRESHOLD*100:.0f}%)",
        fill="tonexty",
        fillcolor="rgba(76, 205, 196, 0.15)",
        line=dict(color="rgba(255, 107, 107, 0.5)", width=1, dash="dash"),
        showlegend=True
    ),
    row=1, col=1
)

# Actual spending
fig.add_trace(
    go.Scatter(
        x=BACKTEST_RESULTS.index,
        y=BACKTEST_RESULTS["Actual"],
        mode="lines+markers",
        name="Actual Spending",
        line=dict(color="#7FADDC", width=2),
        marker=dict(size=5)
    ),
    row=1, col=1
)

# Moving average line
fig.add_trace(
    go.Scatter(
        x=BACKTEST_RESULTS.index,
        y=BACKTEST_RESULTS["MA 3 Months"],
        mode="lines",
        name=f"{MA_WINDOW}-Month MA",
        line=dict(color="#FFA500", width=2.5)
    ),
    row=1, col=1
)

# MA anomalies (if any)
MA_ANOMALIES = BACKTEST_RESULTS[BACKTEST_RESULTS["Anomaly MA"]]
if len(MA_ANOMALIES) > 0:
    fig.add_trace(
        go.Scatter(
            x=MA_ANOMALIES.index,
            y=MA_ANOMALIES["Actual"],
            mode="markers",
            name="MA Anomalies",
            marker=dict(
                size=14,
                color="#FF6B6B",
                symbol="x",
                line=dict(width=2, color="white")
            )
        ),
        row=1, col=1
    )
else:
    # Add annotation showing no anomalies
    fig.add_annotation(
        x=0.5, y=0.85,
        xref="x domain", yref="y domain",
        text="✓ No MA Anomalies Detected",
        showarrow=False,
        font=dict(color="#4ECDC4", size=13),
        bgcolor="rgba(76, 205, 196, 0.15)",
        bordercolor="#4ECDC4",
        borderwidth=1,
        row=1, col=1
    )

# Deviation % Chart (BOTTOM)
# Color bars by direction
bar_colors = [
    "#FF6B6B" if x > 0 else "#4ECDC4" 
    for x in BACKTEST_RESULTS["MA Deviation"].fillna(0)
]

fig.add_trace(
    go.Bar(
        x=BACKTEST_RESULTS.index,
        y=BACKTEST_RESULTS["MA Deviation"],
        name="% Deviation",
        marker=dict(color=bar_colors),
        showlegend=False
    ),
    row=2, col=1
)

# Add threshold lines on deviation chart
fig.add_hline(
    y=MA_THRESHOLD * 100,
    line_dash="dash",
    line_color="#FF6B6B",
    annotation_text=f"+{MA_THRESHOLD*100:.0f}% threshold",
    annotation_font_color="#FF6B6B",
    row=2, col=1
)
fig.add_hline(
    y=-MA_THRESHOLD * 100,
    line_dash="dash",
    line_color="#FF6B6B",
    annotation_text=f"-{MA_THRESHOLD*100:.0f}% threshold",
    annotation_font_color="#FF6B6B",
    row=2, col=1
)
fig.add_hline(
    y=0,
    line_dash="solid",
    line_color="gray",
    row=2, col=1
)

# Update axes
fig.update_xaxes(title_text="Date", row=1, col=1)
fig.update_yaxes(title_text="Expenses ($)", row=1, col=1)

fig.update_xaxes(title_text="Date", row=2, col=1)
fig.update_yaxes(title_text="Deviation (%)", row=2, col=1)

fig.update_layout(
    title=dict(
        text=f"Moving Average ({MA_WINDOW}-Month) Anomaly Detection",
        x=0.5,
        xanchor="center",
        font=dict(size=20)
    ),
    height=800,
    width=1000,
    template="plotly_dark",
    showlegend=True,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    ),
    hovermode="x unified"
)

fig.show()

FIG_TITLE = f"Moving Average ({MA_WINDOW}-Month) Anomaly Detection"
PLOT_CAPTION = f"""
Moving average anomaly detection uses a {MA_WINDOW}-month centered rolling average to establish dynamic spending baselines, adapting to gradual trend changes rather than using fixed static thresholds. The teal shaded envelope represents the ±{MA_THRESHOLD*100:.0f}% normal deviation band around the moving average. The absence of MA-detected anomalies is a meaningful finding: while CI-based and Z-score methods flagged isolated monthly spikes, the moving average confirms these were brief, self-correcting deviations rather than sustained trend shifts. This distinction is important for financial monitoring as it suggests the anomalies did not alter the underlying spending trajectory. The deviation panel (bottom) quantifies month-to-month volatility relative to the rolling baseline, providing additional context for spending rhythm and consistency.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="MA_ANOMALY_DETECTION.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Moving average anomaly detection uses a 3-month centered rolling average to establish dynamic spending baselines, adapting to
gradual trend changes rather than using fixed static thresholds. The teal shaded envelope represents the ±25% normal deviation
band around the moving average. The absence of MA-detected anomalies is a meaningful finding: while CI-based and Z-score methods
flagged isolated monthly spikes, the moving average confirms these were brief, self-correcting deviations rather than sustained
trend shifts. This distinction is important for financial monitoring as it suggests the anomalies did not alter the underlying
spending trajectory. The deviation panel (bottom) quantifies month-to-month volatility relative to the rolling baseline, providing
additional context for spending rhythm and consistency.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\MA_ANOMALY_DETECTION.png
✅ Registered component: MA_ANOMALY_DETECTION.png with Title Moving Average (3-Month) Anomaly Detection

In [145]:
# Report Management
CAPTION = f"""By analyzing deviations from the 3-month moving average, we have identified months where spending significantly diverged from recent trends. A threshold of {MA_THRESHOLD*100:.0f}% deviation effectively captures these anomalies, highlighting periods of unusual spending behavior. The months identified as anomalies based on moving average deviation analysis are: {ANOMALIES_MA_MONTH_STRING}.
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)

print("\n--------------------------------\n")

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="ANOMALY_DETECTION_MA_SUMMARY_BODY_1"
)

By analyzing deviations from the 3-month moving average, we have identified months where spending significantly diverged from
recent trends. A threshold of 25% deviation effectively captures these anomalies, highlighting periods of unusual spending
behavior. The months identified as anomalies based on moving average deviation analysis are: Feb 2023, Mar 2023, Apr 2023, May
2023, Jun 2023, Jul 2023, Aug 2023, Sep 2023, Oct 2023, Nov 2023.

--------------------------------

In [146]:
# Consensus: Anomaly if detected by at least 2 methods
BACKTEST_RESULTS["Detection Count"] = (
    BACKTEST_RESULTS["Anomaly CI"].astype(int) +
    BACKTEST_RESULTS["Anomaly Z-Score"].astype(int) +
    BACKTEST_RESULTS["Anomaly IQR"].astype(int) +
    BACKTEST_RESULTS["Anomaly MA"].astype(int)
)
BACKTEST_RESULTS["Anomaly Consensus"] = BACKTEST_RESULTS["Detection Count"] >= 2

print("\n" + "="*50)
print("ANOMALY DETECTION SUMMARY")
print("="*50)
print(f"CI-based (primary):        {BACKTEST_RESULTS["Anomaly CI"].sum():2d} anomalies")
print(f"Z-score (>{Z_SCORES_THRESHOLD}):          {BACKTEST_RESULTS["Anomaly Z-Score"].sum():2d} anomalies")
print(f"IQR-based:                 {BACKTEST_RESULTS["Anomaly IQR"].sum():2d} anomalies")
print(f"MA Deviation (>{MA_THRESHOLD*100:.0f}%):      {BACKTEST_RESULTS["Anomaly MA"].sum():2d} anomalies")
print(f"Consensus (≥2 methods):    {BACKTEST_RESULTS["Anomaly Consensus"].sum():2d} anomalies")
print("="*50)

==================================================
ANOMALY DETECTION SUMMARY
==================================================
CI-based (primary):         2 anomalies
Z-score (>1.5):           2 anomalies
IQR-based:                  1 anomalies
MA Deviation (>25%):      10 anomalies
Consensus (≥2 methods):     2 anomalies
==================================================

In [147]:
# Anomaly Consensus
ANOMALIES_CONSENSUS = BACKTEST_RESULTS[BACKTEST_RESULTS["Anomaly Consensus"] == True]
ANOMALIES_CONSENSUS["Month Year Label"] = ANOMALIES_CONSENSUS.index.strftime("%b %Y")

ANOMALIES_CONSENSUS_MONTH_LIST = []
for i in ANOMALIES_CONSENSUS["Month Year Label"]:
    ANOMALIES_CONSENSUS_MONTH_LIST.append(i)

ANOMALIES_CONSENSUS_MONTH_STRING = ", ".join(ANOMALIES_CONSENSUS_MONTH_LIST)
if ANOMALIES_CONSENSUS_MONTH_STRING == "":
    ANOMALIES_CONSENSUS_MONTH_STRING = "None"

ANOMALIES_CONSENSUS_MONTH_STRING

C:\Users\Ferdy Arianto Wiyogo\AppData\Local\Temp\ipykernel_27236\763629208.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

'Jan 2023, Dec 2023'

In [148]:
# Extract anomalous months with details
ANOMALIES_DETAILED = BACKTEST_RESULTS[BACKTEST_RESULTS["Anomaly Consensus"] == True].copy()

if len(ANOMALIES_DETAILED) > 0:
    # Calculate additional metrics
    ANOMALIES_DETAILED["Deviation PCT"] = (
        (ANOMALIES_DETAILED["Actual"] - ANOMALIES_DETAILED["Forecast"]) / 
        ANOMALIES_DETAILED["Forecast"] * 100
    )
    
    ANOMALIES_DETAILED["CI Width"] = (
        ANOMALIES_DETAILED["Upper CI"] - ANOMALIES_DETAILED["Lower CI"]
    )
    
    ANOMALIES_DETAILED["Type"] = ANOMALIES_DETAILED["Error"].apply(
        lambda x: "Overspending" if x > 0 else "Underspending"
    )
    
    ANOMALIES_DETAILED["Severity"] = ANOMALIES_DETAILED["Deviation PCT"].apply(
        lambda x: "Severe" if abs(x) > 30 else "Moderate" if abs(x) > 15 else "Mild"
    )
    
    # Create summary display
    ANOMALY_DISPLAY = ANOMALIES_DETAILED[[
        "Actual", "Forecast", "Lower CI", "Upper CI", 
        "Error", "Deviation PCT", "Type", "Severity"
    ]].round(2)
    
    # Reset index to show dates
    ANOMALY_DISPLAY.index = ANOMALY_DISPLAY.index.strftime("%B %Y")
    
    print("\n" + "="*100)
    print("DETECTED ANOMALIES - DETAILED BREAKDOWN")
    print("="*100)
    print(ANOMALY_DISPLAY.to_string())
    print("="*100)
    
    # Create interactive table
    fig = go.Figure(data=[go.Table(
        header=dict(
            values=[
                "<b>Date</b>", "<b>Actual</b>", "<b>Forecast</b>", 
                "<b>Lower CI</b>", "<b>Upper CI</b>", "<b>Error</b>", 
                "<b>Deviation %</b>", "<b>Type</b>", "<b>Severity</b>"
            ],
            fill_color="#1e293b",
            align="left",
            font=dict(color="white", size=11)
        ),
        cells=dict(
            values=[
                ANOMALY_DISPLAY.index,
                ANOMALY_DISPLAY["Actual"],
                ANOMALY_DISPLAY["Forecast"],
                ANOMALY_DISPLAY["Lower CI"],
                ANOMALY_DISPLAY["Upper CI"],
                ANOMALY_DISPLAY["Error"],
                [f"{x:.1f}%" for x in ANOMALY_DISPLAY["Deviation PCT"]],
                ANOMALY_DISPLAY["Type"],
                ANOMALY_DISPLAY["Severity"]
            ],
            fill_color=[
                "#334155",  # Date
                ["#ef4444" if t == "Overspending" else "#22c55e" for t in ANOMALY_DISPLAY["Type"]],  # Actual (colored)
                "#475569",  # Forecast
                "#475569",  # Lower CI
                "#475569",  # Upper CI
                ["#ef4444" if e > 0 else "#22c55e" for e in ANOMALY_DISPLAY["Error"]],  # Error (colored)
                "#475569",  # Deviation %
                "#475569",  # Type
                ["#ef4444" if s == "Severe" else "#f59e0b" if s == "Moderate" else "#22c55e" 
                 for s in ANOMALY_DISPLAY["Severity"]]  # Severity (colored)
            ],
            align="left",
            font=dict(color="white", size=10),
            height=35
        )
    )])
    
    fig.update_layout(
        title=dict(
            text="Detected Anomalies - Detailed Analysis",
            x=0.5,
            xanchor="center",
            font=dict(size=18)
        ),
        height=max(250, 100 * len(ANOMALY_DISPLAY) + 100),  # Dynamic height based on rows
        width=1000,
        template="plotly_dark"
    )
    
    fig.show()
    
    FIG_TITLE = "Detected Anomalies - Detailed Analysis"
    PLOT_CAPTION = """
Comprehensive breakdown of detected expense anomalies during back-testing period. Each anomalous month is characterized by actual spending, model forecast, confidence interval bounds, deviation magnitude, and classified by type (overspending vs underspending) and severity (mild/moderate/severe). Color coding highlights overspending (red) and underspending (green) patterns. The error column quantifies dollar deviation from forecast, while deviation percentage enables comparison across different spending levels. This granular analysis facilitates investigation into root causes and informs budget adjustment strategies.
    """
    
    PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
    print(PLOT_CAPTION_WRAPPED)
    
    print("\n--------------------------------\n")
    
    SAVE_PLOT_AND_REGISTER(
        fig,
        FILENAME="ANOMALY_DETECTION_SUMMARY_TABLE.png",
        TITLE=FIG_TITLE,
        CAPTION=PLOT_CAPTION_WRAPPED
    )

else:
    print("\nNo anomalies detected in backtesting period.")

====================================================================================================
DETECTED ANOMALIES - DETAILED BREAKDOWN
====================================================================================================
               Actual  Forecast  Lower CI  Upper CI   Error  Deviation PCT           Type Severity
Date
January 2023    793.4    570.42    370.26    770.58  222.98          39.09   Overspending   Severe
December 2023   454.9    721.94    515.93    927.95 -267.04         -36.99  Underspending   Severe
====================================================================================================

 Comprehensive breakdown of detected expense anomalies during back-testing period. Each anomalous month is characterized by actual
spending, model forecast, confidence interval bounds, deviation magnitude, and classified by type (overspending vs underspending)
and severity (mild/moderate/severe). Color coding highlights overspending (red) and underspending (green) patterns. The error
column quantifies dollar deviation from forecast, while deviation percentage enables comparison across different spending levels.
This granular analysis facilitates investigation into root causes and informs budget adjustment strategies.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\ANOMALY_DETECTION_SUMMARY_TABLE.png
✅ Registered component: ANOMALY_DETECTION_SUMMARY_TABLE.png with Title Detected Anomalies - Detailed Analysis

In [149]:
# Report Management
CAPTION = f"""Anomalies confirmed by multiple detection methods provide higher confidence in their validity. By requiring consensus from at least two independent techniques, we mitigate the risk of false positives inherent in any single method. This multi-faceted approach ensures that flagged anomalies represent genuine deviations from expected spending patterns, warranting further investigation. The months identified as consensus anomalies are: {ANOMALIES_CONSENSUS_MONTH_STRING}.
"""

CAPTION_WRAPPED = textwrap.fill(CAPTION, width=130)
print(CAPTION_WRAPPED)

print("\n--------------------------------\n")

REGISTER_REPORT_COMPONENT(
    TITLE=None,
    CONTENT=CAPTION_WRAPPED,
    TYPE="text",
    HEADING="normal",
    BODY="point",
    PATH=None,
    REPORTING_TAG="ANOMALY_DETECTION_CONSENSUS_SUMMARY_BODY_1"
)

Anomalies confirmed by multiple detection methods provide higher confidence in their validity. By requiring consensus from at
least two independent techniques, we mitigate the risk of false positives inherent in any single method. This multi-faceted
approach ensures that flagged anomalies represent genuine deviations from expected spending patterns, warranting further
investigation. The months identified as consensus anomalies are: Jan 2023, Dec 2023.

--------------------------------

In [150]:
# Define alert system based on SARIMA CI + historical patterns
HISTORICAL_MEAN = MONTHLY_EXPENSES_TIME_SERIES_COPY.mean()
HISTORICAL_STD = MONTHLY_EXPENSES_TIME_SERIES_COPY.std()

# Get average CI width from backtesting as basis for thresholds
AVG_CI_WIDTH = (BACKTEST_RESULTS["Upper CI"] - BACKTEST_RESULTS["Lower CI"]).mean()
AVG_FORECAST = BACKTEST_RESULTS["Forecast"].mean()

# Define four-tier alert thresholds
ALERT_SYSTEM = {
    "GREEN": {
        "Label": "Normal",
        "Condition": "Within 95% CI",
        "Upper Multiplier": 1.0,   # At CI boundary
        "Lower Multiplier": 1.0,
        "Color": "#4CAF50",
        "Action": "No action needed"
    },
    "YELLOW": {
        "Label": "Caution",
        "Condition": "1.0x - 1.25x beyond CI",
        "Upper Multiplier": 1.25,
        "Lower Multiplier": 1.25,
        "Color": "#FFC107",
        "Action": "Monitor closely, review spending categories"
    },
    "ORANGE": {
        "Label": "Warning",
        "Condition": "1.25x - 1.5x beyond CI",
        "Upper Multiplier": 1.50,
        "Lower Multiplier": 1.50,
        "Color": "#FF9800",
        "Action": "Investigate causes, reduce discretionary spending"
    },
    "RED": {
        "Label": "Critical",
        "Condition": "Beyond 1.5x CI",
        "Upper Multiplier": None,   # Anything beyond orange
        "Lower Multiplier": None,
        "Color": "#F44336",
        "Action": "URGENT - Immediate budget review required"
    }
}

def GET_ALERT_THRESHOLDS(FORECAST_MEAN, CI_LOWER, CI_UPPER):
    """Calculate all four alert tier boundaries for a given forecast."""
    CI_HALF_WIDTH_UPPER = CI_UPPER - FORECAST_MEAN
    CI_HALF_WIDTH_LOWER = FORECAST_MEAN - CI_LOWER

    return {
        # Upper thresholds
        "Upper Green": CI_UPPER,
        "Upper Yellow": CI_UPPER + (CI_HALF_WIDTH_UPPER * 0.25),
        "Upper Orange": CI_UPPER + (CI_HALF_WIDTH_UPPER * 0.50),
        # Lower thresholds
        "Lower Green": CI_LOWER,
        "Lower Yellow": CI_LOWER - (CI_HALF_WIDTH_LOWER * 0.25),
        "Lower Orange": CI_LOWER - (CI_HALF_WIDTH_LOWER * 0.50),
        # Reference
        "Forecast": FORECAST_MEAN,
        "CI Upper": CI_UPPER,
        "CI Lower": CI_LOWER
    }

def CLASSIFY_ALERT(actual, thresholds):
    """Classify a spending value into an alert tier."""
    if thresholds["Lower Green"] <= actual <= thresholds["Upper Green"]:
        return "GREEN"
    elif thresholds["Lower Yellow"] <= actual <= thresholds["Upper Yellow"]:
        return "YELLOW"
    elif thresholds["Lower Orange"] <= actual <= thresholds["Upper Orange"]:
        return "ORANGE"
    else:
        return "RED"

# Visualize the threshold system conceptually
# Use the average forecast as a reference point
REF_THRESHOLDS = GET_ALERT_THRESHOLDS(
    AVG_FORECAST,
    AVG_FORECAST - AVG_CI_WIDTH / 2,
    AVG_FORECAST + AVG_CI_WIDTH / 2
)

# Build threshold definition table
THRESHOLD_TABLE = pd.DataFrame({
    "Alert Level": ["🟢 GREEN", "🟡 YELLOW", "🟠 ORANGE", "🔴 RED"],
    "Label": ["Normal", "Caution", "Warning", "Critical"],
    "Condition": [
        "Within 95% CI",
        "1.0x - 1.25x beyond CI",
        "1.25x - 1.5x beyond CI",
        "Beyond 1.5x CI"
    ],
    "Upper Bound ($)": [
        f"${REF_THRESHOLDS["Upper Green"]:.2f}",
        f"${REF_THRESHOLDS["Upper Yellow"]:.2f}",
        f"${REF_THRESHOLDS["Upper Orange"]:.2f}",
        "Above orange"
    ],
    "Lower Bound ($)": [
        f"${REF_THRESHOLDS["Lower Green"]:.2f}",
        f"${REF_THRESHOLDS["Lower Yellow"]:.2f}",
        f"${REF_THRESHOLDS["Lower Orange"]:.2f}",
        "Below orange"
    ],
    "Recommended Action": [
        details["Action"] for details in ALERT_SYSTEM.values()
    ]
})

# Plot threshold definition as visual table
fig = go.Figure(data=[go.Table(
    header=dict(
        values=[f"<b>{col}</b>" for col in THRESHOLD_TABLE.columns],
        fill_color="#1e293b",
        align="left",
        font=dict(color="white", size=12),
        height=35
    ),
    cells=dict(
        values=[THRESHOLD_TABLE[col] for col in THRESHOLD_TABLE.columns],
        fill_color=[
            ["#1a3a2a", "#3a3010", "#3a2010", "#3a1010"],  # Alert Level
            ["#1a3a2a", "#3a3010", "#3a2010", "#3a1010"],  # Label
            "#334155",  # Condition
            "#334155",  # Upper
            "#334155",  # Lower
            "#334155",  # Action
        ],
        align="left",
        font=dict(
            color=[
                ["#4CAF50", "#FFC107", "#FF9800", "#F44336"],
                ["#4CAF50", "#FFC107", "#FF9800", "#F44336"],
                "white", "white", "white", "white"
            ],
            size=11
        ),
        height=35
    )
)])

fig.update_layout(
    title=dict(
        text="Early Warning System - Alert Threshold Definitions",
        x=0.5,
        xanchor="center",
        font=dict(size=18)
    ),
    height=450,
    template="plotly_dark"
)

fig.show()

FIG_TITLE = "Early Warning System - Alert Threshold Definitions"
PLOT_CAPTION = f"""
The early warning system defines four alert tiers based on SARIMA confidence interval boundaries and historical spending patterns. The GREEN zone represents normal spending within the 95% confidence interval, requiring no intervention. YELLOW caution alerts trigger when spending deviates 1.0-1.25x beyond CI bounds, signalling the need for closer monitoring. ORANGE warnings indicate moderate anomalies (1.25-1.5x beyond CI) requiring active investigation and corrective action. RED critical alerts fire for severe deviations beyond 1.5x CI boundaries, demanding immediate budget review. Reference thresholds are calculated from the average forecast of ${AVG_FORECAST:.2f} and average CI width of ${AVG_CI_WIDTH:.2f}, with dynamic thresholds recalculated monthly based on current SARIMA forecasts.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)
print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="EARLY_WARNING_THRESHOLD_DEFINITION.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The early warning system defines four alert tiers based on SARIMA confidence interval boundaries and historical spending
patterns. The GREEN zone represents normal spending within the 95% confidence interval, requiring no intervention. YELLOW caution
alerts trigger when spending deviates 1.0-1.25x beyond CI bounds, signalling the need for closer monitoring. ORANGE warnings
indicate moderate anomalies (1.25-1.5x beyond CI) requiring active investigation and corrective action. RED critical alerts fire
for severe deviations beyond 1.5x CI boundaries, demanding immediate budget review. Reference thresholds are calculated from the
average forecast of $709.66 and average CI width of $405.10, with dynamic thresholds recalculated monthly based on current SARIMA
forecasts.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\EARLY_WARNING_THRESHOLD_DEFINITION.png
✅ Registered component: EARLY_WARNING_THRESHOLD_DEFINITION.png with Title Early Warning System - Alert Threshold Definitions

In [151]:
# Retrospective Alert Simulation
# Apply alert classification to all backtesting results
RETROSPECTIVE_ALERTS = BACKTEST_RESULTS.copy()

# Calculate thresholds and classify each month
ALERT_LEVELS = []
for idx, row in RETROSPECTIVE_ALERTS.iterrows():
    THRESHOLDS = GET_ALERT_THRESHOLDS(
        row["Forecast"],
        row["Lower CI"],
        row["Upper CI"]
    )
    LEVEL = CLASSIFY_ALERT(row["Actual"], THRESHOLDS)
    ALERT_LEVELS.append(LEVEL)

RETROSPECTIVE_ALERTS["Alert Level"] = ALERT_LEVELS

# Map colors
COLOR_MAP = {
    "GREEN": "#4CAF50",
    "YELLOW": "#FFC107",
    "ORANGE": "#FF9800",
    "RED": "#F44336"
}
RETROSPECTIVE_ALERTS["Alert Color"] = RETROSPECTIVE_ALERTS["Alert Level"].map(COLOR_MAP)

# Alert summary statistics
ALERT_COUNTS = RETROSPECTIVE_ALERTS["Alert Level"].value_counts()

print("="*60)
print("RETROSPECTIVE ALERT SIMULATION SUMMARY")
print("="*60)
for level in ["GREEN", "YELLOW", "ORANGE", "RED"]:
    COUNT = ALERT_COUNTS.get(level, 0)
    PCT = COUNT / len(RETROSPECTIVE_ALERTS) * 100
    print(f"  {level:8s}: {COUNT:3d} months ({PCT:5.1f}%)")
print(f"  {"TOTAL":8s}: {len(RETROSPECTIVE_ALERTS):3d} months")
print("="*60)

# Visualization
fig = make_subplots(
    rows=3, cols=1,
    subplot_titles=(
        "Retrospective Alert Timeline (2018-2023)",
        "Monthly Alert Level",
        "Alert Distribution"
    ),
    vertical_spacing=0.10,
    row_heights=[0.50, 0.25, 0.25],
    specs=[
        [{"type": "scatter"}],
        [{"type": "scatter"}],
        [{"type": "bar"}]
    ]
)

# Main time series with color-coded alert zones (TOP)
# Add CI shading
fig.add_trace(
    go.Scatter(
        x=RETROSPECTIVE_ALERTS.index,
        y=RETROSPECTIVE_ALERTS["Upper CI"],
        mode="lines",
        line=dict(width=0),
        showlegend=False,
        hoverinfo="skip"
    ),
    row=1, 
    col=1
)

fig.add_trace(
    go.Scatter(
        x=RETROSPECTIVE_ALERTS.index,
        y=RETROSPECTIVE_ALERTS["Lower CI"],
        mode="lines",
        fill="tonexty",
        fillcolor="rgba(76, 175, 80, 0.15)",
        line=dict(width=0),
        name="Normal Zone (95% CI)",
        showlegend=True
    ),
    row=1, 
    col=1
)

# Actual spending line
fig.add_trace(
    go.Scatter(
        x=RETROSPECTIVE_ALERTS.index,
        y=RETROSPECTIVE_ALERTS["Actual"],
        mode="lines",
        name="Actual Spending",
        line=dict(color="#7FADDC", width=2),
        showlegend=True
    ),
    row=1, 
    col=1
)

# Forecast line
fig.add_trace(
    go.Scatter(
        x=RETROSPECTIVE_ALERTS.index,
        y=RETROSPECTIVE_ALERTS["Forecast"],
        mode="lines",
        name="Forecast",
        line=dict(color="#E8B4B8", width=1.5, dash="dash"),
        showlegend=True
    ),
    row=1, 
    col=1
)

# Color coded alert markers
for level, color in COLOR_MAP.items():
    LEVEL_DATA = RETROSPECTIVE_ALERTS[RETROSPECTIVE_ALERTS["Alert Level"] == level]
    if len(LEVEL_DATA) > 0 and level != "GREEN":
        fig.add_trace(
            go.Scatter(
                x=LEVEL_DATA.index,
                y=LEVEL_DATA["Actual"],
                mode="markers",
                name=f"{level} Alert",
                marker=dict(
                    size=10 if level == "YELLOW" else 12 if level == "ORANGE" else 14,
                    color=color,
                    symbol="circle",
                    line=dict(width=1.5, color="white")
                ),
                showlegend=True
            ),
            row=1, 
            col=1
        )

# Alert level timeline (MIDDLE)
# Numeric mapping for y-axis
LEVEL_MAP = {"GREEN": 1, "YELLOW": 2, "ORANGE": 3, "RED": 4}
RETROSPECTIVE_ALERTS["Alert Numeric"] = RETROSPECTIVE_ALERTS["Alert Level"].map(LEVEL_MAP)

fig.add_trace(
    go.Scatter(
        x=RETROSPECTIVE_ALERTS.index,
        y=RETROSPECTIVE_ALERTS["Alert Numeric"],
        mode="markers+lines",
        marker=dict(
            color=RETROSPECTIVE_ALERTS["Alert Color"],
            size=10,
            line=dict(width=1, color="white")
        ),
        line=dict(color="rgba(255,255,255,0.2)", width=1),
        showlegend=False,
        hovertemplate="%{x}<br>Alert: %{text}<extra></extra>",
        text=RETROSPECTIVE_ALERTS["Alert Level"]
    ),
    row=2, 
    col=1
)

# Update y-axis for alert timeline
fig.update_yaxes(
    tickvals=[1, 2, 3, 4],
    ticktext=["GREEN", "YELLOW", "ORANGE", "RED"],
    # tickfont=dict(
    #     color=["#4CAF50", "#FFC107", "#FF9800", "#F44336"]
    # ),
    row=2, 
    col=1
)

# Alert distribution bar chart (BOTTOM)
ALERT_ORDER = ["GREEN", "YELLOW", "ORANGE", "RED"]
ALERT_COUNTS_ORDERED = [ALERT_COUNTS.get(level, 0) for level in ALERT_ORDER]
ALERT_COLORS_ORDERED = [COLOR_MAP[level] for level in ALERT_ORDER]

fig.add_trace(
    go.Bar(
        x=ALERT_ORDER,
        y=ALERT_COUNTS_ORDERED,
        marker=dict(color=ALERT_COLORS_ORDERED),
        text=ALERT_COUNTS_ORDERED,
        textposition="outside",
        textfont=dict(color="white"),
        showlegend=False
    ),
    row=3, 
    col=1
)

# Update axes
fig.update_xaxes(title_text="Date", row=2, col=1)
fig.update_yaxes(title_text="Expenses ($)", row=1, col=1)
fig.update_yaxes(title_text="Alert Level", row=2, col=1)
fig.update_xaxes(title_text="Alert Level", row=3, col=1)
fig.update_yaxes(title_text="Count", row=3, col=1)

fig.update_layout(
    title=dict(
        text="Early Warning System - Retrospective Alert Simulation",
        x=0.5,
        xanchor="center",
        font=dict(size=20)
    ),
    height=1200,
    width=1000,
    template="plotly_dark",
    showlegend=True,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    ),
    hovermode="x unified"
)

fig.show()

FIG_TITLE = "Early Warning System - Retrospective Alert Simulation (2018-2023)"
PLOT_CAPTION = f"""
Retrospective simulation of the early warning system across the full 2018-2023 period demonstrates its practical effectiveness. The main panel overlays actual spending against SARIMA forecasts and confidence intervals, with color-coded markers indicating alert levels triggered each month. The alert timeline (middle) provides a clear temporal view of system status, revealing the frequency and clustering of elevated alerts. The distribution chart (bottom) summarises alert frequency: the majority of months fall within the GREEN normal zone, validating overall spending predictability. YELLOW and ORANGE alerts highlight months requiring closer attention, while RED critical alerts correspond directly to the consensus anomalies identified in section 3.1. This retrospective validation confirms the early warning system would have successfully flagged genuine anomalies while maintaining a low false positive rate across the observation period.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)
print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="EARLY_WARNING_RETROSPECTIVE_SIMULATION.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

============================================================
RETROSPECTIVE ALERT SIMULATION SUMMARY
============================================================
  GREEN   :  10 months ( 83.3%)
  YELLOW  :   1 months (  8.3%)
  ORANGE  :   1 months (  8.3%)
  RED     :   0 months (  0.0%)
  TOTAL   :  12 months
============================================================

 Retrospective simulation of the early warning system across the full 2018-2023 period demonstrates its practical effectiveness.
The main panel overlays actual spending against SARIMA forecasts and confidence intervals, with color-coded markers indicating
alert levels triggered each month. The alert timeline (middle) provides a clear temporal view of system status, revealing the
frequency and clustering of elevated alerts. The distribution chart (bottom) summarises alert frequency: the majority of months
fall within the GREEN normal zone, validating overall spending predictability. YELLOW and ORANGE alerts highlight months requiring
closer attention, while RED critical alerts correspond directly to the consensus anomalies identified in section 3.1. This
retrospective validation confirms the early warning system would have successfully flagged genuine anomalies while maintaining a
low false positive rate across the observation period.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\EARLY_WARNING_RETROSPECTIVE_SIMULATION.png
✅ Registered component: EARLY_WARNING_RETROSPECTIVE_SIMULATION.png with Title Early Warning System - Retrospective Alert Simulation (2018-2023)

In [152]:
# Generate forward forecast using fitted SARIMA model
SARIMA_FORECAST = FITTED_MODEL.get_forecast(steps=FORECAST_HORIZON)
SARIMA_FORECAST_MEAN = SARIMA_FORECAST.predicted_mean
SARIMA_FORECAST_CI = SARIMA_FORECAST.conf_int()

# Build forward forecast dataframe
FORWARD_SARIMA = pd.DataFrame({
    "Forecast": SARIMA_FORECAST_MEAN,
    "Lower CI": SARIMA_FORECAST_CI.iloc[:, 0],
    "Upper CI": SARIMA_FORECAST_CI.iloc[:, 1]
})

# Calculate alert thresholds for each future month
FORWARD_ALERTS = []
for idx, row in FORWARD_SARIMA.iterrows():
    THRESHOLDS = GET_ALERT_THRESHOLDS(
        row["Forecast"],
        row["Lower CI"],
        row["Upper CI"]
    )
    FORWARD_ALERTS.append({
        "Date": idx,
        "Forecast": row["Forecast"],
        "Lower CI": row["Lower CI"],
        "Upper CI": row["Upper CI"],
        "Upper Yellow": THRESHOLDS["Upper Yellow"],
        "Upper Orange": THRESHOLDS["Upper Orange"],
        "Lower Yellow": THRESHOLDS["Lower Yellow"],
        "Lower Orange": THRESHOLDS["Lower Orange"]
    })

FORWARD_ALERT_DF = pd.DataFrame(FORWARD_ALERTS).set_index("Date")

# Visualization
fig = make_subplots(
    rows=2, cols=1,
    subplot_titles=(
        "12-Month Forward Forecast with Alert Zones",
        "Forecast Uncertainty by Month"
    ),
    vertical_spacing=0.12,
    row_heights=[0.65, 0.35]
)

# Historical context (last 12 months)
HISTORICAL_TAIL = BACKTEST_RESULTS.tail(12)

# Forward forecast with alert zones (TOP)
# Historical context
fig.add_trace(
    go.Scatter(
        x=HISTORICAL_TAIL.index,
        y=HISTORICAL_TAIL["Actual"],
        mode="lines+markers",
        name="Historical (Last 12 Months)",
        line=dict(color="#7FADDC", width=2),
        marker=dict(size=5)
    ),
    row=1, col=1
)

# Add vertical line separating history from forecast
LAST_HISTORICAL_DATE = HISTORICAL_TAIL.index[-1]
fig.add_vrect(
    x0="LAST_HISTORICAL_DATE", 
    x1="LAST_HISTORICAL_DATE",
    fillcolor="white", 
    opacity=0.3,
    layer="below", 
    line_width=0,
    annotation_text="Forecast Start",
    annotation_position="top left", 
    annotation_textangle = 90
)

# RED zone (critical)
fig.add_trace(
    go.Scatter(
        x=FORWARD_ALERT_DF.index,
        y=FORWARD_ALERT_DF["Upper Orange"],
        mode="lines",
        line=dict(width=0),
        showlegend=False,
        hoverinfo="skip"
    ),
    row=1, col=1
)
fig.add_trace(
    go.Scatter(
        x=FORWARD_ALERT_DF.index,
        y=[FORWARD_ALERT_DF["Upper Orange"].max() * 1.3] * len(FORWARD_ALERT_DF),
        mode="lines",
        fill="tonexty",
        fillcolor="rgba(244, 67, 54, 0.15)",
        line=dict(width=0),
        name="🔴 Critical Zone",
        showlegend=True,
        hoverinfo="skip"
    ),
    row=1, col=1
)

# ORANGE zone
fig.add_trace(
    go.Scatter(
        x=FORWARD_ALERT_DF.index,
        y=FORWARD_ALERT_DF["Upper Yellow"],
        mode="lines",
        line=dict(width=0),
        showlegend=False,
        hoverinfo="skip"
    ),
    row=1, col=1
)
fig.add_trace(
    go.Scatter(
        x=FORWARD_ALERT_DF.index,
        y=FORWARD_ALERT_DF["Upper Orange"],
        mode="lines",
        fill="tonexty",
        fillcolor="rgba(255, 152, 0, 0.20)",
        line=dict(width=0),
        name="🟠 Warning Zone",
        showlegend=True,
        hoverinfo="skip"
    ),
    row=1, col=1
)

# YELLOW zone
fig.add_trace(
    go.Scatter(
        x=FORWARD_ALERT_DF.index,
        y=FORWARD_ALERT_DF["Upper CI"],
        mode="lines",
        line=dict(width=0),
        showlegend=False,
        hoverinfo="skip"
    ),
    row=1, col=1
)
fig.add_trace(
    go.Scatter(
        x=FORWARD_ALERT_DF.index,
        y=FORWARD_ALERT_DF["Upper Yellow"],
        mode="lines",
        fill="tonexty",
        fillcolor="rgba(255, 193, 7, 0.20)",
        line=dict(width=0),
        name="🟡 Caution Zone",
        showlegend=True,
        hoverinfo="skip"
    ),
    row=1, col=1
)

# GREEN zone (CI band)
fig.add_trace(
    go.Scatter(
        x=FORWARD_ALERT_DF.index,
        y=FORWARD_ALERT_DF["Upper CI"],
        mode="lines",
        line=dict(width=0),
        showlegend=False,
        hoverinfo="skip"
    ),
    row=1, col=1
)
fig.add_trace(
    go.Scatter(
        x=FORWARD_ALERT_DF.index,
        y=FORWARD_ALERT_DF["Lower CI"],
        mode="lines",
        fill="tonexty",
        fillcolor="rgba(76, 175, 80, 0.20)",
        line=dict(width=0),
        name="🟢 Normal Zone",
        showlegend=True,
        hoverinfo="skip"
    ),
    row=1, col=1
)

# Forecast line
fig.add_trace(
    go.Scatter(
        x=FORWARD_ALERT_DF.index,
        y=FORWARD_ALERT_DF["Forecast"],
        mode="lines+markers",
        name="Forecast",
        line=dict(color="#E8B4B8", width=2.5, dash="dash"),
        marker=dict(size=6)
    ),
    row=1, col=1
)

# Uncertainty (CI width) by month (BOTTOM)
FORWARD_ALERT_DF["CI Width"] = (
    FORWARD_ALERT_DF["Upper CI"] - FORWARD_ALERT_DF["Lower CI"]
)

fig.add_trace(
    go.Bar(
        x=FORWARD_ALERT_DF.index,
        y=FORWARD_ALERT_DF["CI Width"],
        name="CI Width (Uncertainty)",
        marker=dict(
            color=FORWARD_ALERT_DF["CI Width"],
            colorscale="RdYlGn_r",
            showscale=True,
            colorbar=dict(title="CI Width ($)", x=1.02, len=0.35, y=0.15)
        ),
        showlegend=False
    ),
    row=2, col=1
)

# Update axes
fig.update_xaxes(title_text="Date", row=1, col=1)
fig.update_yaxes(title_text="Expenses ($)", row=1, col=1)
fig.update_xaxes(title_text="Forecast Month", row=2, col=1)
fig.update_yaxes(title_text="CI Width ($)", row=2, col=1)

fig.update_layout(
    title=dict(
        text=f"Early Warning System - {FORECAST_HORIZON}-Month Forward Monitoring Framework",
        x=0.5,
        xanchor="center",
        font=dict(size=20)
    ),
    height=900,
    width=1000,
    template="plotly_dark",
    showlegend=True,
    legend=dict(
        orientation="v",
        yanchor="top",
        y=0.98,
        xanchor="left",
        x=1.05
    ),
    hovermode="x unified"
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
The forward-looking monitoring framework extends the SARIMA model"s predictive capability into a {FORECAST_HORIZON}-month horizon beyond the observation period, establishing actionable alert zones for future expense monitoring. Four color-coded zones define expected spending ranges: GREEN (normal, within {(1 - SARIMA_CI_ALPHA)*100}% CI), YELLOW (caution, 1.0-1.25x beyond CI), ORANGE (warning, 1.25-1.5x beyond CI), and RED (critical, beyond 1.5x CI). The historical context panel (last {FORECAST_HORIZON} months) anchors the forecast to recent spending patterns, providing continuity between observed and predicted behavior. The uncertainty panel (bottom) reveals how forecast confidence degrades over the 12-month horizon - wider confidence intervals in later months reflect increasing uncertainty, which is expected and should inform more conservative budget buffers for longer planning horizons. This framework provides a practical monthly monitoring guide: at each month-end, compare actual spending to the forecast zones to determine if intervention is required.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)
print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="EARLY_WARNING_FORWARD_MONITORING.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The forward-looking monitoring framework extends the SARIMA model"s predictive capability into a 24-month horizon beyond the
observation period, establishing actionable alert zones for future expense monitoring. Four color-coded zones define expected
spending ranges: GREEN (normal, within 95.0% CI), YELLOW (caution, 1.0-1.25x beyond CI), ORANGE (warning, 1.25-1.5x beyond CI),
and RED (critical, beyond 1.5x CI). The historical context panel (last 24 months) anchors the forecast to recent spending
patterns, providing continuity between observed and predicted behavior. The uncertainty panel (bottom) reveals how forecast
confidence degrades over the 12-month horizon - wider confidence intervals in later months reflect increasing uncertainty, which
is expected and should inform more conservative budget buffers for longer planning horizons. This framework provides a practical
monthly monitoring guide: at each month-end, compare actual spending to the forecast zones to determine if intervention is
required.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\EARLY_WARNING_FORWARD_MONITORING.png
✅ Registered component: EARLY_WARNING_FORWARD_MONITORING.png with Title Early Warning System - 24-Month Forward Monitoring Framework

In [153]:
SUMMARY_DATA = {
    'Component': [
        'Alert Thresholds',
        'Retrospective Validation',
        'Forward Forecast Horizon',
        'Detection Methods Used',
        'False Positive Rate',
        'True Anomalies Confirmed'
    ],
    'Detail': [
        '4-tier: Green / Yellow / Orange / Red',
        f'Applied across full 2018-2023 period ({len(RETROSPECTIVE_ALERTS)} months)',
        f'{FORECAST_HORIZON} months beyond observation period',
        'CI-based + Z-score consensus',
        f"{(ALERT_COUNTS.get('YELLOW', 0) / len(RETROSPECTIVE_ALERTS) * 100):.1f}% caution alerts (non-critical)",
        f"{ALERT_COUNTS.get('RED', 0)} RED alerts matching {BACKTEST_RESULTS['Anomaly Consensus'].sum()} consensus anomalies"
    ]
}

SUMMARY_DF = pd.DataFrame(SUMMARY_DATA)

fig = go.Figure(data=[go.Table(
    header=dict(
        values=['<b>Component</b>', '<b>Detail</b>'],
        fill_color='#1e293b',
        align='left',
        font=dict(color='white', size=12),
        height=35
    ),
    cells=dict(
        values=[SUMMARY_DF['Component'], SUMMARY_DF['Detail']],
        fill_color=['#334155', '#475569'],
        align='left',
        font=dict(color='white', size=11),
        height=35
    )
)])

fig.update_layout(
    title=dict(
        text="Early Warning System - Summary",
        x=0.5,
        xanchor='center',
        font=dict(size=18)
    ),
    height=350,
    template="plotly_dark"
)

fig.show()

FIG_TITLE = fig.layout.title.text if fig.layout.title else "Untitled Plot"
PLOT_CAPTION = f"""
Summary of the early warning system components, validation results, and forward monitoring framework designed to support proactive expense management beyond the 2018-2023 observation period.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)
print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="EARLY_WARNING_SUMMARY_TABLE.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Summary of the early warning system components, validation results, and forward monitoring framework designed to support
proactive expense management beyond the 2018-2023 observation period.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\EARLY_WARNING_SUMMARY_TABLE.png
✅ Registered component: EARLY_WARNING_SUMMARY_TABLE.png with Title Early Warning System - Summary

<h2>Forecast Error Analysis</h2>
<p>Why does the model fail and what can be derived from it?</p>
<p> --> To study the errors from the model.</p>

In [154]:
# Report Management
SUBSECTION_TITLE = "Forecast Error Analysis"
SUBSECTION_CAPTION = "To study the errors from the model"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="PREDICTIVE_AND_PRESCRIPTIVE_FORECAST_ERROR_ANALYSIS"
)

✅ Registered component: PREDICTIVE_AND_PRESCRIPTIVE_FORECAST_ERROR_ANALYSIS with Title Forecast Error Analysis

In [155]:
# Use backtest results for error analysis
ERROR_ANALYSIS = BACKTEST_RESULTS.copy()

# Calculate comprehensive error metrics
ERROR_METRICS = {
    # Bias (systematic over/under prediction)
    "MEAN_ERROR": ERROR_ANALYSIS["Error"].mean(),
    "MEDIAN_ERROR": ERROR_ANALYSIS["Error"].median(),
    
    # Variance (consistency)
    "STD_ERROR": ERROR_ANALYSIS["Error"].std(),
    "VARIANCE": ERROR_ANALYSIS["Error"].var(),
    
    # Accuracy
    "MAE": ERROR_ANALYSIS["Error"].abs().mean(),
    "RMSE": np.sqrt((ERROR_ANALYSIS["Error"]**2).mean()),
    "MAPE": (ERROR_ANALYSIS["Error"].abs() / ERROR_ANALYSIS["Actual"]).mean() * 100,
    
    # Distribution
    "SKEWNESS": ERROR_ANALYSIS["Error"].skew(),
    "KURTOSIS": ERROR_ANALYSIS["Error"].kurtosis(),
    
    # Extremes
    "MAX_OVERPREDICTION": ERROR_ANALYSIS["Error"].min(),  # Negative = underspent vs prediction
    "MAX_UNDERPREDICTION": ERROR_ANALYSIS["Error"].max()  # Positive = overspent vs prediction
}

ERROR_METRICS

{'MEAN_ERROR': np.float64(-5.21104528738375),
 'MEDIAN_ERROR': np.float64(4.693020499129318),
 'STD_ERROR': np.float64(142.99853157139026),
 'VARIANCE': np.float64(20448.580031573896),
 'MAE': np.float64(106.18706259412208),
 'RMSE': np.float64(137.00980508195963),
 'MAPE': np.float64(16.63021733802703),
 'SKEWNESS': np.float64(-0.22537264377634716),
 'KURTOSIS': np.float64(-0.20057606365065617),
 'MAX_OVERPREDICTION': np.float64(-267.04014589337874),
 'MAX_UNDERPREDICTION': np.float64(222.9775394790904)}

In [156]:
# Bias Classification
if abs(ERROR_METRICS["MEAN_ERROR"]) < ERROR_METRICS["STD_ERROR"] * 0.1:
    BIAS_ASSESSMENT = "UNBIASED - No systematic over/under prediction"
elif ERROR_METRICS["MEAN_ERROR"] > 0:
    BIAS_ASSESSMENT = f"POSITIVE BIAS - Tends to underpredict by ${ERROR_METRICS['MEAN_ERROR']:.2f}/month"
else:
    BIAS_ASSESSMENT = f"NEGATIVE BIAS - Tends to overpredict by ${abs(ERROR_METRICS['MEAN_ERROR']):.2f}/month"

In [157]:
 # Coefficient of Variation
CV = ERROR_METRICS['STD_ERROR'] / ERROR_METRICS['MAE'] 
if CV < 0.5:
    CONSISTENCY = "HIGH - Errors are consistent in magnitude"
elif CV < 1.0:
    CONSISTENCY = "MODERATE - Some variability in error magnitude"
else:
    CONSISTENCY = "LOW - High variability in prediction accuracy"

In [158]:
print("="*70)
print("FORECAST ERROR DECOMPOSITION")
print("="*70)
print(f"\n📊 BIAS ANALYSIS")
print(f"  Mean Error:           ${ERROR_METRICS['MEAN_ERROR']:>8.2f}")
print(f"  Median Error:         ${ERROR_METRICS['MEDIAN_ERROR']:>8.2f}")
print(f"  Assessment:           {BIAS_ASSESSMENT}")

print(f"\n📈 VARIANCE ANALYSIS")
print(f"  Std Deviation:        ${ERROR_METRICS['STD_ERROR']:>8.2f}")
print(f"  Coefficient of Var:   {CV:>8.2f}")
print(f"  Consistency:          {CONSISTENCY}")

print(f"\n🎯 ACCURACY METRICS")
print(f"  MAE:                  ${ERROR_METRICS['MAE']:>8.2f}")
print(f"  RMSE:                 ${ERROR_METRICS['RMSE']:>8.2f}")
print(f"  MAPE:                 {ERROR_METRICS['MAPE']:>8.1f}%")

print(f"\n📉 DISTRIBUTION SHAPE")
print(f"  Skewness:             {ERROR_METRICS['SKEWNESS']:>8.2f} ", end="")
if abs(ERROR_METRICS['SKEWNESS']) < 0.5:
    print("(Symmetric)")
elif ERROR_METRICS['SKEWNESS'] > 0:
    print("(Right-skewed: more large positive errors)")
else:
    print("(Left-skewed: more large negative errors)")
    
print(f"  Kurtosis:             {ERROR_METRICS['KURTOSIS']:>8.2f} ", end="")
if abs(ERROR_METRICS['KURTOSIS']) < 0.5:
    print("(Normal tails)")
elif ERROR_METRICS['KURTOSIS'] > 0:
    print("(Heavy tails: more extremes than normal)")
else:
    print("(Light tails: fewer extremes)")

print(f"\n⚠️  EXTREME ERRORS")
print(f"  Largest Overspend:    ${ERROR_METRICS['MAX_UNDERPREDICTION']:>8.2f}")
print(f"  Largest Underspend:   ${abs(ERROR_METRICS['MAX_OVERPREDICTION']):>8.2f}")

print("="*70)

======================================================================
FORECAST ERROR DECOMPOSITION
======================================================================

📊 BIAS ANALYSIS
  Mean Error:           $   -5.21
  Median Error:         $    4.69
  Assessment:           UNBIASED - No systematic over/under prediction

📈 VARIANCE ANALYSIS
  Std Deviation:        $  143.00
  Coefficient of Var:       1.35
  Consistency:          LOW - High variability in prediction accuracy

🎯 ACCURACY METRICS
  MAE:                  $  106.19
  RMSE:                 $  137.01
  MAPE:                     16.6%

📉 DISTRIBUTION SHAPE
  Skewness:                -0.23 (Symmetric)
  Kurtosis:                -0.20 (Normal tails)

⚠️  EXTREME ERRORS
  Largest Overspend:    $  222.98
  Largest Underspend:   $  267.04
======================================================================

In [159]:
# Visualize error decomposition
fig = make_subplots(
    rows=2, 
    cols=2,
    subplot_titles=(
        "Error Distribution (Bias Check)",
        "Error vs Forecast (Heteroscedasticity)",
        "Cumulative Error Over Time",
        "Error Magnitude by Month"
    ),
    vertical_spacing=0.15,
    horizontal_spacing=0.12
)

# Error histogram with normal overlay (TOP LEFT)
fig.add_trace(
    go.Histogram(
        x=ERROR_ANALYSIS["Error"],
        nbinsx=25,
        name="Error Distribution",
        marker=dict(color="#7FADDC"),
        showlegend=False
    ),
    row=1, 
    col=1
)

# Add normal distribution overlay
MU = ERROR_METRICS["MEAN_ERROR"]
SIGMA = ERROR_METRICS["STD_ERROR"]
X_RANGE = np.linspace(
    ERROR_ANALYSIS["Error"].min(),
    ERROR_ANALYSIS["Error"].max(),
    100
)

Y_NORMAL = stats.norm.pdf(X_RANGE, MU, SIGMA) * len(ERROR_ANALYSIS) * \
           (ERROR_ANALYSIS["Error"].max() - ERROR_ANALYSIS["Error"].min()) / 25

fig.add_trace(
    go.Scatter(
        x=X_RANGE,
        y=Y_NORMAL,
        mode="lines",
        name="Normal Distribution",
        line=dict(color="#FF6B6B", width=3, dash="dash")
    ),
    row=1, 
    col=1
)

# Add mean line
fig.add_vline(
    x=MU,
    line_dash="solid",
    line_color="#FFA500",
    annotation_text=f"Mean: ${MU:.2f}",
    row=1, col=1
)

# Error vs Forecast (heteroscedasticity check) (TOP RIGHT)
fig.add_trace(
    go.Scatter(
        x=ERROR_ANALYSIS["Forecast"],
        y=ERROR_ANALYSIS["Error"],
        mode="markers",
        marker=dict(
            size=8,
            color=ERROR_ANALYSIS["Error"],
            colorscale="RdYlGn_r",
            showscale=True,
            colorbar=dict(title="Error ($)", x=1.15, len=0.45, y=0.75)
        ),
        showlegend=False
    ),
    row=1, 
    col=2
)

# Add zero line
fig.add_hline(
    y=0, 
    line_dash="dash", 
    line_color="gray", 
    row=1, 
    col=2
)

# Add regression line
Z = np.polyfit(ERROR_ANALYSIS["Forecast"], ERROR_ANALYSIS["Error"], 1)
P = np.poly1d(Z)
fig.add_trace(
    go.Scatter(
        x=ERROR_ANALYSIS["Forecast"],
        y=P(ERROR_ANALYSIS["Forecast"]),
        mode="lines",
        name="Trend",
        line=dict(color="#4ECDC4", width=2, dash="dot"),
        showlegend=False
    ),
    row=1, col=2
)

# Cumulative error (BOTTOM LEFT)
ERROR_ANALYSIS["Cumulative Error"] = ERROR_ANALYSIS["Error"].cumsum()

fig.add_trace(
    go.Scatter(
        x=ERROR_ANALYSIS.index,
        y=ERROR_ANALYSIS["Cumulative Error"],
        mode="lines",
        fill="tozeroy",
        name="Cumulative Error",
        line=dict(color="#7FADDC", width=2),
        fillcolor="rgba(124, 173, 220, 0.3)",
        showlegend=False
    ),
    row=2, col=1
)

fig.add_hline(y=0, line_dash="dash", line_color="gray", row=2, col=1)

# 4. Error magnitude over time (BOTTOM RIGHT)
ERROR_ANALYSIS["Abs Error"] = ERROR_ANALYSIS["Error"].abs()

# Color by whether it"s over or under prediction
colors = ["#FF6B6B" if e > 0 else "#4ECDC4" for e in ERROR_ANALYSIS["Error"]]

fig.add_trace(
    go.Bar(
        x=ERROR_ANALYSIS.index,
        y=ERROR_ANALYSIS["Abs Error"],
        marker=dict(color=colors),
        showlegend=False
    ),
    row=2, col=2
)

# Update axes
fig.update_xaxes(title_text="Error ($)", row=1, col=1)
fig.update_yaxes(title_text="Frequency", row=1, col=1)

fig.update_xaxes(title_text="Forecast ($)", row=1, col=2)
fig.update_yaxes(title_text="Error ($)", row=1, col=2)

fig.update_xaxes(title_text="Date", row=2, col=1)
fig.update_yaxes(title_text="Cumulative Error ($)", row=2, col=1)

fig.update_xaxes(title_text="Date", row=2, col=2)
fig.update_yaxes(title_text="Absolute Error ($)", row=2, col=2)

fig.update_layout(
    title=dict(
        text="Forecast Error Decomposition Analysis",
        x=0.5,
        xanchor="center",
        font=dict(size=20)
    ),
    height=900,
    width=1000,
    template="plotly_dark",
    showlegend=True
)

fig.show()

FIG_TITLE = "Forecast Error Decomposition Analysis"
PLOT_CAPTION = f"""
Comprehensive error decomposition reveals the SARIMA model"s prediction characteristics and failure modes. The error distribution (top-left) shows {BIAS_ASSESSMENT.lower()}, with mean error of ${ERROR_METRICS["MEAN_ERROR"]:.2f} and standard deviation of ${ERROR_METRICS["STD_ERROR"]:.2f}. Deviation from the normal curve indicates the presence of outlier predictions. The heteroscedasticity plot (top-right) examines whether forecast accuracy varies with spending level - a flat trend around zero suggests consistent accuracy across all magnitudes, while slope indicates systematic patterns. The cumulative error chart (bottom-left) tracks total prediction drift over time, revealing whether errors compound or self-correct. The magnitude timeline (bottom-right) identifies when the model struggles most, with red bars indicating overspending (underprediction) and teal bars showing underspending (overprediction). Error skewness of {ERROR_METRICS["SKEWNESS"]:.2f} and kurtosis of {ERROR_METRICS["KURTOSIS"]:.2f} characterize the distribution"s shape and tail behavior.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="FORECAST_ERROR_ANALYSIS_ERROR_DECOMPOSITION_ANALYSIS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Comprehensive error decomposition reveals the SARIMA model"s prediction characteristics and failure modes. The error distribution
(top-left) shows unbiased - no systematic over/under prediction, with mean error of $-5.21 and standard deviation of $143.00.
Deviation from the normal curve indicates the presence of outlier predictions. The heteroscedasticity plot (top-right) examines
whether forecast accuracy varies with spending level - a flat trend around zero suggests consistent accuracy across all
magnitudes, while slope indicates systematic patterns. The cumulative error chart (bottom-left) tracks total prediction drift over
time, revealing whether errors compound or self-correct. The magnitude timeline (bottom-right) identifies when the model struggles
most, with red bars indicating overspending (underprediction) and teal bars showing underspending (overprediction). Error skewness
of -0.23 and kurtosis of -0.20 characterize the distribution"s shape and tail behavior.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\FORECAST_ERROR_ANALYSIS_ERROR_DECOMPOSITION_ANALYSIS.png
✅ Registered component: FORECAST_ERROR_ANALYSIS_ERROR_DECOMPOSITION_ANALYSIS.png with Title Forecast Error Decomposition Analysis

In [160]:
# Seasonal & Temporal Error Patterns
ERROR_ANALYSIS["Month"] = ERROR_ANALYSIS.index.month
ERROR_ANALYSIS["Quarter"] = ERROR_ANALYSIS.index.quarter
ERROR_ANALYSIS["Year"] = ERROR_ANALYSIS.index.year
ERROR_ANALYSIS["Month Name"] = ERROR_ANALYSIS.index.strftime("%b")

ERROR_ANALYSIS

,Actual,Forecast,Lower CI,Upper CI,Anomaly CI,Error,Z-Score,Anomaly Z-Score,Anomaly IQR,MA 3 Months,...,MA Deviation,Anomaly MA,Detection Count,Anomaly Consensus,Cumulative Error,Abs Error,Month,Quarter,Year,Month Name
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-01,793.4,570.422461,370.264168,770.580753,True,222.977539,1.666697,True,False,NaN,...,NaN,False,2,True,222.977539,222.977539,1,1,2023,Jan
2023-02-01,776.8,734.616595,525.843324,943.389866,False,42.183405,0.346171,False,False,781.166667,...,0.558993,True,1,False,265.160945,42.183405,2,1,2023,Feb
2023-03-01,773.3,745.396845,538.902096,951.891595,False,27.903155,0.241867,False,False,767.300000,...,0.781963,True,1,False,293.064100,27.903155,3,1,2023,Mar
2023-04-01,751.8,744.097518,540.058238,948.136798,False,7.702482,0.094321,False,False,727.366667,...,3.359149,True,1,False,300.766582,7.702482,4,2,2023,Apr
2023-05-01,657.0,746.697945,545.205558,948.190332,False,-89.697945,0.617095,False,False,699.166667,...,6.030989,True,1,False,211.068637,89.697945,5,2,2023,May
2023-06-01,688.7,687.016441,486.173555,887.859328,False,1.683559,0.050358,False,False,675.400000,...,1.969203,True,1,False,212.752195,1.683559,6,2,2023,Jun
2023-07-01,680.5,710.332455,511.897992,908.766917,False,-29.832455,0.179836,False,False,730.900000,...,6.895608,True,1,False,182.919741,29.832455,7,3,2023,Jul
2023-08-01,823.5,690.187530,493.874577,886.500483,False,133.312470,1.011780,False,False,690.333333,...,19.290198,True,1,False,316.232211,133.312470,8,3,2023,Aug
2023-09-01,567.0,763.856349,565.854412,961.858286,False,-196.856349,1.399784,False,False,736.133333,...,22.975910,True,1,False,119.375862,196.856349,9,3,2023,Sep
2023-10-01,817.9,647.806507,444.533566,851.079448,False,170.093493,1.280430,False,False,684.500000,...,19.488678,True,1,False,289.469355,170.093493,10,4,2023,Oct
2023-11-01,668.6,753.561752,546.787360,960.336145,False,-84.961752,0.582502,False,False,647.133333,...,3.317194,True,1,False,204.507602,84.961752,11,4,2023,Nov
2023-12-01,454.9,721.940146,515.926585,927.953707,True,-267.040146,1.912408,True,True,NaN,...,NaN,False,3,True,-62.532543,267.040146,12,4,2023,Dec

In [161]:
# Calculate error statistics by month
MONTHLY_ERROR_STATS = ERROR_ANALYSIS.groupby("Month").agg({
    "Error": ["mean", "std", "count"],
    "Abs Error": "mean"
}).round(2)

MONTHLY_ERROR_STATS.columns = ["Mean Error", "Std Dev", "Count", "MAE"]
MONTHLY_ERROR_STATS

       Mean Error  Std Dev  Count     MAE
Month
1          222.98      NaN      1  222.98
2           42.18      NaN      1   42.18
3           27.90      NaN      1   27.90
4            7.70      NaN      1    7.70
5          -89.70      NaN      1   89.70
6            1.68      NaN      1    1.68
7          -29.83      NaN      1   29.83
8          133.31      NaN      1  133.31
9         -196.86      NaN      1  196.86
10         170.09      NaN      1  170.09
11         -84.96      NaN      1   84.96
12        -267.04      NaN      1  267.04

In [162]:
# Calculate by quarter
QUARTERLY_ERROR_STATS = ERROR_ANALYSIS.groupby("Quarter").agg({
    "Error": ["mean", "std"],
    "Abs Error": "mean"
}).round(2)

QUARTERLY_ERROR_STATS.columns = ["Mean Error", "Std Dev", "MAE"]
QUARTERLY_ERROR_STATS

         Mean Error  Std Dev     MAE
Quarter
1             97.69   108.74   97.69
2            -26.77    54.58   33.03
3            -31.13   165.09  120.00
4            -60.64   219.58  174.03

In [163]:
# Calculate by year
YEARLY_ERROR_STATS = ERROR_ANALYSIS.groupby("Year").agg({
    "Error": ["mean", "std"],
    "Abs Error": "mean",
    "Forecast": "mean",
    "Actual": "mean"
}).round(2)

YEARLY_ERROR_STATS.columns = ["Mean Error", "Std Dev", "MAE", "Avg Forecast", "Avg Actual"]
YEARLY_ERROR_STATS

      Mean Error  Std Dev     MAE  Avg Forecast  Avg Actual
Year
2023       -5.21    143.0  106.19        709.66      704.45

In [164]:
print("\n" + "="*70)
print("SEASONAL ERROR PATTERNS")
print("="*70)
print("\n📅 BY MONTH:")
print(MONTHLY_ERROR_STATS.to_string())

print("\n\n📊 BY QUARTER:")
print(QUARTERLY_ERROR_STATS.to_string())

print("\n\n📆 BY YEAR:")
print(YEARLY_ERROR_STATS.to_string())
print("="*70)

======================================================================
SEASONAL ERROR PATTERNS
======================================================================

📅 BY MONTH:
       Mean Error  Std Dev  Count     MAE
Month
1          222.98      NaN      1  222.98
2           42.18      NaN      1   42.18
3           27.90      NaN      1   27.90
4            7.70      NaN      1    7.70
5          -89.70      NaN      1   89.70
6            1.68      NaN      1    1.68
7          -29.83      NaN      1   29.83
8          133.31      NaN      1  133.31
9         -196.86      NaN      1  196.86
10         170.09      NaN      1  170.09
11         -84.96      NaN      1   84.96
12        -267.04      NaN      1  267.04


📊 BY QUARTER:
         Mean Error  Std Dev     MAE
Quarter
1             97.69   108.74   97.69
2            -26.77    54.58   33.03
3            -31.13   165.09  120.00
4            -60.64   219.58  174.03


📆 BY YEAR:
      Mean Error  Std Dev     MAE  Avg Forecast  Avg Actual
Year
2023       -5.21    143.0  106.19        709.66      704.45
======================================================================

In [165]:
WORST_MONTH = MONTHLY_ERROR_STATS["MAE"].idxmax()
WORST_QUARTER = QUARTERLY_ERROR_STATS["MAE"].idxmax()
WORST_YEAR = YEARLY_ERROR_STATS["MAE"].idxmax()

print(f"\n⚠️  PERIODS WITH HIGHEST ERRORS:")
print(f"  Worst Month:    {pd.to_datetime(f"2020-{WORST_MONTH}-01").strftime("%B")} (MAE: ${MONTHLY_ERROR_STATS.loc[WORST_MONTH, "MAE"]:.2f})")
print(f"  Worst Quarter:  Q{WORST_QUARTER} (MAE: ${QUARTERLY_ERROR_STATS.loc[WORST_QUARTER, "MAE"]:.2f})")
print(f"  Worst Year:     {WORST_YEAR} (MAE: ${YEARLY_ERROR_STATS.loc[WORST_YEAR, "MAE"]:.2f})")

⚠️  PERIODS WITH HIGHEST ERRORS:
  Worst Month:    December (MAE: $267.04)
  Worst Quarter:  Q4 (MAE: $174.03)
  Worst Year:     2023 (MAE: $106.19)

In [166]:
# Visualization
fig = make_subplots(
    rows=2, 
    cols=2,
    subplot_titles=(
        'Average Error by Month (Seasonal Pattern)',
        'Error Magnitude by Month (MAE)',
        'Average Error by Quarter',
        'Error Evolution Over Time'
    ),
    vertical_spacing=0.15,
    horizontal_spacing=0.12
)

# Mean error by month (TOP LEFT)
MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 
               'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
MONTHLY_MEANS = [MONTHLY_ERROR_STATS.loc[i, 'Mean Error'] if i in MONTHLY_ERROR_STATS.index else 0 
                 for i in range(1, 13)]
MONTHLY_COLORS = ['#FF6B6B' if e > 0 else '#4ECDC4' for e in MONTHLY_MEANS]

fig.add_trace(
    go.Bar(
        x=MONTH_NAMES,
        y=MONTHLY_MEANS,
        marker=dict(color=MONTHLY_COLORS),
        showlegend=False,
        text=[f'${e:.0f}' for e in MONTHLY_MEANS],
        textposition='outside'
    ),
    row=1, 
    col=1
)
fig.add_hline(y=0, line_dash="solid", line_color="gray", row=1, col=1)

# MAE by month (TOP RIGHT)
MONTHLY_MAES = [MONTHLY_ERROR_STATS.loc[i, 'MAE'] if i in MONTHLY_ERROR_STATS.index else 0 for i in range(1, 13)]

fig.add_trace(
    go.Bar(
        x=MONTH_NAMES,
        y=MONTHLY_MAES,
        marker=dict(color='#87A96B'),
        showlegend=False,
        text=[f'${m:.0f}' for m in MONTHLY_MAES],
        textposition='outside'
    ),
    row=1, 
    col=2
)

# Mean error by quarter (BOTTOM LEFT)
QUARTERS = [f'Q{i}' for i in range(1, 5)]
QUARTERLY_MEANS = [QUARTERLY_ERROR_STATS.loc[i, 'Mean Error'] if i in QUARTERLY_ERROR_STATS.index else 0 
                   for i in range(1, 5)]
QUARTERLY_COLORS = ['#FF6B6B' if e > 0 else '#4ECDC4' for e in QUARTERLY_MEANS]

fig.add_trace(
    go.Bar(
        x=QUARTERS,
        y=QUARTERLY_MEANS,
        marker=dict(color=QUARTERLY_COLORS),
        showlegend=False,
        text=[f'${e:.0f}' for e in QUARTERLY_MEANS],
        textposition='outside'
    ),
    row=2, 
    col=1
)
fig.add_hline(y=0, line_dash="solid", line_color="gray", row=2, col=1)

# Error evolution over backtesting period (BOTTOM RIGHT)
fig.add_trace(
    go.Scatter(
        x=ERROR_ANALYSIS.index,
        y=ERROR_ANALYSIS['Error'],
        mode='lines+markers',
        name='Error',
        line=dict(color='#7FADDC', width=2),
        marker=dict(size=6)
    ),
    row=2, 
    col=2
)

fig.add_trace(
    go.Scatter(
        x=ERROR_ANALYSIS.index,
        y=ERROR_ANALYSIS['Abs Error'],
        mode='lines+markers',
        name='Absolute Error',
        line=dict(color='#FFA500', width=2),
        marker=dict(size=6)
    ),
    row=2, 
    col=2
)

fig.add_hline(y=0, line_dash="solid", line_color="gray", row=2, col=2)

# Update axes
fig.update_xaxes(title_text="Month", row=1, col=1)
fig.update_yaxes(title_text="Mean Error ($)", row=1, col=1)

fig.update_xaxes(title_text="Month", row=1, col=2)
fig.update_yaxes(title_text="Std Dev ($)", row=1, col=2)

fig.update_xaxes(title_text="Quarter", row=2, col=1)
fig.update_yaxes(title_text="Mean Error ($)", row=2, col=1)

fig.update_xaxes(title_text="Year", row=2, col=2)
fig.update_yaxes(title_text="Error ($)", row=2, col=2)

fig.update_layout(
    title=dict(
        text="Temporal & Seasonal Error Pattern Analysis",
        x=0.5,
        xanchor='center',
        font=dict(size=20)
    ),
    height=900,
    width=1000,
    template="plotly_dark",
    showlegend=True
)

fig.show()

FIG_TITLE = "Temporal & Seasonal Error Pattern Analysis"
PLOT_CAPTION = f"""
Temporal decomposition of forecast errors reveals systematic patterns in model performance across the 2023 backtesting period. Monthly analysis (top-left) identifies seasonal forecasting challenges, with {pd.to_datetime(f'2020-{WORST_MONTH}-01').strftime('%B')} showing the highest directional bias. Mean Absolute Error by month (top-right) quantifies prediction accuracy regardless of direction, with {pd.to_datetime(f'2020-{WORST_MONTH}-01').strftime('%B')} exhibiting the largest average error magnitude (${MONTHLY_ERROR_STATS.loc[WORST_MONTH, 'MAE']:.2f}), potentially indicating seasonal spending patterns not fully captured by the SARIMA model. Quarterly aggregation (bottom-left) smooths noise to reveal broader seasonal trends, with Q{WORST_QUARTER} showing the most challenging forecast period. The error evolution timeline (bottom-right) tracks prediction performance chronologically throughout 2023, comparing signed errors (showing bias direction) against absolute errors (showing magnitude). Divergence between these lines indicates periods of consistent over or underprediction, while convergence suggests more symmetric error patterns. Horizontal dashed lines mark average error levels for reference.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="FORECAST_ERROR_ANALYSIS_TEMPORAL_SEASONAL_ERROR_PATTERNS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Temporal decomposition of forecast errors reveals systematic patterns in model performance across the 2023 backtesting period.
Monthly analysis (top-left) identifies seasonal forecasting challenges, with December showing the highest directional bias. Mean
Absolute Error by month (top-right) quantifies prediction accuracy regardless of direction, with December exhibiting the largest
average error magnitude ($267.04), potentially indicating seasonal spending patterns not fully captured by the SARIMA model.
Quarterly aggregation (bottom-left) smooths noise to reveal broader seasonal trends, with Q4 showing the most challenging forecast
period. The error evolution timeline (bottom-right) tracks prediction performance chronologically throughout 2023, comparing
signed errors (showing bias direction) against absolute errors (showing magnitude). Divergence between these lines indicates
periods of consistent over or underprediction, while convergence suggests more symmetric error patterns. Horizontal dashed lines
mark average error levels for reference.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\FORECAST_ERROR_ANALYSIS_TEMPORAL_SEASONAL_ERROR_PATTERNS.png
✅ Registered component: FORECAST_ERROR_ANALYSIS_TEMPORAL_SEASONAL_ERROR_PATTERNS.png with Title Temporal & Seasonal Error Pattern Analysis

In [167]:
# Error Attribution & Failure Analysis
ERROR_ANALYSIS["Error Category"] = pd.cut(
    ERROR_ANALYSIS["Abs Error"],
    bins=[0, 50, 100, 200, float("inf")],
    labels=["Small (<$50)", "Medium ($50-$100)", "Large ($100-$200)", "Extreme (>$200)"]
)

# Count errors by category
ERROR_CATEGORY_COUNTS = ERROR_ANALYSIS["Error Category"].value_counts().sort_index()

# Identify top error contributors
TOP_ERRORS = ERROR_ANALYSIS.nlargest(5, "Abs Error")[
    ["Actual", "Forecast", "Error", "Abs Error", "Lower CI", "Upper CI"]
].copy()

TOP_ERRORS["Deviation PCT"] = (TOP_ERRORS["Error"] / TOP_ERRORS["Forecast"] * 100).round(1)

# Calculate error concentration
TOTAL_SQUARED_ERROR = (ERROR_ANALYSIS["Error"] ** 2).sum()
ERROR_ANALYSIS["Squared Error"] = ERROR_ANALYSIS["Error"] ** 2
ERROR_ANALYSIS["Contribution PCT"] = (
    ERROR_ANALYSIS["Squared Error"] / TOTAL_SQUARED_ERROR * 100
).round(2)

# Find months contributing most to total error
TOP_CONTRIBUTORS = ERROR_ANALYSIS.nlargest(5, "Contribution PCT")[
    ["Actual", "Forecast", "Error", "Abs Error", "Contribution PCT"]
]

# Pareto analysis: What % of months account for 80% of total squared error?
ERROR_SORTED = ERROR_ANALYSIS.sort_values("Squared Error", ascending=False).copy()
ERROR_SORTED["Cumulative PCT"] = ERROR_SORTED["Contribution PCT"].cumsum()
MONTHS_FOR_80PCT = (ERROR_SORTED["Cumulative PCT"] <= 80).sum()
PARETO_PCT = MONTHS_FOR_80PCT / len(ERROR_ANALYSIS) * 100

print("="*70)
print("ERROR ATTRIBUTION & FAILURE ANALYSIS")
print("="*70)

print(f"\n📊 ERROR MAGNITUDE DISTRIBUTION:")
for category, count in ERROR_CATEGORY_COUNTS.items():
    pct = count / len(ERROR_ANALYSIS) * 100
    print(f"  {category:20s}: {count:2d} months ({pct:5.1f}%)")

print(f"\n🔥 TOP 5 LARGEST ERRORS:")
print("-" * 70)
for idx, row in TOP_ERRORS.iterrows():
    print(f"  {idx.strftime("%B %Y")}:")
    print(f"    Actual: ${row["Actual"]:.2f} | Forecast: ${row["Forecast"]:.2f}")
    print(f"    Error: ${row["Error"]:+.2f} ({row["Deviation PCT"]:+.1f}%)")
    print(f"    CI: [${row["Lower CI"]:.2f}, ${row["Upper CI"]:.2f}]")
    print()

print(f"📈 ERROR CONCENTRATION (Pareto Analysis):")
print(f"  {MONTHS_FOR_80PCT} months ({PARETO_PCT:.1f}%) account for 80% of total squared error")
print(f"  This suggests errors are {"concentrated" if PARETO_PCT < 50 else "distributed"} across the back-testing period")

print(f"\n🎯 TOP 5 ERROR CONTRIBUTORS (by squared error):")
print("-" * 70)
for idx, row in TOP_CONTRIBUTORS.iterrows():
    print(f"  {idx.strftime("%B %Y")}: {row["Contribution PCT"]:.1f}% of total error")
    print(f"    Error: ${row["Error"]:+.2f}, Abs Error: ${row["Abs Error"]:.2f}")

print("="*70)

======================================================================
ERROR ATTRIBUTION & FAILURE ANALYSIS
======================================================================

📊 ERROR MAGNITUDE DISTRIBUTION:
  Small (<$50)        :  5 months ( 41.7%)
  Medium ($50-$100)   :  2 months ( 16.7%)
  Large ($100-$200)   :  3 months ( 25.0%)
  Extreme (>$200)     :  2 months ( 16.7%)

🔥 TOP 5 LARGEST ERRORS:
----------------------------------------------------------------------
  December 2023:
    Actual: $454.90 | Forecast: $721.94
    Error: $-267.04 (-37.0%)
    CI: [$515.93, $927.95]

  January 2023:
    Actual: $793.40 | Forecast: $570.42
    Error: $+222.98 (+39.1%)
    CI: [$370.26, $770.58]

  September 2023:
    Actual: $567.00 | Forecast: $763.86
    Error: $-196.86 (-25.8%)
    CI: [$565.85, $961.86]

  October 2023:
    Actual: $817.90 | Forecast: $647.81
    Error: $+170.09 (+26.3%)
    CI: [$444.53, $851.08]

  August 2023:
    Actual: $823.50 | Forecast: $690.19
    Error: $+133.31 (+19.3%)
    CI: [$493.87, $886.50]

📈 ERROR CONCENTRATION (Pareto Analysis):
  3 months (25.0%) account for 80% of total squared error
  This suggests errors are concentrated across the back-testing period

🎯 TOP 5 ERROR CONTRIBUTORS (by squared error):
----------------------------------------------------------------------
  December 2023: 31.7% of total error
    Error: $-267.04, Abs Error: $267.04
  January 2023: 22.1% of total error
    Error: $+222.98, Abs Error: $222.98
  September 2023: 17.2% of total error
    Error: $-196.86, Abs Error: $196.86
  October 2023: 12.8% of total error
    Error: $+170.09, Abs Error: $170.09
  August 2023: 7.9% of total error
    Error: $+133.31, Abs Error: $133.31
======================================================================

In [168]:
# Visualization
fig = make_subplots(
    rows=2, 
    cols=2,
    subplot_titles=(
        "Error Magnitude Distribution",
        "Top 10 Errors by Month",
        "Cumulative Error Contribution (Pareto)",
        "Error Contribution by Month"
    ),
    vertical_spacing=0.15,
    horizontal_spacing=0.12,
    specs=[
        [{"type": "pie"}, {"type": "bar"}],
        [{"type": "scatter"}, {"type": "bar"}]
    ]
)

# Error category pie chart (TOP LEFT)
fig.add_trace(
    go.Pie(
        labels=ERROR_CATEGORY_COUNTS.index,
        values=ERROR_CATEGORY_COUNTS.values,
        marker=dict(colors=["#4ECDC4", "#FFA500", "#FF9800", "#F44336"]),
        textinfo="label+percent",
        hole=0.3
    ),
    row=1, 
    col=1
)

# Top 10 errors bar chart (TOP RIGHT)
TOP_10_ERRORS = ERROR_ANALYSIS.nlargest(10, "Abs Error").sort_values("Abs Error")
COLORS_TOP10 = ["#FF6B6B" if e > 0 else "#4ECDC4" for e in TOP_10_ERRORS["Error"]]

fig.add_trace(
    go.Bar(
        y=[idx.strftime("%b %Y") for idx in TOP_10_ERRORS.index],
        x=TOP_10_ERRORS["Abs Error"],
        orientation="h",
        marker=dict(color=COLORS_TOP10),
        showlegend=False,
        text=[f"${e:.0f}" for e in TOP_10_ERRORS["Abs Error"]],
        textposition="outside"
    ),
    row=1, 
    col=2
)

# Pareto chart - cumulative contribution (BOTTOM LEFT)
ERROR_SORTED_FOR_PLOT = ERROR_ANALYSIS.sort_values("Squared Error", ascending=False).copy()
ERROR_SORTED_FOR_PLOT["Cumulative PCT"] = ERROR_SORTED_FOR_PLOT["Contribution PCT"].cumsum()

fig.add_trace(
    go.Scatter(
        x=list(range(1, len(ERROR_SORTED_FOR_PLOT) + 1)),
        y=ERROR_SORTED_FOR_PLOT["Cumulative PCT"],
        mode="lines+markers",
        name="Cumulative %",
        line=dict(color="#7FADDC", width=3),
        marker=dict(size=6),
        fill="tozeroy",
        fillcolor="rgba(124, 173, 220, 0.3)"
    ),
    row=2, 
    col=1
)

# Add 80% reference line
fig.add_shape(
    type="line",
    x0=0,
    x1=len(ERROR_SORTED_FOR_PLOT),
    y0=80,
    y1=80,
    line=dict(color="#FF6B6B", width=2, dash="dash"),
    row=2,
    col=1
)

# Add annotation separately
fig.add_annotation(
    x=len(ERROR_SORTED_FOR_PLOT) * 0.95,
    y=80,
    text="80% threshold",
    showarrow=False,
    font=dict(color="#FF6B6B"),
    xanchor="right",
    row=2,
    col=1
)

# Add vertical line at the month that reaches 80%
fig.add_shape(
    type="line",
    x0=MONTHS_FOR_80PCT,
    x1=MONTHS_FOR_80PCT,
    y0=0,
    y1=100,
    line=dict(color="#FFA500", width=2, dash="dash"),
    row=2,
    col=1
)

# Add annotation
fig.add_annotation(
    x=MONTHS_FOR_80PCT,
    y=90,
    text=f"{MONTHS_FOR_80PCT} months",
    showarrow=False,
    font=dict(color="#FFA500"),
    row=2,
    col=1
)

# Contribution by month timeline (BOTTOM RIGHT)
contribution_colors = [
    "#F44336" if pct > 10 else "#FF9800" if pct > 5 else "#FFA500" if pct > 2 else "#4ECDC4"
    for pct in ERROR_ANALYSIS["Contribution PCT"]
]

fig.add_trace(
    go.Bar(
        x=ERROR_ANALYSIS.index,
        y=ERROR_ANALYSIS["Contribution PCT"],
        marker=dict(color=contribution_colors),
        showlegend=False,
        hovertemplate="%{x}<br>Contribution: %{y:.1f}%<extra></extra>"
    ),
    row=2, col=2
)

# Add mean line
MEAN_CONTRIBUTION = ERROR_ANALYSIS["Contribution PCT"].mean()

fig.add_shape(
    type="line",
    x0=ERROR_ANALYSIS.index.min(),
    x1=ERROR_ANALYSIS.index.max(),
    y0=MEAN_CONTRIBUTION,
    y1=MEAN_CONTRIBUTION,
    line=dict(color="#0096FF", width=2, dash="dash"),
    row=2,
    col=2
)

# Add annotation separately
fig.add_annotation(
    x=ERROR_ANALYSIS.index.max(),
    y=MEAN_CONTRIBUTION,
    text=f"Mean: {MEAN_CONTRIBUTION:.1f}%",
    showarrow=False,
    font=dict(color="#0096FF"),
    xanchor="right",
    row=2,
    col=2
)

# Update axes
fig.update_xaxes(title_text="Absolute Error ($)", row=1, col=2)

fig.update_xaxes(title_text="Month Rank (sorted by error)", row=2, col=1)
fig.update_yaxes(title_text="Cumulative % of Total Error", row=2, col=1)

fig.update_xaxes(title_text="Date", row=2, col=2)
fig.update_yaxes(title_text="% of Total Squared Error", row=2, col=2)

fig.update_layout(
    title=dict(
        text="Error Attribution & Failure Analysis",
        x=0.5,
        xanchor="center",
        font=dict(size=20)
    ),
    height=900,
    width=1000,
    template="plotly_dark",
    showlegend=False
)

fig.show()

FIG_TITLE = "Error Attribution & Failure Analysis"
PLOT_CAPTION = f"""
Error attribution analysis identifies which months and error types dominate model failures. The magnitude distribution (top-left) categorizes errors by severity, revealing that {ERROR_CATEGORY_COUNTS.get("Extreme (>$200)", 0)} months ({ERROR_CATEGORY_COUNTS.get("Extreme (>$200)", 0) / len(ERROR_ANALYSIS) * 100:.1f}%) experienced extreme errors exceeding $200. The top 10 errors chart (top-right) highlights the most challenging predictions, color-coded by direction (red=overspending, teal=underspending). The Pareto analysis (bottom-left) demonstrates error concentration: just {MONTHS_FOR_80PCT} months ({PARETO_PCT:.1f}% of the backtesting period) account for 80% of total squared error, indicating that prediction failures are {"concentrated in specific problematic months" if PARETO_PCT < 50 else "relatively distributed across the period"}. The contribution timeline (bottom-right) identifies when errors occurred, with darker red bars highlighting months that disproportionately contributed to overall model error. This concentration analysis guides where deeper investigation into spending anomalies or model limitations is most needed.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="FORECAST_ERROR_ANALYSIS_ERROR_ATTRIBUTION.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Error attribution analysis identifies which months and error types dominate model failures. The magnitude distribution (top-left)
categorizes errors by severity, revealing that 2 months (16.7%) experienced extreme errors exceeding $200. The top 10 errors chart
(top-right) highlights the most challenging predictions, color-coded by direction (red=overspending, teal=underspending). The
Pareto analysis (bottom-left) demonstrates error concentration: just 3 months (25.0% of the backtesting period) account for 80% of
total squared error, indicating that prediction failures are concentrated in specific problematic months. The contribution
timeline (bottom-right) identifies when errors occurred, with darker red bars highlighting months that disproportionately
contributed to overall model error. This concentration analysis guides where deeper investigation into spending anomalies or model
limitations is most needed.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\FORECAST_ERROR_ANALYSIS_ERROR_ATTRIBUTION.png
✅ Registered component: FORECAST_ERROR_ANALYSIS_ERROR_ATTRIBUTION.png with Title Error Attribution & Failure Analysis

In [169]:
# Analyze CI performance
ERROR_ANALYSIS['Within CI'] = (
    (ERROR_ANALYSIS['Actual'] >= ERROR_ANALYSIS['Lower CI']) &
    (ERROR_ANALYSIS['Actual'] <= ERROR_ANALYSIS['Upper CI'])
)

ERROR_ANALYSIS['CI Width'] = ERROR_ANALYSIS['Upper CI'] - ERROR_ANALYSIS['Lower CI']
ERROR_ANALYSIS['CI Width PCT'] = (
    ERROR_ANALYSIS['CI Width'] / ERROR_ANALYSIS['Forecast'] * 100
)

# Calculate coverage statistics
COVERAGE_RATE = ERROR_ANALYSIS['Within CI'].mean() * 100
EXPECTED_COVERAGE = 95  # 95% CI

# Violations breakdown
UPPER_VIOLATIONS = (ERROR_ANALYSIS['Actual'] > ERROR_ANALYSIS['Upper CI']).sum()
LOWER_VIOLATIONS = (ERROR_ANALYSIS['Actual'] < ERROR_ANALYSIS['Lower CI']).sum()
TOTAL_VIOLATIONS = UPPER_VIOLATIONS + LOWER_VIOLATIONS

# CI width statistics
AVG_CI_WIDTH = ERROR_ANALYSIS['CI Width'].mean()
MIN_CI_WIDTH = ERROR_ANALYSIS['CI Width'].min()
MAX_CI_WIDTH = ERROR_ANALYSIS['CI Width'].max()

# Find periods with narrowest and widest CIs
NARROWEST_CI_MONTH = ERROR_ANALYSIS.loc[ERROR_ANALYSIS['CI Width'].idxmin()]
WIDEST_CI_MONTH = ERROR_ANALYSIS.loc[ERROR_ANALYSIS['CI Width'].idxmax()]

# Analyze relationship between CI width and errors
ERROR_ANALYSIS['CI Violation'] = ~ERROR_ANALYSIS['Within CI']

print("="*70)
print("CONFIDENCE INTERVAL COVERAGE ANALYSIS")
print("="*70)

print(f"\n📊 COVERAGE STATISTICS:")
print(f"  Expected Coverage (95% CI):     {EXPECTED_COVERAGE:.1f}%")
print(f"  Actual Coverage:                {COVERAGE_RATE:.1f}%")
print(f"  Coverage {'meets' if COVERAGE_RATE >= 90 else 'below'} expectations")

print(f"\n⚠️  VIOLATIONS:")
print(f"  Total months outside CI:        {TOTAL_VIOLATIONS} ({TOTAL_VIOLATIONS/len(ERROR_ANALYSIS)*100:.1f}%)")
print(f"  Upper bound violations:         {UPPER_VIOLATIONS} (overspending)")
print(f"  Lower bound violations:         {LOWER_VIOLATIONS} (underspending)")

print(f"\n📏 CONFIDENCE INTERVAL WIDTH:")
print(f"  Average CI Width:               ${AVG_CI_WIDTH:.2f}")
print(f"  As % of forecast:               {ERROR_ANALYSIS['CI Width PCT'].mean():.1f}%")
print(f"  Minimum Width:                  ${MIN_CI_WIDTH:.2f} ({NARROWEST_CI_MONTH.name.strftime('%B %Y')})")
print(f"  Maximum Width:                  ${MAX_CI_WIDTH:.2f} ({WIDEST_CI_MONTH.name.strftime('%B %Y')})")

# Calculate if violations occur when CI is narrow
VIOLATIONS_DF = ERROR_ANALYSIS[ERROR_ANALYSIS['CI Violation']]
if len(VIOLATIONS_DF) > 0:
    AVG_CI_VIOLATIONS = VIOLATIONS_DF['CI Width'].mean()
    AVG_CI_NO_VIOLATIONS = ERROR_ANALYSIS[~ERROR_ANALYSIS['CI Violation']]['CI Width'].mean()
    
    print(f"\n🔍 CI WIDTH vs VIOLATIONS:")
    print(f"  Avg CI width (violations):      ${AVG_CI_VIOLATIONS:.2f}")
    print(f"  Avg CI width (no violations):   ${AVG_CI_NO_VIOLATIONS:.2f}")
    if AVG_CI_VIOLATIONS < AVG_CI_NO_VIOLATIONS:
        print(f"  → Violations tend to occur when CI is narrower (overconfident predictions)")
    else:
        print(f"  → CI width does not predict violations well")

print("="*70)

======================================================================
CONFIDENCE INTERVAL COVERAGE ANALYSIS
======================================================================

📊 COVERAGE STATISTICS:
  Expected Coverage (95% CI):     95.0%
  Actual Coverage:                83.3%
  Coverage below expectations

⚠️  VIOLATIONS:
  Total months outside CI:        2 (16.7%)
  Upper bound violations:         1 (overspending)
  Lower bound violations:         1 (underspending)

📏 CONFIDENCE INTERVAL WIDTH:
  Average CI Width:               $405.10
  As % of forecast:               57.4%
  Minimum Width:                  $392.63 (August 2023)
  Maximum Width:                  $417.55 (February 2023)

🔍 CI WIDTH vs VIOLATIONS:
  Avg CI width (violations):      $406.17
  Avg CI width (no violations):   $404.89
  → CI width does not predict violations well
======================================================================

In [170]:
# Visualization
fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        "CI Coverage Over Time",
        "CI Width Distribution",
        "CI Width vs Forecast Level",
        "Coverage Performance Summary"
    ),
    vertical_spacing=0.15,
    horizontal_spacing=0.12,
    specs=[
        [{"type": "scatter"}, {"type": "histogram"}],
        [{"type": "scatter"}, {"type": "indicator"}]
    ]
)

# CI coverage timeline (TOP LEFT)
# Plot CI bands
fig.add_trace(
    go.Scatter(
        x=ERROR_ANALYSIS.index,
        y=ERROR_ANALYSIS["Upper CI"],
        mode="lines",
        line=dict(width=0),
        showlegend=False,
        hoverinfo="skip"
    ),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(
        x=ERROR_ANALYSIS.index,
        y=ERROR_ANALYSIS["Lower CI"],
        mode="lines",
        fill="tonexty",
        fillcolor="rgba(76, 175, 80, 0.2)",
        line=dict(width=0),
        name="95% CI Band",
        showlegend=True
    ),
    row=1, col=1
)

# Actual values - color by whether within CI
WITHIN_CI = ERROR_ANALYSIS[ERROR_ANALYSIS["Within CI"]]
OUTSIDE_CI = ERROR_ANALYSIS[~ERROR_ANALYSIS["Within CI"]]

fig.add_trace(
    go.Scatter(
        x=WITHIN_CI.index,
        y=WITHIN_CI["Actual"],
        mode="markers",
        name="Within CI",
        marker=dict(size=6, color="#4ECDC4"),
        showlegend=True
    ),
    row=1, col=1
)

if len(OUTSIDE_CI) > 0:
    fig.add_trace(
        go.Scatter(
            x=OUTSIDE_CI.index,
            y=OUTSIDE_CI["Actual"],
            mode="markers",
            name="Outside CI",
            marker=dict(size=10, color="#FF6B6B", symbol="x", line=dict(width=2, color="white")),
            showlegend=True
        ),
        row=1, col=1
    )

# Forecast line
fig.add_trace(
    go.Scatter(
        x=ERROR_ANALYSIS.index,
        y=ERROR_ANALYSIS["Forecast"],
        mode="lines",
        name="Forecast",
        line=dict(color="#E8B4B8", width=1.5, dash="dash"),
        showlegend=True
    ),
    row=1, col=1
)

# CI width histogram (TOP RIGHT)
fig.add_trace(
    go.Histogram(
        x=ERROR_ANALYSIS["CI Width"],
        nbinsx=20,
        marker=dict(color="#7FADDC"),
        showlegend=False
    ),
    row=1, col=2
)

# Add mean line
fig.add_vline(
    x=AVG_CI_WIDTH,
    line_dash="dash",
    line_color="#FFA500",
    annotation_text=f"Mean: ${AVG_CI_WIDTH:.0f}",
    row=1, col=2
)

# CI width vs forecast level (BOTTOM LEFT)
fig.add_trace(
    go.Scatter(
        x=ERROR_ANALYSIS["Forecast"],
        y=ERROR_ANALYSIS["CI Width"],
        mode="markers",
        marker=dict(
            size=8,
            color=ERROR_ANALYSIS["CI Violation"].astype(int),
            colorscale=[[0, "#4ECDC4"], [1, "#FF6B6B"]],
            showscale=True,
            colorbar=dict(
                title="Violation",
                tickvals=[0, 1],
                ticktext=["No", "Yes"],
                x=1.15,
                len=0.35,
                y=0.15
            )
        ),
        showlegend=False
    ),
    row=2, col=1
)

# Add trend line
z = np.polyfit(ERROR_ANALYSIS["Forecast"], ERROR_ANALYSIS["CI Width"], 1)
p = np.poly1d(z)
fig.add_trace(
    go.Scatter(
        x=ERROR_ANALYSIS["Forecast"],
        y=p(ERROR_ANALYSIS["Forecast"]),
        mode="lines",
        name="Trend",
        line=dict(color="#FFA500", width=2, dash="dot"),
        showlegend=False
    ),
    row=2, col=1
)

# Coverage gauge (BOTTOM RIGHT)
fig.add_trace(
    go.Indicator(
        mode="gauge+number+delta",
        value=COVERAGE_RATE,
        delta={'reference': EXPECTED_COVERAGE, 'relative': False, 'suffix': '%'},
        title={'text': f"CI Coverage<br><span style='font-size:0.8em'>Target: {EXPECTED_COVERAGE}%</span>"},
        gauge={
            'axis': {'range': [0, 100]},
            'bar': {'color': '#4ECDC4' if COVERAGE_RATE >= 90 else '#FFA500' if COVERAGE_RATE >= 85 else '#FF6B6B'},
            'steps': [
                {'range': [0, 85], 'color': "rgba(244, 67, 54, 0.2)"},
                {'range': [85, 95], 'color': "rgba(255, 193, 7, 0.2)"},
                {'range': [95, 100], 'color': "rgba(76, 205, 196, 0.2)"}
            ],
            'threshold': {
                'line': {'color': "red", 'width': 4},
                'thickness': 0.75,
                'value': EXPECTED_COVERAGE
            }
        },
        domain={'x': [0, 1], 'y': [0, 1]}
    ),
    row=2, col=2
)

# Update axes
fig.update_xaxes(title_text="Date", row=1, col=1)
fig.update_yaxes(title_text="Expenses ($)", row=1, col=1)

fig.update_xaxes(title_text="CI Width ($)", row=1, col=2)
fig.update_yaxes(title_text="Frequency", row=1, col=2)

fig.update_xaxes(title_text="Forecast ($)", row=2, col=1)
fig.update_yaxes(title_text="CI Width ($)", row=2, col=1)

fig.update_layout(
    title=dict(
        text="Confidence Interval Coverage Analysis",
        x=0.5,
        xanchor="center",
        font=dict(size=20)
    ),
    height=900,
    width=1000,
    template="plotly_dark",
    showlegend=True,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    )
)

fig.show()

FIG_TITLE = "Confidence Interval Coverage Analysis"
PLOT_CAPTION = f"""
Confidence interval coverage analysis assesses the reliability of SARIMA"s uncertainty quantification. The model achieves {COVERAGE_RATE:.1f}% empirical coverage against the theoretical 95% target, {"meeting" if COVERAGE_RATE >= 90 else "falling short of"} expectations. The timeline (top-left) visualizes CI bands with actual spending, clearly marking the {TOTAL_VIOLATIONS} months ({TOTAL_VIOLATIONS/len(ERROR_ANALYSIS)*100:.1f}%) that violated bounds - {UPPER_VIOLATIONS} upper violations (overspending) and {LOWER_VIOLATIONS} lower violations (underspending). The CI width distribution (top-right) shows prediction uncertainty varies from ${MIN_CI_WIDTH:.0f} to ${MAX_CI_WIDTH:.0f}, averaging ${AVG_CI_WIDTH:.0f} ({ERROR_ANALYSIS["CI Width PCT"].mean():.1f}% of forecast). The scatter plot (bottom-left) examines whether CI width scales appropriately with forecast magnitude, with violations color-coded to reveal if failures occur during overconfident (narrow CI) predictions. The coverage gauge (bottom-right) provides at-a-glance assessment of overall CI calibration quality.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="FORECAST_ERROR_ANALYSIS_CI_COVERAGE_ANALYSIS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Confidence interval coverage analysis assesses the reliability of SARIMA"s uncertainty quantification. The model achieves 83.3%
empirical coverage against the theoretical 95% target, falling short of expectations. The timeline (top-left) visualizes CI bands
with actual spending, clearly marking the 2 months (16.7%) that violated bounds - 1 upper violations (overspending) and 1 lower
violations (underspending). The CI width distribution (top-right) shows prediction uncertainty varies from $393 to $418, averaging
$405 (57.4% of forecast). The scatter plot (bottom-left) examines whether CI width scales appropriately with forecast magnitude,
with violations color-coded to reveal if failures occur during overconfident (narrow CI) predictions. The coverage gauge (bottom-
right) provides at-a-glance assessment of overall CI calibration quality.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\FORECAST_ERROR_ANALYSIS_CI_COVERAGE_ANALYSIS.png
✅ Registered component: FORECAST_ERROR_ANALYSIS_CI_COVERAGE_ANALYSIS.png with Title Confidence Interval Coverage Analysis

<h2>Scenario Simulation</h2>
<p>What are the impacts on the forecast given the existence of hypothetical situations?</p>
<p> --> To simulate the what if scenarios.</p>

In [171]:
# Report Management
SUBSECTION_TITLE = "Scenario Simulation"
SUBSECTION_CAPTION = "To simulate the what if scenarios"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="PREDICTIVE_AND_PRESCRIPTIVE_SCENARIO_SIMULATION"
)

✅ Registered component: PREDICTIVE_AND_PRESCRIPTIVE_SCENARIO_SIMULATION with Title Scenario Simulation

In [172]:
# Get baseline forecast (12 months forward from last data point)
BASELINE_FORECAST = FITTED_MODEL.get_forecast(steps=12)
BASELINE_MEAN = BASELINE_FORECAST.predicted_mean
BASELINE_CI = BASELINE_FORECAST.conf_int()

BASELINE_DF = pd.DataFrame({
    "Forecast": BASELINE_MEAN,
    "Lower CI": BASELINE_CI.iloc[:, 0],
    "Upper CI": BASELINE_CI.iloc[:, 1]
})

In [173]:
# Define what-if scenarios
SCENARIOS = {
    "BASELINE": {
        "NAME": "Baseline (Current Trajectory)",
        "DESCRIPTION": "Continue current spending patterns",
        "ADJUSTMENT": 0.0,
        "COLOR": "#7FADDC"
    },
    "INCOME_LOSS": {
        "NAME": "Income Reduction (-20%)",
        "DESCRIPTION": "Reduce all expenses by 20% due to income loss",
        "ADJUSTMENT": -0.20,
        "COLOR": "#FF6B6B"
    },
    "AUSTERITY": {
        "NAME": "Austerity Mode (-30%)",
        "DESCRIPTION": "Aggressive spending cuts across all categories",
        "ADJUSTMENT": -0.30,
        "COLOR": "#F44336"
    },
    "LIFESTYLE_INFLATION": {
        "NAME": "Lifestyle Inflation (+15%)",
        "DESCRIPTION": "Increased spending due to lifestyle changes",
        "ADJUSTMENT": 0.15,
        "COLOR": "#FFA500"
    },
    "MAJOR_EXPENSE": {
        "NAME": "Major One-Time Expense",
        "DESCRIPTION": "Large expense in month 3 (e.g., emergency, purchase)",
        "ADJUSTMENT": 0.0,  # No overall change, just a spike
        "SPIKE_MONTH": 3,
        "SPIKE_AMOUNT": 500,
        "COLOR": "#FF9800"
    },
    "OPTIMIZATION": {
        "NAME": "Optimized Budget (-10%)",
        "DESCRIPTION": "Modest spending reduction through optimization",
        "ADJUSTMENT": -0.10,
        "COLOR": "#4ECDC4"
    }
}

In [174]:
print("="*70)
print("SCENARIO SIMULATION - WHAT-IF ANALYSIS")
print("="*70)
print(f"\nBaseline Annual Spending (next 12 months): ${BASELINE_DF["Forecast"].sum():,.2f}")
print(f"Monthly Average: ${BASELINE_DF["Forecast"].mean():,.2f}")
print(f"\n📋 DEFINED SCENARIOS:\n")

for key, scenario in SCENARIOS.items():
    print(f"  {scenario["NAME"]}")
    print(f"    → {scenario["DESCRIPTION"]}")
    if scenario["ADJUSTMENT"] != 0:
        print(f"    → Adjustment: {scenario["ADJUSTMENT"]:+.0%}")
    if "SPIKE_MONTH" in scenario:
        print(f"    → Spike: +${scenario["SPIKE_AMOUNT"]} in month {scenario["SPIKE_MONTH"]}")
    print()

print("="*70)

======================================================================
SCENARIO SIMULATION - WHAT-IF ANALYSIS
======================================================================

Baseline Annual Spending (next 12 months): $8,508.86
Monthly Average: $709.07

📋 DEFINED SCENARIOS:

  Baseline (Current Trajectory)
    → Continue current spending patterns

  Income Reduction (-20%)
    → Reduce all expenses by 20% due to income loss
    → Adjustment: -20%

  Austerity Mode (-30%)
    → Aggressive spending cuts across all categories
    → Adjustment: -30%

  Lifestyle Inflation (+15%)
    → Increased spending due to lifestyle changes
    → Adjustment: +15%

  Major One-Time Expense
    → Large expense in month 3 (e.g., emergency, purchase)
    → Spike: +$500 in month 3

  Optimized Budget (-10%)
    → Modest spending reduction through optimization
    → Adjustment: -10%

======================================================================

In [175]:
# Generate scenario forecasts
SCENARIO_FORECASTS = {}

for key, scenario in SCENARIOS.items():
    SCENARIO_DATA = BASELINE_DF.copy()
    
    # Apply adjustment
    if scenario["ADJUSTMENT"] != 0:
        SCENARIO_DATA["Forecast"] = SCENARIO_DATA["Forecast"] * (1 + scenario["ADJUSTMENT"])
        SCENARIO_DATA["Lower CI"] = SCENARIO_DATA["Lower CI"] * (1 + scenario["ADJUSTMENT"])
        SCENARIO_DATA["Upper CI"] = SCENARIO_DATA["Upper CI"] * (1 + scenario["ADJUSTMENT"])
    
    # Apply spike if exists
    if "SPIKE_MONTH" in scenario:
        spike_idx = scenario["SPIKE_MONTH"] - 1
        SCENARIO_DATA.iloc[spike_idx, SCENARIO_DATA.columns.get_loc("Forecast")] += scenario["SPIKE_AMOUNT"]
    
    # Calculate totals
    SCENARIO_DATA["Cumulative"] = SCENARIO_DATA["Forecast"].cumsum()
    
    SCENARIO_FORECASTS[key] = {
        "DATA": SCENARIO_DATA,
        "TOTAL": SCENARIO_DATA["Forecast"].sum(),
        "MONTHLY_AVG": SCENARIO_DATA["Forecast"].mean(),
        **scenario
    }

# Comparison summary
print("\n" + "="*70)
print("SCENARIO COMPARISON SUMMARY")
print("="*70)
print(f"{"Scenario":<35s} {"Annual Total":>15s} {"vs Baseline":>12s} {"Monthly Avg":>12s}")
print("-" * 70)

BASELINE_TOTAL = SCENARIO_FORECASTS["BASELINE"]["TOTAL"]

for key in ["BASELINE", "OPTIMIZATION", "INCOME_LOSS", "AUSTERITY", "LIFESTYLE_INFLATION", "MAJOR_EXPENSE"]:
    SCENARIO = SCENARIO_FORECASTS[key]
    DIFF = SCENARIO["TOTAL"] - BASELINE_TOTAL
    DIFF_PCT = (DIFF / BASELINE_TOTAL * 100) if BASELINE_TOTAL != 0 else 0
    
    print(f"{SCENARIO["NAME"]:<35s} ${SCENARIO["TOTAL"]:>13,.2f} {DIFF:+>11,.2f} ({DIFF_PCT:+.1f}%)  ${SCENARIO["MONTHLY_AVG"]:>10,.2f}")

print("="*70)

======================================================================
SCENARIO COMPARISON SUMMARY
======================================================================
Scenario                               Annual Total  vs Baseline  Monthly Avg
----------------------------------------------------------------------
Baseline (Current Trajectory)       $     8,508.86 +++++++0.00 (+0.0%)  $    709.07
Optimized Budget (-10%)             $     7,657.97 ++++-850.89 (-10.0%)  $    638.16
Income Reduction (-20%)             $     6,807.09 ++-1,701.77 (-20.0%)  $    567.26
Austerity Mode (-30%)               $     5,956.20 ++-2,552.66 (-30.0%)  $    496.35
Lifestyle Inflation (+15%)          $     9,785.19 +++1,276.33 (+15.0%)  $    815.43
Major One-Time Expense              $     9,008.86 +++++500.00 (+5.9%)  $    750.74
======================================================================

In [176]:
# Visualization
fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        "Monthly Spending Projections by Scenario",
        "Cumulative Spending Over 12 Months",
        "Annual Total Comparison",
        "Scenario Impact Summary"
    ),
    vertical_spacing=0.15,
    horizontal_spacing=0.12,
    specs=[
        [{"type": "scatter"}, {"type": "scatter"}],
        [{"type": "bar"}, {"type": "table"}]
    ],
    row_heights=[0.45, 0.55]
)

# Prepare x-axis (months 1-12)
MONTHS = list(range(1, 13))
MONTH_LABELS = [f"Month {i}" for i in MONTHS]

# 1. Monthly spending projections (TOP LEFT)
for key in ["BASELINE", "OPTIMIZATION", "INCOME_LOSS", "AUSTERITY", "LIFESTYLE_INFLATION", "MAJOR_EXPENSE"]:
    SCENARIO = SCENARIO_FORECASTS[key]
    
    fig.add_trace(
        go.Scatter(
            x=MONTHS,
            y=SCENARIO["DATA"]["Forecast"],
            mode="lines+markers",
            name=SCENARIO["NAME"],
            line=dict(color=SCENARIO["COLOR"], width=2),
            marker=dict(size=6)
        ),
        row=1, col=1
    )

# 2. Cumulative spending (TOP RIGHT)
for key in ["BASELINE", "OPTIMIZATION", "INCOME_LOSS", "AUSTERITY", "LIFESTYLE_INFLATION", "MAJOR_EXPENSE"]:
    SCENARIO = SCENARIO_FORECASTS[key]
    
    fig.add_trace(
        go.Scatter(
            x=MONTHS,
            y=SCENARIO["DATA"]["Cumulative"],
            mode="lines",
            name=SCENARIO["NAME"],
            line=dict(color=SCENARIO["COLOR"], width=2.5),
            showlegend=False
        ),
        row=1, col=2
    )

# 3. Annual total comparison (BOTTOM LEFT)
SCENARIO_NAMES = []
SCENARIO_TOTALS = []
SCENARIO_COLORS = []

for key in ["BASELINE", "OPTIMIZATION", "INCOME_LOSS", "AUSTERITY", "LIFESTYLE_INFLATION", "MAJOR_EXPENSE"]:
    SCENARIO = SCENARIO_FORECASTS[key]
    SCENARIO_NAMES.append(SCENARIO["NAME"].replace(" ", "<br>"))  # Wrap long names
    SCENARIO_TOTALS.append(SCENARIO["TOTAL"])
    SCENARIO_COLORS.append(SCENARIO["COLOR"])

fig.add_trace(
    go.Bar(
        x=SCENARIO_NAMES,
        y=SCENARIO_TOTALS,
        marker=dict(color=SCENARIO_COLORS),
        text=[f"${t:,.0f}" for t in SCENARIO_TOTALS],
        textposition="outside",
        showlegend=False
    ),
    row=2, col=1
)

# Add baseline reference line
fig.add_hline(
    y=BASELINE_TOTAL,
    line_dash="dash",
    line_color="#7FADDC",
    annotation_text=f"Baseline: ${BASELINE_TOTAL:,.0f}",
    annotation_position="right",
    row=2, col=1
)

# 4. Summary table (BOTTOM RIGHT)
SUMMARY_DATA = []
for key in ["BASELINE", "OPTIMIZATION", "INCOME_LOSS", "AUSTERITY", "LIFESTYLE_INFLATION", "MAJOR_EXPENSE"]:
    SCENARIO = SCENARIO_FORECASTS[key]
    DIFF = SCENARIO["TOTAL"] - BASELINE_TOTAL
    DIFF_PCT = (DIFF / BASELINE_TOTAL * 100) if BASELINE_TOTAL != 0 else 0
    
    SUMMARY_DATA.append([
        SCENARIO["NAME"],
        f"${SCENARIO["TOTAL"]:,.0f}",
        f"${DIFF:+,.0f}",
        f"{DIFF_PCT:+.1f}%"
    ])

fig.add_trace(
    go.Table(
        header=dict(
            values=["<b>Scenario</b>", "<b>Annual Total</b>", "<b>vs Baseline</b>", "<b>Change %</b>"],
            fill_color="#1e293b",
            align="left",
            font=dict(color="white", size=11),
            height=30
        ),
        cells=dict(
            values=list(zip(*SUMMARY_DATA)),
            fill_color=[
                "#334155",  # Scenario names
                "#475569",  # Annual total
                ["#4ECDC4" if row[2].startswith("-") else "#FF6B6B" if row[2].startswith("+") else "#475569" 
                 for row in SUMMARY_DATA],  # Color by savings/increase
                "#475569"   # Change %
            ],
            align="left",
            font=dict(color="white", size=10),
            height=28
        )
    ),
    row=2, col=2
)

# Update axes
fig.update_xaxes(title_text="Month", row=1, col=1)
fig.update_yaxes(title_text="Monthly Spending ($)", row=1, col=1)

fig.update_xaxes(title_text="Month", row=1, col=2)
fig.update_yaxes(title_text="Cumulative Spending ($)", row=1, col=2)

fig.update_xaxes(title_text="Scenario", tickangle=-45, row=2, col=1)
fig.update_yaxes(title_text="Annual Total ($)", row=2, col=1)

fig.update_layout(
    title=dict(
        text="Scenario Simulation - What-If Analysis",
        x=0.5,
        xanchor="center",
        font=dict(size=20)
    ),
    height=1000,
    width=1000,
    template="plotly_dark",
    showlegend=True,
    legend=dict(
        orientation="v",
        yanchor="top",
        y=0.98,
        xanchor="left",
        x=1.02
    )
)

fig.show()

FIG_TITLE = "Scenario Simulation - What-If Analysis"
PLOT_CAPTION = f"""
What-if scenario analysis projects the financial impact of various spending adjustments over a 12-month horizon. The baseline scenario (${BASELINE_TOTAL:,.0f} annually) represents continuation of current patterns. The optimization scenario (-10%) demonstrates that modest spending discipline could save ${abs(SCENARIO_FORECASTS["OPTIMIZATION"]["TOTAL"] - BASELINE_TOTAL):,.0f} annually. Income reduction (-20%) and austerity (-30%) scenarios model necessary adjustments during financial hardship, showing required cutbacks of ${abs(SCENARIO_FORECASTS["INCOME_LOSS"]["TOTAL"] - BASELINE_TOTAL):,.0f} and ${abs(SCENARIO_FORECASTS["AUSTERITY"]["TOTAL"] - BASELINE_TOTAL):,.0f} respectively. The lifestyle inflation scenario (+15%) quantifies the cost of increased spending (${SCENARIO_FORECASTS["LIFESTYLE_INFLATION"]["TOTAL"] - BASELINE_TOTAL:,.0f} additional), while the major expense scenario illustrates impact of one-time events. Monthly projections (top-left) show spending trajectories, cumulative charts (top-right) reveal total financial commitment over time, and the comparison bar chart (bottom-left) enables direct scenario evaluation. This analysis supports data-driven budgeting decisions by quantifying the consequences of different financial choices.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="SCENARIO_SIMULATION_WHATIF_ANALYSIS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 What-if scenario analysis projects the financial impact of various spending adjustments over a 12-month horizon. The baseline
scenario ($8,509 annually) represents continuation of current patterns. The optimization scenario (-10%) demonstrates that modest
spending discipline could save $851 annually. Income reduction (-20%) and austerity (-30%) scenarios model necessary adjustments
during financial hardship, showing required cutbacks of $1,702 and $2,553 respectively. The lifestyle inflation scenario (+15%)
quantifies the cost of increased spending ($1,276 additional), while the major expense scenario illustrates impact of one-time
events. Monthly projections (top-left) show spending trajectories, cumulative charts (top-right) reveal total financial commitment
over time, and the comparison bar chart (bottom-left) enables direct scenario evaluation. This analysis supports data-driven
budgeting decisions by quantifying the consequences of different financial choices.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\SCENARIO_SIMULATION_WHATIF_ANALYSIS.png
✅ Registered component: SCENARIO_SIMULATION_WHATIF_ANALYSIS.png with Title Scenario Simulation - What-If Analysis

In [177]:
# Test range of spending adjustments
ADJUSTMENT_RANGE = np.arange(-0.40, 0.31, 0.05).round(2)  # -40% to +30% in 5% increments
SENSITIVITY_RESULTS = []

for adjustment in ADJUSTMENT_RANGE:
    ADJUSTED_FORECAST = BASELINE_DF["Forecast"] * (1 + adjustment)
    ANNUAL_TOTAL = ADJUSTED_FORECAST.sum()
    MONTHLY_AVG = ADJUSTED_FORECAST.mean()

    ADJUSTMENT_PCT = adjustment * 100
    
    SENSITIVITY_RESULTS.append({
        "Adjustment PCT": ADJUSTMENT_PCT,
        "Annual Total": ANNUAL_TOTAL,
        "Monthly Avg": MONTHLY_AVG,
        "VS Baseline": ANNUAL_TOTAL - BASELINE_TOTAL,
        "VS Baseline PCT": ((ANNUAL_TOTAL - BASELINE_TOTAL) / BASELINE_TOTAL) * 100
    })

SENSITIVITY_DF = pd.DataFrame(SENSITIVITY_RESULTS)

# Identify key thresholds
# Example: What adjustment needed to save $1000/year?
TARGET_SAVINGS = 1000
CLOSEST_TO_TARGET = SENSITIVITY_DF.iloc[(SENSITIVITY_DF["VS Baseline"] + TARGET_SAVINGS).abs().argsort()[:1]]

print("\n" + "="*70)
print("SENSITIVITY ANALYSIS - SPENDING ADJUSTMENT IMPACT")
print("="*70)
print(f"\nBaseline Annual Spending: ${BASELINE_TOTAL:,.2f}")
print(f"\n💡 KEY INSIGHTS:")
print(f"  To save $1,000/year: Need {CLOSEST_TO_TARGET["Adjustment PCT"].values[0]:.1f}% spending reduction")
print(f"  -10% spending cut saves: ${abs(SENSITIVITY_DF[SENSITIVITY_DF["Adjustment PCT"] == -10.0]["VS Baseline"].values[0]):,.2f}/year")
print(f"  -20% spending cut saves: ${abs(SENSITIVITY_DF[SENSITIVITY_DF["Adjustment PCT"] == -20.0]["VS Baseline"].values[0]):,.2f}/year")
print(f"  +10% spending increase costs: ${SENSITIVITY_DF[SENSITIVITY_DF["Adjustment PCT"] == 10.0]["VS Baseline"].values[0]:,.2f}/year")
print("="*70)

======================================================================
SENSITIVITY ANALYSIS - SPENDING ADJUSTMENT IMPACT
======================================================================

Baseline Annual Spending: $8,508.86

💡 KEY INSIGHTS:
  To save $1,000/year: Need -10.0% spending reduction
  -10% spending cut saves: $850.89/year
  -20% spending cut saves: $1,701.77/year
  +10% spending increase costs: $850.89/year
======================================================================

In [ ]:
# Visualization
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=(
        "Annual Spending vs Adjustment Level",
        "Savings/Increase vs Baseline"
    ),
    horizontal_spacing=0.12
)

# Annual total vs adjustment (LEFT)
# Color gradient based on adjustment
COLORS_GRADIENT = ["#4ECDC4" if adj < 0 else "#FF6B6B" for adj in SENSITIVITY_DF["Adjustment PCT"]]

fig.add_trace(
    go.Scatter(
        x=SENSITIVITY_DF["Adjustment PCT"],
        y=SENSITIVITY_DF["Annual Total"],
        mode="lines+markers",
        name="Annual Total",
        line=dict(color="#7FADDC", width=3),
        marker=dict(size=8, color=COLORS_GRADIENT),
        fill="tozeroy",
        fillcolor="rgba(124, 173, 220, 0.2)"
    ),
    row=1, col=1
)

# Add baseline reference
fig.add_hline(
    y=BASELINE_TOTAL,
    line_dash="dash",
    line_color="white",
    annotation_text=f"Baseline: ${BASELINE_TOTAL:,.0f}",
    row=1, col=1
)

# Highlight key points
for adj_pct in [-30, -20, -10, 0, 10, 15]:
    point = SENSITIVITY_DF[SENSITIVITY_DF["Adjustment PCT"] == adj_pct]
    if not point.empty:
        fig.add_annotation(
            x=adj_pct,
            y=point["Annual Total"].values[0],
            text=f"{adj_pct:+.0f}%",
            showarrow=True,
            arrowhead=2,
            arrowsize=1,
            arrowwidth=1,
            arrowcolor="white",
            font=dict(size=9),
            row=1, col=1
        )

# 2. Savings vs baseline (RIGHT)
fig.add_trace(
    go.Bar(
        x=SENSITIVITY_DF["Adjustment PCT"],
        y=SENSITIVITY_DF["VS Baseline"],
        marker=dict(
            color=SENSITIVITY_DF["VS Baseline"],
            colorscale="RdYlGn",
            showscale=True,
            colorbar=dict(title="Savings ($)", x=1.05, y=0.35)
        ),
        showlegend=False
    ),
    row=1, col=2
)

fig.add_hline(y=0, line_dash="solid", line_color="gray", row=1, col=2)

# Update axes
fig.update_xaxes(title_text="Spending Adjustment (%)", row=1, col=1)
fig.update_yaxes(title_text="Annual Spending ($)", row=1, col=1)

fig.update_xaxes(title_text="Spending Adjustment (%)", row=1, col=2)
fig.update_yaxes(title_text="Savings vs Baseline ($)", row=1, col=2)

fig.update_layout(
    title=dict(
        text="Sensitivity Analysis - Impact of Spending Adjustments",
        x=0.5,
        xanchor="center",
        font=dict(size=20)
    ),
    height=500,
    width=1000,
    template="plotly_dark"
)

fig.show()

FIG_TITLE = "Sensitivity Analysis - Impact of Spending Adjustments"
PLOT_CAPTION = f"""
Sensitivity analysis quantifies the linear relationship between spending adjustments and annual budget impact across a -40% to +30% range. The left panel demonstrates that annual spending scales predictably with adjustment percentage - each 5% spending reduction yields approximately ${abs(SENSITIVITY_DF[SENSITIVITY_DF["Adjustment PCT"] == -5.0]["VS Baseline"].values[0]):,.0f} in annual savings. Key reference points are annotated: a -20% adjustment (income reduction scenario) saves ${abs(SENSITIVITY_DF[SENSITIVITY_DF["Adjustment PCT"] == -20.0]["VS Baseline"].values[0]):,.2f} annually, while a +15% increase (lifestyle inflation) adds ${SENSITIVITY_DF[SENSITIVITY_DF["Adjustment PCT"] == 15.0]["VS Baseline"].values[0]:,.2f}. The right panel visualizes this relationship as savings/costs relative to baseline, with green bars indicating savings and red bars showing increased spending. This analysis reveals that achieving a $1,000 annual savings target requires approximately {CLOSEST_TO_TARGET["Adjustment PCT"].values[0]:.1f}% spending reduction, providing concrete guidance for budget goal setting.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="SENSITIVITY_ANALYSIS_SPENDING_ADJUSTMENTS.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Sensitivity analysis quantifies the linear relationship between spending adjustments and annual budget impact across a -40% to
+30% range. The left panel demonstrates that annual spending scales predictably with adjustment percentage - each 5% spending
reduction yields approximately $425 in annual savings. Key reference points are annotated: a -20% adjustment (income reduction
scenario) saves $1,701.77 annually, while a +15% increase (lifestyle inflation) adds $1,276.33. The right panel visualizes this
relationship as savings/costs relative to baseline, with green bars indicating savings and red bars showing increased spending.
This analysis reveals that achieving a $1,000 annual savings target requires approximately -10.0% spending reduction, providing
concrete guidance for budget goal setting.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\SENSITIVITY_ANALYSIS_SPENDING_ADJUSTMENTS.png
✅ Registered component: SENSITIVITY_ANALYSIS_SPENDING_ADJUSTMENTS.png with Title Sensitivity Analysis - Impact of Spending Adjustments

In [179]:
# Summary Table
print("\n" + "="*70)
print("SCENARIO SIMULATION SUMMARY - KEY TAKEAWAYS")
print("="*70)
print(f"""
The what-if scenario analysis provides actionable insights for budget planning:

1. BASELINE PROJECTION
   • Expected annual spending: ${BASELINE_TOTAL:,.2f}
   • Monthly average: ${SCENARIO_FORECASTS["BASELINE"]["MONTHLY_AVG"]:,.2f}

2. OPTIMIZATION POTENTIAL  
   • 10% reduction saves: ${abs(SCENARIO_FORECASTS["OPTIMIZATION"]["TOTAL"] - BASELINE_TOTAL):,.2f}/year
   • Achievable through category-level budget discipline

3. FINANCIAL HARDSHIP SCENARIOS
   • Income loss (-20%): Requires ${abs(SCENARIO_FORECASTS["INCOME_LOSS"]["TOTAL"] - BASELINE_TOTAL):,.2f} in cuts
   • Austerity mode (-30%): Maximum sustainable reduction

4. SPENDING RISK
   • Lifestyle inflation (+15%): Costs ${SCENARIO_FORECASTS["LIFESTYLE_INFLATION"]["TOTAL"] - BASELINE_TOTAL:,.2f} extra annually
   • Vigilance needed to prevent gradual spending creep

5. SENSITIVITY INSIGHTS
   • Each 1% spending change = ~${abs(SENSITIVITY_DF[SENSITIVITY_DF["Adjustment PCT"] == 10.0]["VS Baseline"].values[0])/10:,.0f}/year impact
   • Small adjustments compound significantly over 12 months

RECOMMENDATION: Target the optimization scenario (-10%) as a balanced approach
between financial discipline and lifestyle maintenance.
""")
print("="*70)

======================================================================
SCENARIO SIMULATION SUMMARY - KEY TAKEAWAYS
======================================================================

The what-if scenario analysis provides actionable insights for budget planning:

1. BASELINE PROJECTION
   • Expected annual spending: $8,508.86
   • Monthly average: $709.07

2. OPTIMIZATION POTENTIAL
   • 10% reduction saves: $850.89/year
   • Achievable through category-level budget discipline

3. FINANCIAL HARDSHIP SCENARIOS
   • Income loss (-20%): Requires $1,701.77 in cuts
   • Austerity mode (-30%): Maximum sustainable reduction

4. SPENDING RISK
   • Lifestyle inflation (+15%): Costs $1,276.33 extra annually
   • Vigilance needed to prevent gradual spending creep

5. SENSITIVITY INSIGHTS
   • Each 1% spending change = ~$85/year impact
   • Small adjustments compound significantly over 12 months

RECOMMENDATION: Target the optimization scenario (-10%) as a balanced approach
between financial discipline and lifestyle maintenance.

======================================================================

<h2>Budget Recommendation</h2>
<p>Given historical spending and forecast uncertainty, what should the recommended budget for the next period be?</p>
<p> --> To determine the recommended budget level for the future periods.</p>

In [180]:
# Report Management
SUBSECTION_TITLE = "Budget Recommendation"
SUBSECTION_CAPTION = "To determine the recommended budget level for the future periods"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="PREDICTIVE_AND_PRESCRIPTIVE_BUDGET_RECOMMENDATION"
)

✅ Registered component: PREDICTIVE_AND_PRESCRIPTIVE_BUDGET_RECOMMENDATION with Title Budget Recommendation

In [181]:
# Use historical data + forward forecast to build recommendations
HISTORICAL_STATS = {
    'MEAN': MONTHLY_EXPENSES_TIME_SERIES_COPY.mean(),
    'MEDIAN': MONTHLY_EXPENSES_TIME_SERIES_COPY.median(),
    'STD': MONTHLY_EXPENSES_TIME_SERIES_COPY.std(),
    'Q25': MONTHLY_EXPENSES_TIME_SERIES_COPY.quantile(0.25),
    'Q75': MONTHLY_EXPENSES_TIME_SERIES_COPY.quantile(0.75),
    'MIN': MONTHLY_EXPENSES_TIME_SERIES_COPY.min(),
    'MAX': MONTHLY_EXPENSES_TIME_SERIES_COPY.max()
}

In [182]:
# Forward forecast for next 12 months
FORWARD_12M = FITTED_MODEL.get_forecast(steps=12)
FORECAST_MEAN_12M = FORWARD_12M.predicted_mean
FORECAST_CI_12M = FORWARD_12M.conf_int()

FORECAST_STATS = {
    'MEAN': FORECAST_MEAN_12M.mean(),
    'MEDIAN': FORECAST_MEAN_12M.median(),
    'UPPER_CI_AVG': FORECAST_CI_12M.iloc[:, 1].mean(),
    'LOWER_CI_AVG': FORECAST_CI_12M.iloc[:, 0].mean()
}

In [183]:
# Build tiered budget recommendations
BUDGET_TIERS = {
    "CONSERVATIVE": {
        "NAME": "Conservative Budget",
        "BASIS": "Upper CI average - ensures 95% coverage",
        "MONTHLY": FORECAST_STATS["UPPER_CI_AVG"],
        "ANNUAL": FORECAST_STATS["UPPER_CI_AVG"] * 12,
        "BUFFER_PCT": ((FORECAST_STATS["UPPER_CI_AVG"] - FORECAST_STATS["MEAN"]) / FORECAST_STATS["MEAN"]) * 100,
        "COLOR": "#4ECDC4",
        "RECOMMENDATION": "Recommended for irregular income or low risk tolerance"
    },
    "MODERATE": {
        "NAME": "Moderate Budget",
        "BASIS": "Forecast mean + 1 std dev",
        "MONTHLY": FORECAST_STATS["MEAN"] + (FORECAST_MEAN_12M.std()),
        "ANNUAL": (FORECAST_STATS["MEAN"] + FORECAST_MEAN_12M.std()) * 12,
        "BUFFER_PCT": (FORECAST_MEAN_12M.std() / FORECAST_STATS["MEAN"]) * 100,
        "COLOR": "#FFA500",
        "RECOMMENDATION": "Balanced approach for stable income"
    },
    "TARGET": {
        "NAME": "Target Budget",
        "BASIS": "SARIMA forecast mean",
        "MONTHLY": FORECAST_STATS["MEAN"],
        "ANNUAL": FORECAST_STATS["MEAN"] * 12,
        "BUFFER_PCT": 0,
        "COLOR": "#7FADDC",
        "RECOMMENDATION": "Aspirational target based on predictive model"
    },
    "OPTIMIZED": {
        "NAME": "Optimized Budget",
        "BASIS": "Target - 10% (efficiency gains)",
        "MONTHLY": FORECAST_STATS["MEAN"] * 0.90,
        "ANNUAL": FORECAST_STATS["MEAN"] * 0.90 * 12,
        "BUFFER_PCT": -10,
        "COLOR": "#4CAF50",
        "RECOMMENDATION": "Requires active spending discipline"
    }
}

print("="*70)
print("BUDGET RECOMMENDATION FRAMEWORK")
print("="*70)

print(f"\n📊 HISTORICAL SPENDING PROFILE (2018-2023):")
print(f"  Average:    ${HISTORICAL_STATS["MEAN"]:,.2f}/month")
print(f"  Median:     ${HISTORICAL_STATS["MEDIAN"]:,.2f}/month")
print(f"  Std Dev:    ${HISTORICAL_STATS["STD"]:,.2f}")
print(f"  Range:      ${HISTORICAL_STATS["MIN"]:,.2f} - ${HISTORICAL_STATS["MAX"]:,.2f}")

print(f"\n🔮 FORWARD FORECAST (Next 12 Months):")
print(f"  Expected:   ${FORECAST_STATS["MEAN"]:,.2f}/month")
print(f"  95% CI:     ${FORECAST_STATS["LOWER_CI_AVG"]:,.2f} - ${FORECAST_STATS["UPPER_CI_AVG"]:,.2f}")

print(f"\n💰 RECOMMENDED BUDGET TIERS:\n")

for key in ["CONSERVATIVE", "MODERATE", "TARGET", "OPTIMIZED"]:
    TIER = BUDGET_TIERS[key]
    print(f"  {TIER["NAME"].upper()}")
    print(f"    Basis:       {TIER["BASIS"]}")
    print(f"    Monthly:     ${TIER["MONTHLY"]:,.2f}")
    print(f"    Annual:      ${TIER["ANNUAL"]:,.2f}")
    print(f"    Buffer:      {TIER["BUFFER_PCT"]:+.1f}% vs forecast")
    print(f"    Use Case:    {TIER["RECOMMENDATION"]}")
    print()

print("="*70)

# Calculate savings potential
CONSERVATIVE_VS_HISTORICAL = (BUDGET_TIERS["CONSERVATIVE"]["ANNUAL"] - (HISTORICAL_STATS["MEAN"] * 12))
OPTIMIZED_VS_HISTORICAL = (BUDGET_TIERS["OPTIMIZED"]["ANNUAL"] - (HISTORICAL_STATS["MEAN"] * 12))

print(f"\n💡 BUDGET IMPACT ANALYSIS:")
print(f"  Conservative vs Historical: {CONSERVATIVE_VS_HISTORICAL:+,.2f}/year")
print(f"  Optimized vs Historical:    {OPTIMIZED_VS_HISTORICAL:+,.2f}/year")
print(f"  Potential Savings Range:    ${abs(OPTIMIZED_VS_HISTORICAL):,.2f} - ${abs(CONSERVATIVE_VS_HISTORICAL) if CONSERVATIVE_VS_HISTORICAL < 0 else 0:,.2f}/year")

print("="*70)

======================================================================
BUDGET RECOMMENDATION FRAMEWORK
======================================================================

📊 HISTORICAL SPENDING PROFILE (2018-2023):
  Average:    $559.81/month
  Median:     $567.00/month
  Std Dev:    $188.61
  Range:      $0.00 - $875.10

🔮 FORWARD FORECAST (Next 12 Months):
  Expected:   $709.07/month
  95% CI:     $449.11 - $969.04

💰 RECOMMENDED BUDGET TIERS:

  CONSERVATIVE BUDGET
    Basis:       Upper CI average - ensures 95% coverage
    Monthly:     $969.04
    Annual:      $11,628.44
    Buffer:      +36.7% vs forecast
    Use Case:    Recommended for irregular income or low risk tolerance

  MODERATE BUDGET
    Basis:       Forecast mean + 1 std dev
    Monthly:     $717.00
    Annual:      $8,603.95
    Buffer:      +1.1% vs forecast
    Use Case:    Balanced approach for stable income

  TARGET BUDGET
    Basis:       SARIMA forecast mean
    Monthly:     $709.07
    Annual:      $8,508.86
    Buffer:      +0.0% vs forecast
    Use Case:    Aspirational target based on predictive model

  OPTIMIZED BUDGET
    Basis:       Target - 10% (efficiency gains)
    Monthly:     $638.16
    Annual:      $7,657.97
    Buffer:      -10.0% vs forecast
    Use Case:    Requires active spending discipline

======================================================================

💡 BUDGET IMPACT ANALYSIS:
  Conservative vs Historical: +4,910.72/year
  Optimized vs Historical:    +940.26/year
  Potential Savings Range:    $940.26 - $0.00/year
======================================================================

In [ ]:
fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        "Monthly Budget Tier Comparison",
        "Annual Budget Breakdown",
        "12-Month Forecast with Budget Bands",
        "Budget Tier Details"
    ),
    vertical_spacing=0.15,
    horizontal_spacing=0.12,
    specs=[
        [{"type": "bar"}, {"type": "pie"}],
        [{"type": "scatter"}, {"type": "table"}]
    ],
    row_heights=[0.40, 0.60]
)

# Monthly budget comparison (TOP LEFT)
TIER_NAMES = [BUDGET_TIERS[k]["NAME"] for k in ["CONSERVATIVE", "MODERATE", "TARGET", "OPTIMIZED"]]
TIER_MONTHLY = [BUDGET_TIERS[k]["MONTHLY"] for k in ["CONSERVATIVE", "MODERATE", "TARGET", "OPTIMIZED"]]
TIER_COLORS = [BUDGET_TIERS[k]["COLOR"] for k in ["CONSERVATIVE", "MODERATE", "TARGET", "OPTIMIZED"]]

fig.add_trace(
    go.Bar(
        x=TIER_NAMES,
        y=TIER_MONTHLY,
        marker=dict(color=TIER_COLORS),
        text=[f"${m:,.0f}" for m in TIER_MONTHLY],
        textposition="outside",
        showlegend=False
    ),
    row=1, col=1
)

# Add historical average reference
fig.add_hline(
    y=HISTORICAL_STATS["MEAN"],
    line_dash="dash",
    line_color="white",
    annotation_text=f"Historical Avg: ${HISTORICAL_STATS["MEAN"]:,.0f}",
    annotation_position="right",
    row=1, col=1
)

# Annual budget pie chart (TOP RIGHT)
TIER_ANNUAL = [BUDGET_TIERS[k]["ANNUAL"] for k in ["CONSERVATIVE", "MODERATE", "TARGET", "OPTIMIZED"]]

fig.add_trace(
    go.Pie(
        labels=TIER_NAMES,
        values=TIER_ANNUAL,
        marker=dict(colors=TIER_COLORS),
        textinfo="label+value",
        texttemplate="%{label}<br>$%{value:,.0f}",
        hole=0.3
    ),
    row=1, col=2
)

# 12-month forecast with budget bands (BOTTOM LEFT)
months = list(range(1, 13))

# Conservative band (top)
fig.add_trace(
    go.Scatter(
        x=months,
        y=[BUDGET_TIERS["CONSERVATIVE"]["MONTHLY"]] * 12,
        mode="lines",
        line=dict(width=0),
        showlegend=False,
        hoverinfo="skip"
    ),
    row=2, col=1
)

# Optimized band (bottom)
fig.add_trace(
    go.Scatter(
        x=months,
        y=[BUDGET_TIERS["OPTIMIZED"]["MONTHLY"]] * 12,
        mode="lines",
        fill="tonexty",
        fillcolor="rgba(76, 205, 196, 0.15)",
        line=dict(width=0),
        name="Budget Range",
        showlegend=True
    ),
    row=2, col=1
)

# Conservative line
fig.add_trace(
    go.Scatter(
        x=months,
        y=[BUDGET_TIERS["CONSERVATIVE"]["MONTHLY"]] * 12,
        mode="lines",
        name="Conservative",
        line=dict(color=BUDGET_TIERS["CONSERVATIVE"]["COLOR"], width=2, dash="dash")
    ),
    row=2, col=1
)

# Target line
fig.add_trace(
    go.Scatter(
        x=months,
        y=[BUDGET_TIERS["TARGET"]["MONTHLY"]] * 12,
        mode="lines",
        name="Target",
        line=dict(color=BUDGET_TIERS["TARGET"]["COLOR"], width=2.5)
    ),
    row=2, col=1
)

# Optimized line
fig.add_trace(
    go.Scatter(
        x=months,
        y=[BUDGET_TIERS["OPTIMIZED"]["MONTHLY"]] * 12,
        mode="lines",
        name="Optimized",
        line=dict(color=BUDGET_TIERS["OPTIMIZED"]["COLOR"], width=2, dash="dot")
    ),
    row=2, col=1
)

# Actual forecast
fig.add_trace(
    go.Scatter(
        x=months,
        y=FORECAST_MEAN_12M,
        mode="lines+markers",
        name="SARIMA Forecast",
        line=dict(color="#E8B4B8", width=2),
        marker=dict(size=6)
    ),
    row=2, col=1
)

# Budget tier details table (BOTTOM RIGHT)
TABLE_DATA = []
for key in ["CONSERVATIVE", "MODERATE", "TARGET", "OPTIMIZED"]:
    TIER = BUDGET_TIERS[key]
    TABLE_DATA.append([
        TIER["NAME"],
        f"${TIER["MONTHLY"]:,.0f}",
        f"${TIER["ANNUAL"]:,.0f}",
        f"{TIER["BUFFER_PCT"]:+.0f}%"
    ])

fig.add_trace(
    go.Table(
        header=dict(
            values=["<b>Tier</b>", "<b>Monthly</b>", "<b>Annual</b>", "<b>Buffer</b>"],
            fill_color="#1e293b",
            align="left",
            font=dict(color="white", size=11),
            height=30
        ),
        cells=dict(
            values=list(zip(*TABLE_DATA)),
            fill_color=[
                [BUDGET_TIERS[k]["COLOR"] for k in ["CONSERVATIVE", "MODERATE", "TARGET", "OPTIMIZED"]],
                "#475569",
                "#475569",
                "#475569"
            ],
            align="left",
            font=dict(color="white", size=10),
            height=28
        )
    ),
    row=2, col=2
)

# Update axes
fig.update_xaxes(title_text="Budget Tier", row=1, col=1)
fig.update_yaxes(title_text="Monthly Budget ($)", row=1, col=1)

fig.update_xaxes(title_text="Month", row=2, col=1)
fig.update_yaxes(title_text="Budget ($)", row=2, col=1)

fig.update_layout(
    title=dict(
        text="Budget Recommendations - Tiered Approach",
        x=0.5,
        xanchor="center",
        font=dict(size=20)
    ),
    height=1000,
    width=1000,
    template="plotly_dark",
    showlegend=True,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=-0.08,
        xanchor="center",
        x=0.3
    )
)

fig.show()

FIG_TITLE = "Budget Recommendations - Tiered Approach"
PLOT_CAPTION = f"""
The tiered budget framework provides four evidence-based spending targets tailored to different financial priorities and risk tolerances. The Conservative budget (${BUDGET_TIERS["CONSERVATIVE"]["MONTHLY"]:,.0f}/month) sets the upper bound at the SARIMA 95% confidence interval, ensuring coverage of typical spending variability with minimal overage risk - ideal for irregular income or conservative financial planning. The Moderate budget (${BUDGET_TIERS["MODERATE"]["MONTHLY"]:,.0f}/month) adds one standard deviation to the forecast mean, balancing protection against volatility with reasonable constraint. The Target budget (${BUDGET_TIERS["TARGET"]["MONTHLY"]:,.0f}/month) represents the model"s best prediction of necessary spending, serving as an aspirational goal. The Optimized budget (${BUDGET_TIERS["OPTIMIZED"]["MONTHLY"]:,.0f}/month) incorporates a 10% efficiency target, achievable through category-level discipline and waste elimination. The 12-month projection (bottom-left) visualizes these tiers against the SARIMA forecast, with the shaded range representing the full spectrum of recommended budgets. Annual totals range from ${BUDGET_TIERS["OPTIMIZED"]["ANNUAL"]:,.0f} to ${BUDGET_TIERS["CONSERVATIVE"]["ANNUAL"]:,.0f}, offering flexibility based on financial goals and circumstances.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="BUDGET_RECOMMENDATIONS_TIERED_APPROACH.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The tiered budget framework provides four evidence-based spending targets tailored to different financial priorities and risk
tolerances. The Conservative budget ($969/month) sets the upper bound at the SARIMA 95% confidence interval, ensuring coverage of
typical spending variability with minimal overage risk - ideal for irregular income or conservative financial planning. The
Moderate budget ($717/month) adds one standard deviation to the forecast mean, balancing protection against volatility with
reasonable constraint. The Target budget ($709/month) represents the model"s best prediction of necessary spending, serving as an
aspirational goal. The Optimized budget ($638/month) incorporates a 10% efficiency target, achievable through category-level
discipline and waste elimination. The 12-month projection (bottom-left) visualizes these tiers against the SARIMA forecast, with
the shaded range representing the full spectrum of recommended budgets. Annual totals range from $7,658 to $11,628, offering
flexibility based on financial goals and circumstances.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\BUDGET_RECOMMENDATIONS_TIERED.png
✅ Registered component: BUDGET_RECOMMENDATIONS_TIERED.png with Title Budget Recommendations - Tiered Approach

In [185]:
# Create month-by-month budget guidance
MONTHLY_GUIDANCE = pd.DataFrame({
    "MONTH": range(1, 13),
    "FORECAST": FORECAST_MEAN_12M.values,
    "LOWER_CI": FORECAST_CI_12M.iloc[:, 0].values,
    "UPPER_CI": FORECAST_CI_12M.iloc[:, 1].values
})

# Add budget tier recommendations per month
for tier_key in ["CONSERVATIVE", "MODERATE", "TARGET", "OPTIMIZED"]:
    MONTHLY_GUIDANCE[tier_key.upper()] = BUDGET_TIERS[tier_key]["MONTHLY"]

# Add seasonal insights
MONTH_NAMES_FULL = ["January", "February", "March", "April", "May", "June",
                   "July", "August", "September", "October", "November", "December"]
MONTHLY_GUIDANCE["MONTH_NAME"] = MONTH_NAMES_FULL

# Calculate variance from target
MONTHLY_GUIDANCE["VS_TARGET"] = MONTHLY_GUIDANCE["FORECAST"] - MONTHLY_GUIDANCE["TARGET"]
MONTHLY_GUIDANCE["VS_TARGET_PCT"] = (MONTHLY_GUIDANCE["VS_TARGET"] / MONTHLY_GUIDANCE["TARGET"]) * 100

# Identify high/low spending months
HIGH_MONTHS = MONTHLY_GUIDANCE.nlargest(3, "FORECAST")["MONTH_NAME"].tolist()
LOW_MONTHS = MONTHLY_GUIDANCE.nsmallest(3, "FORECAST")["MONTH_NAME"].tolist()

print("\n" + "="*70)
print("MONTHLY BUDGET ALLOCATION GUIDANCE")
print("="*70)

print(f"\n📅 MONTH-BY-MONTH RECOMMENDATIONS:\n")
print(f"{"Month":<12} {"Forecast":<10} {"Conservative":<12} {"Target":<10} {"Optimized":<10}")
print("-" * 70)

for idx, row in MONTHLY_GUIDANCE.iterrows():
    print(f"{row["MONTH_NAME"]:<12} ${row["FORECAST"]:<9,.0f} ${row["CONSERVATIVE"]:<11,.0f} "
          f"${row["TARGET"]:<9,.0f} ${row["OPTIMIZED"]:<9,.0f}")

print("\n" + "="*70)

print(f"\n📈 SEASONAL PATTERNS:")
print(f"  Highest Spending Months: {", ".join(HIGH_MONTHS)}")
print(f"  Lowest Spending Months:  {", ".join(LOW_MONTHS)}")

HIGH_AVG = MONTHLY_GUIDANCE.nlargest(3, "FORECAST")["FORECAST"].mean()
LOW_AVG = MONTHLY_GUIDANCE.nsmallest(3, "FORECAST")["FORECAST"].mean()
SEASONAL_VARIANCE = HIGH_AVG - LOW_AVG

print(f"\n  Seasonal Variance: ${SEASONAL_VARIANCE:.2f} ({SEASONAL_VARIANCE/FORECAST_STATS["MEAN"]*100:.1f}% of average)")
print(f"  → Plan for ${SEASONAL_VARIANCE:.2f} higher budgets in {", ".join(HIGH_MONTHS[:2])}")

print("\n" + "="*70)

======================================================================
MONTHLY BUDGET ALLOCATION GUIDANCE
======================================================================

📅 MONTH-BY-MONTH RECOMMENDATIONS:

Month        Forecast   Conservative Target     Optimized
----------------------------------------------------------------------
January      $722       $969         $709       $638
February     $702       $969         $709       $638
March        $704       $969         $709       $638
April        $704       $969         $709       $638
May          $706       $969         $709       $638
June         $715       $969         $709       $638
July         $711       $969         $709       $638
August       $713       $969         $709       $638
September    $699       $969         $709       $638
October      $721       $969         $709       $638
November     $699       $969         $709       $638
December     $713       $969         $709       $638

======================================================================

📈 SEASONAL PATTERNS:
  Highest Spending Months: January, October, June
  Lowest Spending Months:  September, November, February

  Seasonal Variance: $19.10 (2.7% of average)
  → Plan for $19.10 higher budgets in January, October

======================================================================

In [ ]:
# Visualization - Calendar heatmap style
fig = go.Figure()

# Create budget adherence zones
fig.add_trace(
    go.Bar(
        x=MONTHLY_GUIDANCE["MONTH_NAME"],
        y=MONTHLY_GUIDANCE["CONSERVATIVE"],
        name="Conservative Budget",
        marker=dict(color="rgba(78, 205, 196, 0.3)"),
        showlegend=True
    )
)

fig.add_trace(
    go.Bar(
        x=MONTHLY_GUIDANCE["MONTH_NAME"],
        y=MONTHLY_GUIDANCE["TARGET"] - MONTHLY_GUIDANCE["CONSERVATIVE"],
        name="Target Range",
        marker=dict(color="rgba(124, 173, 220, 0.4)"),
        base=MONTHLY_GUIDANCE["CONSERVATIVE"],
        showlegend=True
    )
)

# Actual forecast as line
fig.add_trace(
    go.Scatter(
        x=MONTHLY_GUIDANCE["MONTH_NAME"],
        y=MONTHLY_GUIDANCE["FORECAST"],
        mode="lines+markers",
        name="SARIMA Forecast",
        line=dict(color="#E8B4B8", width=3),
        marker=dict(size=10, symbol="diamond")
    )
)

# Optimized target as line
fig.add_trace(
    go.Scatter(
        x=MONTHLY_GUIDANCE["MONTH_NAME"],
        y=MONTHLY_GUIDANCE["OPTIMIZED"],
        mode="lines+markers",
        name="Optimized Target",
        line=dict(color="#4CAF50", width=2, dash="dot"),
        marker=dict(size=8)
    )
)

fig.update_layout(
    title=dict(
        text="Month-by-Month Budget Guidance",
        x=0.5,
        xanchor="center",
        font=dict(size=20)
    ),
    xaxis_title="Month",
    yaxis_title="Budget ($)",
    barmode="stack",
    height=600,
    width=1000,
    template="plotly_dark",
    showlegend=True,
    hovermode="x unified"
)

fig.show()

FIG_TITLE = "Month-by-Month Budget Guidance"
PLOT_CAPTION = f"""
Monthly budget allocation guidance accounts for seasonal spending patterns identified through SARIMA forecasting. The stacked bars represent budget flexibility zones: the Conservative layer (teal) provides a safety buffer for unexpected expenses, while the Target range (blue) narrows to the model"s predicted spending. The SARIMA forecast line (pink diamonds) shows expected spending trajectory, revealing higher expenditure periods in {", ".join(HIGH_MONTHS[:2])} and lower spending in {", ".join(LOW_MONTHS[:2])}. The Optimized target (green dots) maintains a consistent efficiency goal across all months. Seasonal variance of ${SEASONAL_VARIANCE:.2f} ({SEASONAL_VARIANCE/FORECAST_STATS["MEAN"]*100:.1f}% of monthly average) indicates material spending fluctuation throughout the year, suggesting the need for month-specific budget planning rather than uniform annual allocation. This granular guidance enables proactive budget adjustments aligned with predictable seasonal patterns.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="BUDGET_RECOMMENDATIONS_MONTHLY_BUDGET_GUIDANCE.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 Monthly budget allocation guidance accounts for seasonal spending patterns identified through SARIMA forecasting. The stacked
bars represent budget flexibility zones: the Conservative layer (teal) provides a safety buffer for unexpected expenses, while the
Target range (blue) narrows to the model"s predicted spending. The SARIMA forecast line (pink diamonds) shows expected spending
trajectory, revealing higher expenditure periods in January, October and lower spending in September, November. The Optimized
target (green dots) maintains a consistent efficiency goal across all months. Seasonal variance of $19.10 (2.7% of monthly
average) indicates material spending fluctuation throughout the year, suggesting the need for month-specific budget planning
rather than uniform annual allocation. This granular guidance enables proactive budget adjustments aligned with predictable
seasonal patterns.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\MONTHLY_BUDGET_GUIDANCE.png
✅ Registered component: MONTHLY_BUDGET_GUIDANCE.png with Title Month-by-Month Budget Guidance

<h2>Decision Playbook</h2>
<p>Among several possible scenarios, what kind of actions should be undertaken?</p>
<p> --> To have a clear action table on each outcome.</p>

In [ ]:
# Report Management
SUBSECTION_TITLE = "Decision Playbook"
SUBSECTION_CAPTION = "To have a clear action table on each outcome"
REGISTER_REPORT_COMPONENT(
    TITLE=SUBSECTION_TITLE,
    CONTENT=SUBSECTION_CAPTION,
    TYPE="text",
    HEADING="h3",
    BODY="normal",
    PATH=None,
    REPORTING_TAG="PREDICTIVE_AND_PRESCRIPTIVE_DECISION_PLAYBOOK"
)

✅ Registered component: PREDICTIVE_AND_PRESCRIPTIVE_BUDGET_RECOMMENDATION with Title Budget Recommendation

In [188]:
# Define decision tree based on all analysis
DECISION_RULES = {
    'MONTHLY_REVIEW': {
        'NAME': 'Monthly Spending Review Protocol',
        'TRIGGERS': [
            {
                'CONDITION': 'Actual spending within Target budget',
                'STATUS': 'GREEN',
                'ACTION': 'Continue current spending patterns',
                'FREQUENCY': 'Monthly review',
                'PRIORITY': 'Low'
            },
            {
                'CONDITION': 'Actual spending between Target and Moderate budget',
                'STATUS': 'YELLOW',
                'ACTION': 'Review discretionary categories, identify causes',
                'FREQUENCY': 'Weekly monitoring',
                'PRIORITY': 'Medium'
            },
            {
                'CONDITION': 'Actual spending exceeds Moderate budget',
                'STATUS': 'ORANGE',
                'ACTION': 'Immediate category analysis, implement cutbacks',
                'FREQUENCY': 'Daily tracking',
                'PRIORITY': 'High'
            },
            {
                'CONDITION': 'Actual spending exceeds Conservative budget',
                'STATUS': 'RED',
                'ACTION': 'Emergency review - reduce all non-essential spending',
                'FREQUENCY': 'Real-time monitoring',
                'PRIORITY': 'Critical'
            }
        ]
    },
    'ANOMALY_RESPONSE': {
        'NAME': 'Anomaly Detection Response',
        'TRIGGERS': [
            {
                'CONDITION': 'SARIMA flags anomaly (outside CI)',
                'STATUS': 'ALERT',
                'ACTION': 'Investigate cause - expected or unexpected?',
                'FREQUENCY': 'Immediate',
                'PRIORITY': 'High'
            },
            {
                'CONDITION': '2+ detection methods flag anomaly',
                'STATUS': 'CONFIRMED',
                'ACTION': 'Document cause, adjust budget if recurring pattern',
                'FREQUENCY': 'Within 48 hours',
                'PRIORITY': 'High'
            },
            {
                'CONDITION': 'Anomaly = planned expense (e.g., travel)',
                'STATUS': 'EXPECTED',
                'ACTION': 'Log as one-time event, no action needed',
                'FREQUENCY': 'Post-month review',
                'PRIORITY': 'Low'
            },
            {
                'CONDITION': 'Anomaly = unplanned expense (emergency)',
                'STATUS': 'UNEXPECTED',
                'ACTION': 'Build emergency fund buffer, review insurance',
                'FREQUENCY': 'Quarterly planning',
                'PRIORITY': 'Medium'
            }
        ]
    },
    'BUDGET_ADJUSTMENT': {
        'NAME': 'Budget Adjustment Protocol',
        'TRIGGERS': [
            {
                'CONDITION': 'Consistent underspending (3+ months below Target)',
                'STATUS': 'SURPLUS',
                'ACTION': 'Reduce budget tier or allocate to savings/investments',
                'FREQUENCY': 'Quarterly review',
                'PRIORITY': 'Low'
            },
            {
                'CONDITION': 'Consistent overspending (3+ months above Moderate)',
                'STATUS': 'DEFICIT',
                'ACTION': 'Increase budget tier OR implement spending cuts',
                'FREQUENCY': 'Immediate',
                'PRIORITY': 'High'
            },
            {
                'CONDITION': 'Forecast error >20% for 2+ consecutive months',
                'STATUS': 'MODEL_DRIFT',
                'ACTION': 'Refit SARIMA model with recent data',
                'FREQUENCY': 'Quarterly',
                'PRIORITY': 'Medium'
            },
            {
                'CONDITION': 'Major life change (income, family, location)',
                'STATUS': 'REGIME_CHANGE',
                'ACTION': 'Full budget reset - reanalyze spending patterns',
                'FREQUENCY': 'As needed',
                'PRIORITY': 'High'
            }
        ]
    }
}

print("="*80)
print("DECISION PLAYBOOK - ACTION TRIGGERS & RESPONSE PROTOCOLS")
print("="*80)

for category_key, category in DECISION_RULES.items():
    print(f"\n📋 {category['NAME'].upper()}")
    print("-" * 80)
    
    for i, trigger in enumerate(category['TRIGGERS'], 1):
        print(f"\n  {i}. CONDITION: {trigger['CONDITION']}")
        print(f"     Status:    [{trigger['STATUS']}]")
        print(f"     Action:    {trigger['ACTION']}")
        print(f"     Frequency: {trigger['FREQUENCY']}")
        print(f"     Priority:  {trigger['PRIORITY']}")

print("\n" + "="*80)

================================================================================
DECISION PLAYBOOK - ACTION TRIGGERS & RESPONSE PROTOCOLS
================================================================================

📋 MONTHLY SPENDING REVIEW PROTOCOL
--------------------------------------------------------------------------------

  1. CONDITION: Actual spending within Target budget
     Status:    [GREEN]
     Action:    Continue current spending patterns
     Frequency: Monthly review
     Priority:  Low

  2. CONDITION: Actual spending between Target and Moderate budget
     Status:    [YELLOW]
     Action:    Review discretionary categories, identify causes
     Frequency: Weekly monitoring
     Priority:  Medium

  3. CONDITION: Actual spending exceeds Moderate budget
     Status:    [ORANGE]
     Action:    Immediate category analysis, implement cutbacks
     Frequency: Daily tracking
     Priority:  High

  4. CONDITION: Actual spending exceeds Conservative budget
     Status:    [RED]
     Action:    Emergency review - reduce all non-essential spending
     Frequency: Real-time monitoring
     Priority:  Critical

📋 ANOMALY DETECTION RESPONSE
--------------------------------------------------------------------------------

  1. CONDITION: SARIMA flags anomaly (outside CI)
     Status:    [ALERT]
     Action:    Investigate cause - expected or unexpected?
     Frequency: Immediate
     Priority:  High

  2. CONDITION: 2+ detection methods flag anomaly
     Status:    [CONFIRMED]
     Action:    Document cause, adjust budget if recurring pattern
     Frequency: Within 48 hours
     Priority:  High

  3. CONDITION: Anomaly = planned expense (e.g., travel)
     Status:    [EXPECTED]
     Action:    Log as one-time event, no action needed
     Frequency: Post-month review
     Priority:  Low

  4. CONDITION: Anomaly = unplanned expense (emergency)
     Status:    [UNEXPECTED]
     Action:    Build emergency fund buffer, review insurance
     Frequency: Quarterly planning
     Priority:  Medium

📋 BUDGET ADJUSTMENT PROTOCOL
--------------------------------------------------------------------------------

  1. CONDITION: Consistent underspending (3+ months below Target)
     Status:    [SURPLUS]
     Action:    Reduce budget tier or allocate to savings/investments
     Frequency: Quarterly review
     Priority:  Low

  2. CONDITION: Consistent overspending (3+ months above Moderate)
     Status:    [DEFICIT]
     Action:    Increase budget tier OR implement spending cuts
     Frequency: Immediate
     Priority:  High

  3. CONDITION: Forecast error >20% for 2+ consecutive months
     Status:    [MODEL_DRIFT]
     Action:    Refit SARIMA model with recent data
     Frequency: Quarterly
     Priority:  Medium

  4. CONDITION: Major life change (income, family, location)
     Status:    [REGIME_CHANGE]
     Action:    Full budget reset - reanalyze spending patterns
     Frequency: As needed
     Priority:  High

================================================================================

In [ ]:
# Create decision flowchart
fig = go.Figure()

# Define decision tree structure
DECISION_TREE = {
    'LEVEL_0': {
        'TEXT': 'MONTHLY SPENDING REVIEW',
        'X': 0.5, 
        'Y': 1.0,
        'COLOR': '#7FADDC'
    },
    'LEVEL_1_GREEN': {
        'TEXT': 'Within Target<br>Budget?',
        'X': 0.2, 
        'Y': 0.8,
        'COLOR': '#4CAF50'
    },
    'LEVEL_1_YELLOW': {
        'TEXT': 'Within Moderate<br>Budget?',
        'X': 0.4, 
        'Y': 0.8,
        'COLOR': '#FFC107'
    },
    'LEVEL_1_ORANGE': {
        'TEXT': 'Within Conservative<br>Budget?',
        'X': 0.6, 
        'Y': 0.8,
        'COLOR': '#FF9800'
    },
    'LEVEL_1_RED': {
        'TEXT': 'Exceeded All<br>Budgets?',
        'X': 0.8, 
        'Y': 0.8,
        'COLOR': '#F44336'
    },
    # Actions
    'ACTION_GREEN': {
        'TEXT': '✓ Continue<br>Current Pattern',
        'X': 0.2, 
        'Y': 0.6,
        'COLOR': '#4CAF50'
    },
    'ACTION_YELLOW': {
        'TEXT': '⚠ Review<br>Categories',
        'X': 0.4, 
        'Y': 0.6,
        'COLOR': '#FFC107'
    },
    'ACTION_ORANGE': {
        'TEXT': '⚠ Implement<br>Cutbacks',
        'X': 0.6, 
        'Y': 0.6,
        'COLOR': '#FF9800'
    },
    'ACTION_RED': {
        'TEXT': '🚨 Emergency<br>Review',
        'X': 0.8, 
        'Y': 0.6,
        'COLOR': '#F44336'
    },
    # Follow-ups
    'FOLLOWUP_GREEN': {
        'TEXT': 'Monthly<br>Review Only',
        'X': 0.2, 
        'Y': 0.4,
        'COLOR': '#4CAF50'
    },
    'FOLLOWUP_YELLOW': {
        'TEXT': 'Weekly<br>Monitoring',
        'X': 0.4, 
        'Y': 0.4,
        'COLOR': '#FFC107'
    },
    'FOLLOWUP_ORANGE': {
        'TEXT': 'Daily<br>Tracking',
        'X': 0.6, 
        'Y': 0.4,
        'COLOR': '#FF9800'
    },
    'FOLLOWUP_RED': {
        'TEXT': 'Real-time<br>Monitoring',
        'X': 0.8, 
        'Y': 0.4,
        'COLOR': '#F44336'
    }
}

# Add nodes
for node_id, node in DECISION_TREE.items():
    fig.add_trace(go.Scatter(
        x=[node['X']],
        y=[node['Y']],
        mode='markers+text',
        marker=dict(
            size=80 if 'level_0' in node_id else 60,
            color=node['COLOR'],
            line=dict(color='white', width=2)
        ),
        text=node['TEXT'],
        textposition='middle center',
        textfont=dict(size=9, color='white'),
        showlegend=False,
        hoverinfo='skip'
    ))

# Add connecting lines
CONNECTIONS = [
    ('LEVEL_0', 'LEVEL_1_GREEN'),
    ('LEVEL_0', 'LEVEL_1_YELLOW'),
    ('LEVEL_0', 'LEVEL_1_ORANGE'),
    ('LEVEL_0', 'LEVEL_1_RED'),
    ('LEVEL_1_GREEN', 'ACTION_GREEN'),
    ('LEVEL_1_YELLOW', 'ACTION_YELLOW'),
    ('LEVEL_1_ORANGE', 'ACTION_ORANGE'),
    ('LEVEL_1_RED', 'ACTION_RED'),
    ('ACTION_GREEN', 'FOLLOWUP_GREEN'),
    ('ACTION_YELLOW', 'FOLLOWUP_YELLOW'),
    ('ACTION_ORANGE', 'FOLLOWUP_ORANGE'),
    ('ACTION_RED', 'FOLLOWUP_RED')
]

for start, end in CONNECTIONS:
    fig.add_trace(go.Scatter(
        x=[DECISION_TREE[start]['X'], DECISION_TREE[end]['X']],
        y=[DECISION_TREE[start]['Y'], DECISION_TREE[end]['Y']],
        mode='lines',
        line=dict(color='rgba(255,255,255,0.3)', width=2),
        showlegend=False,
        hoverinfo='skip'
    ))

fig.update_layout(
    title=dict(
        text="Decision Tree - Monthly Budget Review Protocol",
        x=0.5,
        xanchor='center',
        font=dict(size=20)
    ),
    xaxis=dict(visible=False, range=[0, 1]),
    yaxis=dict(visible=False, range=[0.3, 1.1]),
    height=700,
    width=1000,
    template="plotly_dark",
    showlegend=False
)

fig.show()

FIG_TITLE = "Decision Tree - Monthly Budget Review Protocol"
PLOT_CAPTION = """
The decision tree provides a structured protocol for monthly spending review and response. At month-end, actual spending is evaluated against the four budget tiers established previously Green status (within Target budget) requires only routine monthly review with no intervention. Yellow status (between Target and Moderate budgets) triggers weekly monitoring and category-level analysis to identify spending drivers. Orange status (between Moderate and Conservative budgets) necessitates immediate cutbacks and daily expense tracking. Red status (exceeding all budgets) demands emergency review and real-time spending monitoring. This tiered response system ensures intervention intensity scales appropriately with spending deviation magnitude, preventing both overreaction to minor variances and under-response to serious budget breaches.
"""

PLOT_CAPTION_WRAPPED = textwrap.fill(PLOT_CAPTION, width=130)
print(PLOT_CAPTION_WRAPPED)

print("\n--------------------------------\n")

SAVE_PLOT_AND_REGISTER(
    fig,
    FILENAME="DECISION_PLAYBOOK_DECISION_TREE_BUDGET_REVIEW.png",
    TITLE=FIG_TITLE,
    CAPTION=PLOT_CAPTION_WRAPPED
)

 The decision tree provides a structured protocol for monthly spending review and response. At month-end, actual spending is
evaluated against the four budget tiers established previously Green status (within Target budget) requires only routine monthly
review with no intervention. Yellow status (between Target and Moderate budgets) triggers weekly monitoring and category-level
analysis to identify spending drivers. Orange status (between Moderate and Conservative budgets) necessitates immediate cutbacks
and daily expense tracking. Red status (exceeding all budgets) demands emergency review and real-time spending monitoring. This
tiered response system ensures intervention intensity scales appropriately with spending deviation magnitude, preventing both
overreaction to minor variances and under-response to serious budget breaches.

--------------------------------

✅ PNG saved with Dynamic Path: ASSETS\PLOTS\DECISION_TREE_BUDGET_REVIEW.png
✅ Registered component: DECISION_TREE_BUDGET_REVIEW.png with Title Decision Tree - Monthly Budget Review Protocol

In [187]:
# Generate reports
GENERATE_REPORT()

Report generated successfully at REPORT.md.

<hr>
<p><center>End of the Document</center></p>
<hr>